window.masteryData = {
  Sword: [
    {
      name: "تدريب السيف",
      maxLvl: 10,
      req: "1H السيف المستوى 1",
      template: "When 1h Sword is equipped, normal attack's damage +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "الفروسية",
      maxLvl: 10,
      req: "1H السيف المستوى 1",
      template: "يزيد الهجوم والدفاع عندما يتم تجهيز السيف بـ +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "flat_atk_def",
      active: true,
    },
    {
      name: "Sword's Blow",
      maxLvl: 10,
      req: "1H السيف المستوى 1",
      template: "After hitting an enemy with Switch, buffs the player's Attack and Defense for 8 seconds by +{val}%",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الموقف الأساسي",
      maxLvl: 10,
      req: "1H السيف المستوى 1",
      template: "يضيف +{val} ضررًا إضافيًا للعدو عند الهجوم (جميع الأسلحة)",
      calc: (lvl) => lvl * 5,
      bonusType: "flat_damage",
      active: true,
    },
    {
      name: "الضربة الكاملة",
      maxLvl: 10,
      req: "تدريب السيف Lv.5",
      template: "عندما يتم تجهيز سيف 1H، فإن الضرر الذي يلحق بالأعداء ضعيف لدرجة القطع +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "إتقان السيف",
      maxLvl: 10,
      req: "تدريب السيف المستوى 5، الضربة الكاملة المستوى 5",
      template: "عندما يتم تجهيز السيف لمدة ساعة واحدة، قوة مهارة السيف +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "علامة المحارب",
      maxLvl: 1,
      req: "1ح السيف م.10، الضربة الكاملة م.5",
      template: "عندما يتم تجهيز 1H Sword، قم باستعادة +{val}% من الصحة عند القتل",
      calc: (lvl) => lvl * 2,
      bonusType: "healing_percent",
      active: true,
    },
    {
      name: "تحسين التحكم بالسيف",
      maxLvl: 1,
      req: "1ح السيف م.10، الوضع الأساسي م.5",
      template: "عندما يتم تجهيز سيف 1H، تكلفة النقاط الذهنية - {val} للخطوة",
      calc: (lvl) => lvl * 1,
      bonusType: "step_reduction",
      active: true,
    },
    {
      name: "غريزة المعركة",
      maxLvl: 10,
      req: "1ح السيف م.10، الوضع الأساسي م.5",
      template: "الهجوم + {val} (جميع الأسلحة)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "غريزة البقاء",
      maxLvl: 10,
      req: "1ح السيف المستوى 15، علامة المحارب المستوى 1",
      template: "الحد الأقصى من الصحة +{val}% (جميع الأسلحة)",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "مزيج",
      maxLvl: 10,
      req: "1ح السيف م.20، غريزة البقاء م.5",
      template: "عندما يتم تجهيز سيف 1H، ضرر التبديل +{val}%",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "المعرفة بالأسلحة",
      maxLvl: 10,
      req: "1H السيف م.25، المجموعة م.5",
      template: "الهجوم +{val}% (جميع الأسلحة)",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.699999999999999, 5][
          lvl - 1
        ] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "تبديل المسؤول",
      maxLvl: 10,
      req: "1ح السيف المستوى 30، معرفة السلاح المستوى 5",
      template: "عندما يتم تجهيز 1H Sword، قم باسترداد +{val} SP عند استخدام مهارة التبديل",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "sp_recovery_flat",
      active: true,
    },
    {
      name: "سر السيف",
      maxLvl: 10,
      req: "1H السيف المستوى 35، شحن التبديل المستوى 1",
      template: "عند تجهيز سيف 1H، الهجوم +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف",
      maxLvl: 10,
      req: "1ح السيف المستوى 40، معرفة السلاح المستوى 10",
      template: "قوة مهارة السيف +{val}% (فعالة مع جميع الأسلحة)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "ss_power",
      active: true,
    },
    {
      name: "الشحن الزائد I (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "1H السيف Lv.45",
      template: "سيتم شحن مقياس التبديل حتى المستوى الثالث عند تجهيز 1H Sword. الضرر +200% عند استخدام المفتاح في المستوى الثالث. ",
      calc: (lvl) => 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج اللهب (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "1ح السيف م.50، إتقان مهارة السيف م.5",
      template: "هجوم +{val}% عند الهجوم باستخدام عنصر النار والتزود بسيف 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج أكوا (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "1ح السيف م.50، إتقان مهارة السيف م.5",
      template: "هجوم +{val}% عند الهجوم باستخدام عنصر الماء والتزود بسيف 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الرياح (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "1ح السيف م.50، إتقان مهارة السيف م.5",
      template: "هجوم +{val}% عند الهجوم باستخدام عنصر الرياح والتزود بسيف 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الأرض (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "1ح السيف م.50، إتقان مهارة السيف م.5",
      template: "هجوم +{val}% عند الهجوم باستخدام عنصر الأرض والتزود بسيف 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "تألق الوهج (1H السيف)",
      maxLvl: 10,
      req: "1ح السيف م.50، إتقان مهارة السيف م.5",
      template: "هجوم +{val}% عند الهجوم باستخدام العنصر المقدس والتزود بسيف 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الوهج الداكن (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "1ح السيف م.50، إتقان مهارة السيف م.5",
      template: "هجوم +{val}% عند الهجوم باستخدام Dark Element والتزود بسيف 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة البقاء (السيف 1H)",
      maxLvl: 10,
      req: "1ح السيف المستوى 55، إتقان مهارة السيف المستوى 5",
      template: "HP +{val} عند تجهيز سيف 1H",
      calc: (lvl) => lvl * 100,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "كفاءة القطع (السيف 1H)",
      maxLvl: 10,
      req: "1H سيف م.60، خبرة البقاء (1H سيف) Lv.5",
      template: "عندما يتم تجهيز 1H Sword، فإن الضرر الذي يلحق بالأعداء ضعيف لدرجة القطع +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية (سيف 1H)",
      maxLvl: 10,
      req: "1H سيف م.65، خبرة البقاء (1H سيف) Lv.5",
      template: "الدفاع +{val} عند تجهيز سيف 1H",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "def_flat",
      active: true,
    },
    {
      name: "حارس حرق",
      maxLvl: 10,
      req: "سيف 1H م.70، خبرة دفاعية قوية (سيف 1H) م.5",
      template: "عند تجهيز سيف 1H، يحدث ضرر الحروق -{val}",
      calc: (lvl) =>
        [-4.5, -4, -3.5, -3, -2.5, -2, -1.5, -1, -0.5, 0][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس (السيف ساعة واحدة)",
      maxLvl: 10,
      req: "سيف 1H م.75، خبرة دفاعية قوية (سيف 1H) م.5",
      template: "هجوم +{val} عند تجهيز سيف 1H",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "كسر صعب (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف م.80، خبرة الهجوم الشرس (1H سيف) Lv.5",
      template: "عندما يتم تجهيز 1H Sword، هجوم +{val} عند استخدام Break",
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "إتقان مهارة السيف الفردي (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف م.85، خبرة الهجوم الشرس (1H سيف) Lv.5",
      template: "قوة مهارة السيف (فردية) +{val}% عند التزود بسيف 1H",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "skill_power",
      active: true,
    },
    {
      name: "صعود اللهب (السيف ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف م.90، خبرة الهجوم الشرس (1H سيف) Lv.5",
      template: "عند تجهيز سيف 1H، هجوم +{val} عند استخدام عنصر النار",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "إتقان مهارة السيف (السيف لمدة ساعة واحدة)",
      maxLvl: 10,
      req: "سيف 1 ساعة م.95، إتقان مهارة سيف واحد (سيف 1 ساعة) مستوى 5",
      template: "ضرر مهارة السيف +{val}% (فعال مع جميع الأسلحة)",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "شحنة اللهب (سيف ساعة واحدة)",
      maxLvl: 10,
      req: "سيف 1ساعة مستوى 100، كفاءة مهارة السيف (سيف ساعة واحدة) مستوى 5",
      template: "عند التزود بسيف ساعة واحدة، ضرر عنصر النار +{val}%",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "damage_percent_fire",
      active: true,
    },
    {
      name: "حارس الشدائد",
      maxLvl: 10,
      req: "سيف 1H المستوى 105، شحنة اللهب (سيف 1H) المستوى 5",
      template: "الدفاع +{val} عند التزود بسيف 1H وتكون الصحة 25% أو أقل",
      calc: (lvl) => lvl * 10,
      bonusType: "def_flat",
      active: true,
    },
    ,
    {
      name: "فاحش I",
      maxLvl: 1,
      req: "إتقان السيف لمدة ساعة - المستوى 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة البقاء على قيد الحياة",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 55، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 65، وخبرة البقاء (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 75، خبرة دفاعية قوية (سيف لمدة ساعة واحدة) - المستوى 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "إتقان مهارة السيف الواحد",
      maxLvl: 10,
      req: "كفاءة السيف لمدة ساعة واحدة - المستوى 85، خبرة الهجوم الشرس (سيف ساعة واحدة) - المستوى 5",
      template: "تزيد قوة مهارات السيف الفردية بنسبة +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "إتقان مهارة السيف",
      maxLvl: 10,
      req: "مهارة السيف ساعة واحدة - المستوى 95، إتقان مهارة السيف الفردي (سيف الساعة الواحدة) - المستوى 5",
      template: "تزيد قوة مهارات السيف بنسبة +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "استراحة صعبة",
      maxLvl: 10,
      req: "كفاءة السيف لمدة ساعة واحدة - المستوى 80، خبرة الهجوم الشرس (سيف ساعة واحدة) - المستوى 5",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "صعود اللهب",
      maxLvl: 10,
      req: "مهارة السيف ساعة واحدة - المستوى 90، إتقان مهارة السيف الفردي (سيف الساعة الواحدة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر النار. + {فال}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تهمة اللهب",
      maxLvl: 10,
      req: "إتقان السيف ساعة واحدة - المستوى 100، إتقان مهارة السيف (السيف 1 ساعة) - المستوى 5",
      template: "يزيد الضرر الناتج عن عنصر النار. + {فال}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 50، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر النار. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "أكوا توهج",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 50، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الماء. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الرياح",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 50، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الرياح. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الأرض",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 50، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الأرض. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تألق توهج",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 50، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر المقدس. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الوهج الداكن",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 50، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر الداكن. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الموقف التطبيقي",
      maxLvl: 10,
      req: "حرر الكريستال (M) × 1",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 125,
      bonusType: "passive",
      active: true,
    },
    {
      name: "موقف متطور",
      maxLvl: 10,
      req: "تحرير الكريستال (L) × 3",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تطوير تقنية السيف",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 50، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "تزيد قوة مهارات السيف بنسبة +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كسر الأساسيات",
      maxLvl: 10,
      req: "إتقان السيف لمدة ساعة واحدة - المستوى 50، إتقان مهارة السيف (السيف لمدة ساعة واحدة) - المستوى 5",
      template: "تزيد قيمة الكسر لمهارات السيف بمقدار +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "هجوم سلسلة المستعبدين",
      maxLvl: 10,
      req: "مهارة السيف ساعة واحدة - المستوى 110، حارس الشدائد - المستوى 5",
      template: "تزيد قوة مهارات السيف المستخدمة في Switch بنسبة +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Rapier: [
    {
      name: "تدريب سيف",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.1",
      template: "يزيد من ضرر الهجوم العادي عندما يتم تجهيز سيف ذو حدين 1H+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الهجوم التسلسلي",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.1",
      template: "يزيد الهجوم وفقًا لعدد الضربات التي يتم التعامل معها في مجموعة واحدة، عندما يتم تجهيز سيف ذو حدين+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Rapier's Blow",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.1",
      template: "بعد ضرب عدو باستخدام Switch، يتلقى اللاعب تعزيزًا يؤدي إلى زيادة معدله الحرج لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الموقف الأساسي",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الهدف نقطة ضعف",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.5",
      template: "يزيد الضرر الموجه للأعداء الضعفاء في توجيه الهجمات+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان سيف ذو حدين",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.5",
      template: "Increases rapier skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "علامة المبارز",
      maxLvl: 10,
      req: "1ح سيف ذو حدين المستوى 10",
      template: "استعادة النقاط الذهنية عند التعامل مع الضربة الحرجة+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "sp",
      active: true,
    },
    {
      name: "تحسين التحكم بالسيف",
      maxLvl: 10,
      req: "1ح سيف ذو حدين المستوى 10",
      template: "يقلل تكلفة النقاط الذهنية اللازمة للخطوة+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "غريزة المعركة",
      maxLvl: 10,
      req: "1ح سيف ذو حدين المستوى 15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "غريزة البقاء",
      maxLvl: 10,
      req: "1H كفاءة سيف السيف - المستوى 15، علامة المبارز - المستوى 1",
      template: "الحد الأقصى للصحة +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "سرعة البرق",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.20",
      template: "يزيد الضرر الحرج عندما يكون لدى اللاعب سيف ذو حدين مجهز + {val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "المعرفة بالأسلحة",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "نيزك",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.30",
      template: "يزيد المعدل الحرج لمدة +{val} ثانية بعد الخطوات، عندما يتم تجهيز سيف ذو حدين.",
      calc: (lvl) => [20, 25, 30, 35, 40, 45, 50, 55, 60, 65][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "سر سيف ذو حدين",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.35",
      template: "يزيد الهجوم عندما يتم تجهيز سيف ذو حدين+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الشحن الزائد I (سيف ذو حدين لمدة ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب (سيف سيف لمدة ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر النار+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "أكوا جلو (ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الماء+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الرياح (سيف سيف لمدة ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الرياح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الأرض (سيف سيف لمدة ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الأرض+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "شاين جلو (ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.50",
      template: "يزيد الهجوم عند استخدام العنصر المقدس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الوهج الداكن (سيف سيف لمدة ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.50",
      template: "يزيد الهجوم عند استخدام Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة البقاء (ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كفاءة الدفع (سيف سيف لمدة ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.60",
      template: "يزيد الضرر الموجه للأعداء الضعفاء في توجيه الهجمات+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية (سيف ذو ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "هجوم النقطة الحيوية",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.70",
      template: "يزيد الهجوم بينما يكون التعزيز الذي يزيد من الضرر الحرج ساري المفعول+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس (سيف ذو حدين لمدة ساعة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "طعنة النقطة الحيوية",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.80",
      template: "يزيد الضرر الخطير عند استخدام Skills+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "ضربة دقيقة",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.85",
      template: "يزيد المعدل الحرج عند استخدام المهارات بنسبة +{val}%",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ارتفاع أكوا (سيف سيف لمدة ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.90",
      template: "يزيد الهجوم عند استخدام عنصر الماء+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "ضربة مدروسة",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.95",
      template: "بعد ضرب عدو باستخدام Switch، يتم تطبيق تعزيز على اللاعب، مما يزيد من الضرر الحرج لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "أكوا تشارج (ساعة واحدة)",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.100",
      template: "يزيد الضرر الناتج عن عنصر الماء+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "ضربة الضعف",
      maxLvl: 10,
      req: "1H سيف ذو حدين Lv.105",
      template: "Increases player's Attack when Critical Rate buff is active+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "فاحش I",
      maxLvl: 1,
      req: "ساعة واحدة من كفاءة السيف - المستوى 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة البقاء على قيد الحياة",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 55، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية",
      maxLvl: 10,
      req: "مهارة استخدام السيف لمدة ساعة واحدة - المستوى 65، خبرة البقاء على قيد الحياة (ساعة واحدة) - المستوى 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس",
      maxLvl: 10,
      req: "كفاءة سيف لمدة ساعة واحدة - المستوى 75، خبرة دفاعية قوية (ساعة واحدة) - المستوى 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "أكوا رايز",
      maxLvl: 10,
      req: "ساعة واحدة من كفاءة السيف - المستوى 90، الضربة الدقيقة - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الماء. + {فال}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "أكوا تشارج",
      maxLvl: 10,
      req: "ساعة واحدة من كفاءة السيف - المستوى 100، الضربة المتقنة - المستوى 5",
      template: "يزيد الضرر الناتج عن عنصر الماء. + {فال}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 50، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر النار. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "أكوا توهج",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 50، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الماء. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الرياح",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 50، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الرياح. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الأرض",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 50، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الأرض. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تألق توهج",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 50، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر المقدس. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الوهج الداكن",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 50، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر الداكن. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تطوير تقنية السيف",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 50، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "تزيد قوة مهارات السيف بنسبة +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كسر الأساسيات",
      maxLvl: 10,
      req: "إتقان سيف السيف لمدة ساعة - المستوى 50، إتقان مهارة السيف (ساعة سيف) - المستوى 5",
      template: "تزيد قيمة الكسر لمهارات السيف بمقدار +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "هجوم سلسلة المستعبدين",
      maxLvl: 10,
      req: "ساعة واحدة من كفاءة السيف - المستوى 110، ضربة الضعف - المستوى 5",
      template: "تزيد قوة مهارات السيف المستخدمة في Switch بنسبة +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Club: [
    {
      name: "تدريب النادي",
      maxLvl: 10,
      req: "نادي 1H المستوى 1",
      template: "يزيد من الضرر الناتج عن الهجوم العادي عندما يتم تجهيز الصولجان+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "المعرفة للأدوية",
      maxLvl: 10,
      req: "نادي 1H المستوى 1",
      template: "يزيد من مقدار الصحة المستعادة عن طريق العناصر العلاجية عندما يتم تجهيز النادي+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Blow",
      maxLvl: 10,
      req: "نادي 1H المستوى 1",
      template: "بعد ضرب عدو باستخدام Switch، يتلقى اللاعب وفريقه تعزيزًا يقلل الضرر الذي يتلقونه لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الموقف الأساسي",
      maxLvl: 10,
      req: "نادي 1H المستوى 1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "ضربة قوية",
      maxLvl: 10,
      req: "نادي 1H المستوى 5",
      template: "يزيد الضرر الموجه للأعداء الضعيفين للهجمات الحادة+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان النادي",
      maxLvl: 10,
      req: "نادي 1H المستوى 5",
      template: "Increases club skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "علامة الدفاع",
      maxLvl: 10,
      req: "نادي 1H المستوى 10",
      template: "يستعيد الصحة كل +{val} ثانية.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تحسين التحكم في النادي",
      maxLvl: 10,
      req: "نادي 1H المستوى 10",
      template: "يقلل تكلفة النقاط الذهنية اللازمة للخطوة+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "غريزة المعركة",
      maxLvl: 10,
      req: "نادي 1H المستوى 15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "غريزة البقاء",
      maxLvl: 10,
      req: "1H كفاءة النادي - المستوى 15، علامة الدفاع - المستوى 1",
      template: "الحد الأقصى للصحة +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "كسر الدروع",
      maxLvl: 10,
      req: "نادي 1H المستوى 20",
      template: "كل هجوم لديه فرصة لتطبيق تأثير دفاعي على العدو المهاجم لمدة +{val} ثانية.",
      calc: (lvl) => [16, 17, 18, 19, 20, 21, 22, 23, 24, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "المعرفة بالأسلحة",
      maxLvl: 10,
      req: "نادي 1H المستوى 25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كسر السلاح",
      maxLvl: 10,
      req: "النادي 1H المستوى 30",
      template: "كل هجوم لديه فرصة لتطبيق تأثير معزز للهجوم على العدو المهاجم لمدة +{val} ثانية.",
      calc: (lvl) => [27, 29, 31, 33, 35, 37, 39, 41, 43, 45][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "سر النادي",
      maxLvl: 10,
      req: "نادي 1H المستوى 35",
      template: "يزيد الهجوم عندما يتم تجهيز الصولجان+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف",
      maxLvl: 10,
      req: "نادي 1H المستوى 40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الشحن الزائد I (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 50",
      template: "يزيد الهجوم عند استخدام عنصر النار+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "أكوا جلو (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 50",
      template: "يزيد الهجوم عند استخدام عنصر الماء+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الرياح (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 50",
      template: "يزيد الهجوم عند استخدام عنصر الرياح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الأرض (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 50",
      template: "يزيد الهجوم عند استخدام عنصر الأرض+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "شاين جلو (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 50",
      template: "يزيد الهجوم عند استخدام العنصر المقدس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الوهج الداكن (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 50",
      template: "يزيد الهجوم عند استخدام Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة البقاء (نادي 1H)",
      maxLvl: 10,
      req: "نادي 1H المستوى 55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الكفاءة الحادة (نادي 1H)",
      maxLvl: 10,
      req: "1H نادي Lv.60",
      template: "يزيد الضرر الموجه للأعداء الضعيفين للهجمات الحادة+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية (نادي 1H)",
      maxLvl: 10,
      req: "نادي 1H المستوى 65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ضربة منحوتة",
      maxLvl: 10,
      req: "نادي 1H المستوى 70",
      template: "يزيد الهجوم ضد الأعداء الذين تم تحسينهم بواسطة [[Mark Debuff",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "نسخة احتياطية قوية",
      maxLvl: 10,
      req: "نادي 1H المستوى 80",
      template: "عند ضرب عدو باستخدام Switch، يتم تعزيز أعضاء المجموعة من خلال زيادة ضرر ضعفهم الحاد+{val}",
      calc: (lvl) => lvl * 0.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الدفاع العالي",
      maxLvl: 10,
      req: "نادي 1H المستوى 85",
      template: "يزيد من الدفاع بينما يكون لدى اللاعب تعزيز نشط",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ارتفاع الرياح (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 90",
      template: "يزيد الهجوم عند استخدام عنصر الرياح+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "التشجيع",
      maxLvl: 10,
      req: "نادي 1H المستوى 95",
      template: "بعد ضرب عدو باستخدام Switch، يتلقى اللاعب وفريقه تعزيزًا يزيد من هجومهم لمدة +{val} ثانية.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "شحن الرياح (نادي الساعة الواحدة)",
      maxLvl: 10,
      req: "نادي 1H المستوى 100",
      template: "يزيد الضرر الناتج عن عنصر الرياح+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "ضرب محفورة",
      maxLvl: 10,
      req: "نادي 1H المستوى 105",
      template: "يزيد الهجوم ضد الأعداء الذين تم تحسينهم بواسطة [[Mark Debuff",
      calc: (lvl) => lvl * 20,
      bonusType: "atk_percent",
      active: true,
    },
  ],
  Dagger: [
    {
      name: "تدريب الخناجر",
      maxLvl: 10,
      req: "خنجر المستوى 1",
      template: "يزيد من الهجوم المنتظم عندما يتم تجهيز الخنجر+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الانتقام",
      maxLvl: 10,
      req: "خنجر المستوى 1",
      template: "يزيد الهجوم عندما تكون الصحة أقل من +{val}%",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "ضربة الخنجر",
      maxLvl: 10,
      req: "خنجر المستوى 1",
      template: "Increases damage dealt to an enemy which isn't focused on the player",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الموقف الأساسي",
      maxLvl: 10,
      req: "خنجر المستوى 1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "شفرة قاسية",
      maxLvl: 10,
      req: "خنجر المستوى 5",
      template: "يزيد الهجوم على الأعداء الذين يعانون من مرض الحالة عندما يتم تجهيز الخنجر+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان الخنجر",
      maxLvl: 10,
      req: "خنجر المستوى 5",
      template: "Increases dagger skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إثبات اللص",
      maxLvl: 10,
      req: "خنجر المستوى 10",
      template: "بعد ضرب عدو باستخدام Switch، تسممه لمدة +{val} ثانية (1 كومة)",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تحسين التحكم في الخناجر",
      maxLvl: 10,
      req: "خنجر المستوى 10",
      template: "يقلل تكلفة النقاط الذهنية اللازمة للخطوة+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "غريزة المعركة",
      maxLvl: 10,
      req: "خنجر المستوى 15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "غريزة البقاء",
      maxLvl: 10,
      req: "مهارة الخناجر 1H - المستوى 15، إثبات اللص - المستوى 1",
      template: "الحد الأقصى للصحة +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "التهرب",
      maxLvl: 10,
      req: "خنجر Lv.20",
      template: "تزيد فرصة تفادي أي هجوم (باستثناء الهجمات المركزة) عندما يكون لدى اللاعب أقل من +{val}% من الحد الأقصى من الصحة.",
      calc: (lvl) => lvl * 2,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "المعرفة بالأسلحة",
      maxLvl: 10,
      req: "خنجر المستوى 25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Executer's Eyes",
      maxLvl: 10,
      req: "خنجر المستوى 30",
      template: "كل هجوم لديه فرصة لجعل العدو يتلقى المزيد من الضرر مع الضربة التالية التي يتم توجيهها خلال الثواني +{val} التالية.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dagger's Secret",
      maxLvl: 10,
      req: "خنجر المستوى 35",
      template: "يزيد الهجوم عند تجهيز الخنجر+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف",
      maxLvl: 10,
      req: "خنجر المستوى 40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "فاحش أنا (خنجر)",
      maxLvl: 10,
      req: "خنجر المستوى 45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب (الخنجر)",
      maxLvl: 10,
      req: "خنجر Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر النار+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "أكوا جلو (خنجر)",
      maxLvl: 10,
      req: "خنجر Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الماء+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الريح (خنجر)",
      maxLvl: 10,
      req: "خنجر Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الرياح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الأرض (خنجر)",
      maxLvl: 10,
      req: "خنجر Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الأرض+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "تألق وهج (خنجر)",
      maxLvl: 10,
      req: "خنجر Lv.50",
      template: "يزيد الهجوم عند استخدام العنصر المقدس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الوهج الداكن (الخنجر)",
      maxLvl: 10,
      req: "خنجر Lv.50",
      template: "يزيد الهجوم عند استخدام Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة البقاء (الخنجر)",
      maxLvl: 10,
      req: "خنجر Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "مهارة القطع (الخنجر)",
      maxLvl: 10,
      req: "خنجر Lv.60",
      template: "يزيد الضرر الموجه للأعداء الضعيف لقطع الهجمات+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية (خنجر)",
      maxLvl: 10,
      req: "خنجر Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "متابعة الإضراب",
      maxLvl: 10,
      req: "خنجر المستوى 70",
      template: "يزيد الهجوم ضد الأعداء المصابين بـ [[التسمم (مهارة تسبب مرض الحالة)",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس (الخنجر)",
      maxLvl: 10,
      req: "خنجر المستوى 75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "فلاش حاد",
      maxLvl: 10,
      req: "خنجر المستوى 80",
      template: "يزيد الهجوم ضد الأعداء المصابين بـ [[التسمم (مهارة تسبب مرض الحالة)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "مكافأة حالة المرض",
      maxLvl: 10,
      req: "خنجر Lv.85",
      template: "يزيد الهجوم ضد الأعداء المتأثرين بأي حالة مرضية",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "صعود الظلام (خنجر)",
      maxLvl: 10,
      req: "خنجر Lv.90",
      template: "يزيد الهجوم عند استخدام Dark element+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "ضربة مصقولة",
      maxLvl: 10,
      req: "خنجر Lv.95",
      template: "يزيد الهجوم ضد الأعداء المصابين بـ [[التسمم (مهارة تسبب مرض الحالة)",
      calc: (lvl) => lvl * 0.01,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الشحنة المظلمة (الخنجر)",
      maxLvl: 10,
      req: "خنجر المستوى 100",
      template: "يزيد الضرر الناتج عن العنصر الداكن+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الاعتداء الدموي",
      maxLvl: 10,
      req: "خنجر Lv.105",
      template: "Increases player's Attack when attacking enemies afflicted with [[Bleed (skill inflicting status ailment)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
  ],
  Axe: [
    {
      name: "تدريب الفأس",
      maxLvl: 10,
      req: "2H الفأس Lv.1",
      template: "يزيد من الهجوم المنتظم عندما يتم تجهيز الفأس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Body's Enhancement",
      maxLvl: 10,
      req: "2H الفأس Lv.1",
      template: "يزيد الهجوم عندما يتم تجهيز الفأس+{val}",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Axe's Blow",
      maxLvl: 10,
      req: "2H الفأس Lv.1",
      template: "بعد ضرب عدو باستخدام Switch، يتم تحسين اللاعب مما يجعله يتلقى ضررًا أقل لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 2.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الموقف الأساسي",
      maxLvl: 10,
      req: "2H الفأس Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الروح القتالية",
      maxLvl: 10,
      req: "2H الفأس Lv.5",
      template: "زيادة معدل تعبئة مقياس التبديل+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "إتقان الفأس",
      maxLvl: 10,
      req: "2H الفأس Lv.5",
      template: "Increases axe skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "علامة المرتزقة",
      maxLvl: 10,
      req: "2H الفأس Lv.10",
      template: "يقلل تكلفة النقاط الذهنية لجميع سجلات مهارات الفأس+{val}",
      calc: (lvl) => lvl * 15,
      bonusType: "sp",
      active: true,
    },
    {
      name: "تحسين التحكم بالفأس",
      maxLvl: 10,
      req: "2H الفأس Lv.10",
      template: "يقلل تكلفة النقاط الذهنية اللازمة للخطوة+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "غريزة المعركة",
      maxLvl: 10,
      req: "2H الفأس Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "غريزة البقاء",
      maxLvl: 10,
      req: "كفاءة الفأس 2H - المستوى 15، علامة المرتزقة - المستوى 1",
      template: "الحد الأقصى للصحة +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "انشق",
      maxLvl: 10,
      req: "2H الفأس Lv.20",
      template: "يزيد الهجوم ضد العدو بأكثر من +{val}% من الحد الأقصى لصحته.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "المعرفة بالأسلحة",
      maxLvl: 10,
      req: "2H الفأس Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كونغو",
      maxLvl: 10,
      req: "2H الفأس Lv.30",
      template: "Decreases damage taken if it's more than +{val}% of character's max HP.",
      calc: (lvl) => [30, 35, 40, 45, 50, 55, 60, 65, 70, 75][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "سر الفأس",
      maxLvl: 10,
      req: "2H الفأس Lv.35",
      template: "يزيد الهجوم عندما يتم تجهيز الفأس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف",
      maxLvl: 10,
      req: "2H الفأس Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الشحن الزائد I (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر النار+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج مائي (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الماء+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الرياح (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الرياح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الأرض (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الأرض+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج لامع (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.50",
      template: "يزيد الهجوم عند استخدام العنصر المقدس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الوهج الداكن (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.50",
      template: "يزيد الهجوم عند استخدام Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة البقاء (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الكفاءة الحادة (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.60",
      template: "يزيد الضرر الموجه للأعداء الضعيفين للهجمات الحادة+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "قوة قوية",
      maxLvl: 10,
      req: "2H الفأس Lv.70",
      template: "يزيد الهجوم بما يتناسب مع الصحة+{val} المتبقية",
      calc: (lvl) =>
        [210, 220, 230, 240, 250, 260, 270, 280, 290, 300][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تعزيز الانعكاس",
      maxLvl: 10,
      req: "2H الفأس Lv.80",
      template: "When receiving a hit, there's a chance to obtain a buff which increases Attack+{val}",
      calc: (lvl) =>
        [15.5, 16, 16.5, 17, 17.5, 18, 18.5, 19, 19.5, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الاعتداء الديناميكي",
      maxLvl: 10,
      req: "2H الفأس Lv.85",
      template: "يزيد اللاعب\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) => lvl * 0.25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "صعود الأرض (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.90",
      template: "يزيد الهجوم عند استخدام عنصر الأرض+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف الفردي (فأس ساعتين)",
      maxLvl: 10,
      req: "2H الفأس Lv.95",
      template: "تزيد قوة مهارات السيف الفردية بنسبة +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "شحنة الأرض (فأس 2H)",
      maxLvl: 10,
      req: "2H الفأس Lv.100",
      template: "يزيد الضرر الناتج عن عنصر الأرض+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "هجوم قوي",
      maxLvl: 10,
      req: "2H الفأس Lv.105",
      template: "Increases player's Attack proportionally to the percentage of remaining HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "فاحش I",
      maxLvl: 1,
      req: "إتقان الفأس لمدة ساعتين - المستوى 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة البقاء على قيد الحياة",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 55، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية",
      maxLvl: 10,
      req: "كفاءة الفأس 2H - المستوى 65، خبرة البقاء على قيد الحياة (فأس 2H) - المستوى 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس",
      maxLvl: 10,
      req: "كفاءة الفأس 2H - المستوى 75، الخبرة الدفاعية القوية (فأس 2H) - المستوى 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "صعود الأرض",
      maxLvl: 10,
      req: "كفاءة الفأس 2H - المستوى 90، الهجوم الديناميكي - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الأرض. + {فال}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تهمة الأرض",
      maxLvl: 10,
      req: "إتقان الفأس 2H - المستوى 100، إتقان مهارة السيف الفردي (فأس 2H) - المستوى 5",
      template: "يزيد من الضرر الذي يتعرض له عنصر الأرض. + {فال}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "إتقان مهارة السيف الواحد",
      maxLvl: 10,
      req: "كفاءة الفأس 2H - المستوى 95، الهجوم الديناميكي - المستوى 5",
      template: "تزيد قوة مهارات السيف الفردية بنسبة +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 50، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر النار. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "أكوا توهج",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 50، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الماء. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الرياح",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 50، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الرياح. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الأرض",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 50، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الأرض. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تألق توهج",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 50، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر المقدس. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الوهج الداكن",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 50، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر الداكن. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تطوير تقنية السيف",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 50، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "تزيد قوة مهارات السيف بنسبة +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كسر الأساسيات",
      maxLvl: 10,
      req: "إتقان الفأس ساعتين - المستوى 50، إتقان مهارة السيف (الفأس ثنائي الساعة) - المستوى 5",
      template: "تزيد قيمة الكسر لمهارات السيف بمقدار +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "هجوم سلسلة المستعبدين",
      maxLvl: 10,
      req: "كفاءة الفأس ساعتين - المستوى 110، الهجوم القوي - المستوى 5",
      template: "تزيد قوة مهارات السيف المستخدمة في Switch بنسبة +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Spear: [
    {
      name: "تدريب الرمح",
      maxLvl: 10,
      req: "2H الرمح Lv.1",
      template: "يزيد من الهجوم المنتظم عندما يتم تجهيز الرمح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "التدافع",
      maxLvl: 10,
      req: "2H الرمح Lv.1",
      template: "يزيد الهجوم لمدة +{val} ثانية بعد الخطو، عندما يتم تجهيز الرمح.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Spear's Blow",
      maxLvl: 10,
      req: "2H الرمح Lv.1",
      template: "بعد ضرب عدو باستخدام Switch، يتم تحسين اللاعب مما يزيد من معدله الحرج لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الموقف الأساسي",
      maxLvl: 10,
      req: "2H الرمح Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "عاصفة",
      maxLvl: 10,
      req: "2H الرمح Lv.5",
      template: "يعمل على تقليل وقت التهدئة لسجلات Spear Skill Records+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "مهارة الرمح",
      maxLvl: 10,
      req: "2H الرمح Lv.5",
      template: "Increases spear skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "علامة الفارس",
      maxLvl: 10,
      req: "2H الرمح Lv.10",
      template: "يستعيد النقاط الذهنية لكل عدو يُهزم+{val}",
      calc: (lvl) => lvl * 3,
      bonusType: "sp",
      active: true,
    },
    {
      name: "تحسين التحكم في الرمح",
      maxLvl: 10,
      req: "2H الرمح Lv.10",
      template: "يقلل تكلفة النقاط الذهنية اللازمة للخطوة+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "غريزة المعركة",
      maxLvl: 10,
      req: "2H الرمح Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "غريزة البقاء",
      maxLvl: 10,
      req: "كفاءة الرمح لمدة ساعتين - المستوى 15، علامة الفارس - المستوى 1",
      template: "الحد الأقصى للصحة +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "فانغ",
      maxLvl: 10,
      req: "2H الرمح Lv.20",
      template: "يزيد الهجوم على الأعداء الذين يعانون من مرض الحالة عندما يتم تجهيز الرمح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "المعرفة بالأسلحة",
      maxLvl: 10,
      req: "2H الرمح Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "رقصة الرمح",
      maxLvl: 10,
      req: "2H الرمح Lv.30",
      template: "الوصف معلق (كعب ويكي)",
      calc: (lvl) => 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "سر الرمح",
      maxLvl: 10,
      req: "2H الرمح Lv.35",
      template: "يزيد الهجوم عند تجهيز الرمح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف",
      maxLvl: 10,
      req: "2H الرمح Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الشحن الزائد I (الرمح 2H)",
      maxLvl: 10,
      req: "2H الرمح Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب (الرمح 2H)",
      maxLvl: 10,
      req: "رمح 2H Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر النار+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "أكوا جلو (رمح 2H)",
      maxLvl: 10,
      req: "رمح 2H Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الماء+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الرياح (الرمح 2H)",
      maxLvl: 10,
      req: "رمح 2H Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الرياح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الأرض (الرمح 2H)",
      maxLvl: 10,
      req: "رمح 2H Lv.50",
      template: "يزيد الهجوم عند استخدام عنصر الأرض+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج لامع (رمح 2H)",
      maxLvl: 10,
      req: "رمح 2H Lv.50",
      template: "يزيد الهجوم عند استخدام العنصر المقدس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الوهج الداكن (الرمح 2H)",
      maxLvl: 10,
      req: "رمح 2H Lv.50",
      template: "يزيد الهجوم عند استخدام Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة البقاء (الرمح الثاني)",
      maxLvl: 10,
      req: "2H الرمح Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كفاءة الدفع (الرمح 2H)",
      maxLvl: 10,
      req: "2H الرمح Lv.60",
      template: "يزيد الضرر الموجه للأعداء الضعفاء في توجيه الهجمات+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية (رمح ساعتين)",
      maxLvl: 10,
      req: "2H الرمح Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تبديل العلامات",
      maxLvl: 10,
      req: "2H الرمح Lv.70",
      template: "عند ضرب عدو باستخدام Switch، لديه فرصة لإلحاق الضرر بالعدو باستخدام [[Stigma Debuff]] لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس (الرمح لساعتين)",
      maxLvl: 10,
      req: "2H الرمح Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "السعي وراء الضعفاء",
      maxLvl: 10,
      req: "2H الرمح Lv.80",
      template: "يزيد الهجوم ضد الأعداء الذين تم خداعهم+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف بشكل عام (الرمح لمدة ساعتين)",
      maxLvl: 10,
      req: "2H الرمح Lv.85",
      template: "تزيد من قوة مهارات السيف في الفتحات النشطة بالإضافة إلى تلك التي تعد جزءًا من Connect Chain بنسبة +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ارتفاع الريح (الرمح 2H)",
      maxLvl: 10,
      req: "2H الرمح Lv.90",
      template: "يزيد الهجوم عند استخدام عنصر الرياح+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "فن التدمير",
      maxLvl: 10,
      req: "2H الرمح Lv.95",
      template: "زيادة كفاءة الكسر+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "شحنة الرياح (الرمح 2H)",
      maxLvl: 10,
      req: "رمح 2H Lv.100",
      template: "يزيد الضرر الناتج عن عنصر الرياح+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "تبديل اضمحلال الدروع",
      maxLvl: 10,
      req: "2H الرمح Lv.105",
      template: "عند ضرب عدو باستخدام Switch، لديه فرصة لإلحاق الضرر بالعدو باستخدام [[Armor Decay Debuff]] لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "فاحش I",
      maxLvl: 1,
      req: "كفاءة الرمح لمدة ساعتين - المستوى 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة البقاء على قيد الحياة",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 55، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية",
      maxLvl: 10,
      req: "كفاءة الرمح لساعتين - المستوى 65، خبرة البقاء (الرمح لساعتين) - المستوى 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 75، الخبرة الدفاعية القوية (الرمح ساعتين) - المستوى 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ارتفاع الرياح",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 90، إتقان مهارة السيف بشكل عام (الرمح ساعتين) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الرياح. + {فال}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تهمة الرياح",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 100، فن التدمير - المستوى 5",
      template: "يزيد الضرر الناتج عن عنصر الرياح. + {فال}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "إتقان مهارة السيف بشكل عام",
      maxLvl: 10,
      req: "كفاءة الرمح - المستوى 85، خبرة الهجوم الشرس (الرمح الثاني) - المستوى 5",
      template: "تزيد من قوة مهارات السيف في الفتحات النشطة بالإضافة إلى تلك التي تعد جزءًا من Connect Chain بنسبة +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 50، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر النار. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "أكوا توهج",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 50، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الماء. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الرياح",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 50، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الرياح. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الأرض",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 50، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الأرض. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تألق توهج",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 50، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر المقدس. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الوهج الداكن",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 50، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر الداكن. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تطوير تقنية السيف",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 50، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "تزيد قوة مهارات السيف بنسبة +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كسر الأساسيات",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 50، إتقان مهارة السيف (الرمح ساعتين) - المستوى 5",
      template: "تزيد قيمة الكسر لمهارات السيف بمقدار +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "هجوم سلسلة المستعبدين",
      maxLvl: 10,
      req: "كفاءة الرمح ساعتين - المستوى 110، مفتاح اضمحلال الدرع - المستوى 1",
      template: "تزيد قوة مهارات السيف المستخدمة في Switch بنسبة +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Bow: [
    {
      name: "تدريب القوس",
      maxLvl: 10,
      req: "القوس المستوى 1",
      template: "يزيد من الهجوم المنتظم عندما يكون القوس مجهزًا+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "بيرس",
      maxLvl: 10,
      req: "القوس المستوى 1",
      template: "يزيد الهجوم عندما تكون الصحة أعلى من +{val}%",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "فلاش",
      maxLvl: 10,
      req: "القوس المستوى 1",
      template: "بعد ضرب عدو باستخدام Switch، يتم تحسين اللاعب مما يزيد من معدله الحرج لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الموقف الأساسي",
      maxLvl: 10,
      req: "القوس المستوى 1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "لقطة دقيقة",
      maxLvl: 10,
      req: "القوس المستوى 5",
      template: "يزيد الضرر الموجه للأعداء الضعفاء في توجيه الهجمات+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "مهارة القوس",
      maxLvl: 10,
      req: "القوس المستوى 5",
      template: "Increases bow skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إثبات آرتشر",
      maxLvl: 10,
      req: "القوس المستوى 10",
      template: "يقلل الوقت اللازم لشحن بعض سجلات مهارات القوس+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تحسين التحكم في القوس",
      maxLvl: 10,
      req: "القوس المستوى 10",
      template: "يقلل تكلفة النقاط الذهنية اللازمة للخطوة+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "غريزة المعركة",
      maxLvl: 10,
      req: "القوس المستوى 15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "غريزة البقاء",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 15، إثبات رامي السهام - المستوى 1",
      template: "الحد الأقصى للصحة +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "عين المفترس الحريصة",
      maxLvl: 10,
      req: "القوس المستوى 20",
      template: "يزيد الهجوم ضد العدو بأقل من +{val}% من الحد الأقصى لصحته.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "المعرفة بالأسلحة",
      maxLvl: 10,
      req: "القوس المستوى 25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "هلال القمر",
      maxLvl: 10,
      req: "القوس المستوى 30",
      template: "بعد ضرب عدو بمهارة القوس على Switch، يتم تنشيط التعزيز الذي يؤدي لمدة +{val} ثانية (أو حتى يتلقى اللاعب الضرر) إلى زيادة الهجوم بنسبة +{val}%.",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "سر القوس",
      maxLvl: 10,
      req: "القوس المستوى 35",
      template: "يزيد الهجوم عندما يتم تجهيز القوس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف",
      maxLvl: 10,
      req: "القوس المستوى 40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الشحن الزائد I (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 50",
      template: "يزيد الهجوم عند استخدام عنصر النار+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "أكوا جلو (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 50",
      template: "يزيد الهجوم عند استخدام عنصر الماء+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الرياح (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 50",
      template: "يزيد الهجوم عند استخدام عنصر الرياح+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "توهج الأرض (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 50",
      template: "يزيد الهجوم عند استخدام عنصر الأرض+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "تألق وهج (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 50",
      template: "يزيد الهجوم عند استخدام العنصر المقدس+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الوهج الداكن (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 50",
      template: "يزيد الهجوم عند استخدام Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة البقاء (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كفاءة الدفع (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 60",
      template: "يزيد الضرر الموجه للأعداء الضعفاء في توجيه الهجمات+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ضربة مفاجئة",
      maxLvl: 10,
      req: "القوس المستوى 70",
      template: "يزيد الهجوم ضد الأعداء الذين لا يستهدفون اللاعب+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "استراحة صعبة (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 80",
      template: "يزيد اللاعب\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الضربة العكسية",
      maxLvl: 10,
      req: "القوس المستوى 85",
      template: "يزيد الهجوم بناءً على نسبة الصحة المتبقية",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "تألق الارتفاع (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 90",
      template: "يزيد الهجوم عند استخدام العنصر المقدس+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "إتقان مهارة السيف الواحد (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 95",
      template: "تزيد قوة مهارات السيف الفردية بنسبة +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تألق تهمة (القوس)",
      maxLvl: 10,
      req: "القوس المستوى 100",
      template: "يزيد الضرر الناتج عن العنصر المقدس+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "الاعتداء العكسي",
      maxLvl: 10,
      req: "القوس المستوى 105",
      template: "Increases player's Attack proportionally to the percentage of lost HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "فاحش I",
      maxLvl: 1,
      req: "مهارة القوس - المستوى 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة البقاء على قيد الحياة",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 55، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة دفاعية قوية",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 65، خبرة البقاء (القوس) - المستوى 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة الهجوم الشرس",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 75، الخبرة الدفاعية القوية (القوس) - المستوى 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "استراحة صعبة",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 80، خبرة الهجوم الشرس (القوس) - المستوى 5",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تألق الارتفاع",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 90، الضربة العكسية - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر المقدس. + {فال}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تألق تهمة",
      maxLvl: 10,
      req: "إتقان القوس - المستوى 100، إتقان مهارة السيف الواحد (القوس) - المستوى 5",
      template: "يزيد الضرر الناتج عن العنصر المقدس. + {فال}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "إتقان مهارة السيف الواحد",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 95، الضربة العكسية - المستوى 5",
      template: "تزيد قوة مهارات السيف الفردية بنسبة +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج اللهب",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 50، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر النار. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "أكوا توهج",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 50، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الماء. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الرياح",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 50، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الرياح. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "توهج الأرض",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 50، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "يزيد الهجوم عند استخدام عنصر الأرض. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تألق توهج",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 50، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر المقدس. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الوهج الداكن",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 50، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "يزيد الهجوم عند استخدام العنصر الداكن. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تطوير تقنية السيف",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 50، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "تزيد قوة مهارات السيف بنسبة +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "كسر الأساسيات",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 50، إتقان مهارة السيف (القوس) - المستوى 5",
      template: "تزيد قيمة الكسر لمهارات السيف بمقدار +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "هجوم سلسلة المستعبدين",
      maxLvl: 10,
      req: "كفاءة القوس - المستوى 110، الهجوم العكسي - المستوى 5",
      template: "تزيد قوة مهارات السيف المستخدمة في Switch بنسبة +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Shield: [
    {
      name: "تدريب الدرع",
      maxLvl: 10,
      req: "الدرع المستوى 1",
      template: "يزيد الدفاع عند تجهيز الدرع+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "مقاومة",
      maxLvl: 10,
      req: "الدرع المستوى 1",
      template: "زيادة المقاومة ضد أمراض الحالة الضارة عند تجهيز الدرع+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "حماية",
      maxLvl: 10,
      req: "الدرع المستوى 1",
      template: "بعد ضرب عدو باستخدام Switch، يتم تعزيز اللاعب مما يزيد من دفاعه لمدة +{val} ثانية.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "الحرس الحاسم",
      maxLvl: 10,
      req: "الدرع المستوى 5",
      template: "يقلل الضرر الناتج بنسبة مئوية تعتمد على عدد سجلات مهارات الدرع المجهزة+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "انعكاس",
      maxLvl: 10,
      req: "الدرع المستوى 10",
      template: "يعكس جزءًا من الضرر الذي تم إرجاعه إلى العدو+{val}",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "غريزة البقاء",
      maxLvl: 10,
      req: "كفاءة الدرع - المستوى 15، الانعكاس - المستوى 1",
      template: "الحد الأقصى للصحة +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "حيوية",
      maxLvl: 10,
      req: "الدرع المستوى 20",
      template: "يزيد من مقاومة الانزلاق عند تجهيز الدرع+{val}",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "المعرفة الدرع",
      maxLvl: 10,
      req: "الدرع المستوى 25",
      template: "Passively increases the player's Defense+{val}",
      calc: (lvl) =>
        [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "متعال",
      maxLvl: 10,
      req: "الدرع المستوى 30",
      template: "يزيد الضرر الناتج عن سجلات مهارة الدرع+{val}",
      calc: (lvl) => [30, 35, 40, 45, 50][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "شفاء الدرع",
      maxLvl: 10,
      req: "الدرع المستوى 55",
      template: "يستعيد قدرًا معينًا من الصحة كل +{val} ثانية.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "خبرة الاسترداد",
      maxLvl: 10,
      req: "الدرع المستوى 60",
      template: "يزيد بشكل سلبي من فعالية عناصر الشفاء+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "تعزيز الجسم (الدرع)",
      maxLvl: 10,
      req: "الدرع المستوى 65",
      template: "ماكس HP + {val}",
      calc: (lvl) => lvl * 50,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "الشفاء الميداني",
      maxLvl: 10,
      req: "الدرع المستوى 70",
      template: "يزيد بشكل سلبي من فعالية النباتات العلاجية+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ضربة قوية",
      maxLvl: 10,
      req: "الدرع المستوى 75",
      template: "يزيد الضرر ضد الأعداء الضعفاء إلى غير حادين+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "التشجيع الجسدي (الدرع)",
      maxLvl: 10,
      req: "الدرع المستوى 80",
      template: "Passively increases player's HP+{val}",
      calc: (lvl) =>
        [525, 550, 575, 600, 625, 650, 675, 700, 725, 750][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "قطع قوية",
      maxLvl: 10,
      req: "الدرع المستوى 85",
      template: "يزيد الضرر ضد الأعداء الضعيفين لقطع + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    ,
    {
      name: "التشجيع الجسدي",
      maxLvl: 10,
      req: "كفاءة الدرع - المستوى 80، الضربة القوية - المستوى 5",
      template: "Passively increases player's HP. +{val}",
      calc: (lvl) => 500 + lvl * 25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "التوجه القوي",
      maxLvl: 10,
      req: "كفاءة الدرع - المستوى 90، الضربة القوية - المستوى 5",
      template: "يزيد الضرر ضد الأعداء الضعفاء للتوجه. + {فال}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
  ],
};
