window.masteryData = {
  Sword: [
    {
      name: "검 훈련",
      maxLvl: 10,
      req: "상반기 검 Lv.1",
      template: "When 1h Sword is equipped, normal attack's damage +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "기사도",
      maxLvl: 10,
      req: "상반기 검 Lv.1",
      template: "검 장착 시 공격력, 방어력이 +{val}만큼 증가합니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "flat_atk_def",
      active: true,
    },
    {
      name: "Sword's Blow",
      maxLvl: 10,
      req: "상반기 검 Lv.1",
      template: "After hitting an enemy with Switch, buffs the player's Attack and Defense for 8 seconds by +{val}%",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 자세",
      maxLvl: 10,
      req: "상반기 검 Lv.1",
      template: "공격 시 적에게 +{val}의 추가 피해를 추가합니다(모든 무기).",
      calc: (lvl) => lvl * 5,
      bonusType: "flat_damage",
      active: true,
    },
    {
      name: "풀 스트라이크",
      maxLvl: 10,
      req: "검술수련 Lv.5",
      template: "상반기 소드 장착 시, 베기에 약한 적에게 주는 데미지 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "검술 숙련도",
      maxLvl: 10,
      req: "검술 Lv.5, 풀스트라이크 Lv.5",
      template: "상반기 소드 장착 시 소드 스킬 파워 +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "전사의 표식",
      maxLvl: 1,
      req: "상반기 소드 Lv.10, 풀스트라이크 Lv.5",
      template: "상반기 검 장착 시 처치 시 HP +{val}% 회복",
      calc: (lvl) => lvl * 2,
      bonusType: "healing_percent",
      active: true,
    },
    {
      name: "검 제어 개선",
      maxLvl: 1,
      req: "상반기 검 Lv.10, 기본 스탠스 Lv.5",
      template: "1H 소드 장착 시, 걷기에 필요한 SP 소모량 -{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "step_reduction",
      active: true,
    },
    {
      name: "전투 본능",
      maxLvl: 10,
      req: "상반기 검 Lv.10, 기본 스탠스 Lv.5",
      template: "공격 +{val} (모든 무기)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "생존 본능",
      maxLvl: 10,
      req: "상반기 검 Lv.15, 전사의 증표 Lv.1",
      template: "최대 HP +{val}% (모든 무기)",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "조합",
      maxLvl: 10,
      req: "상반기 검 Lv.20, 생존 본능 Lv.5",
      template: "상반기 소드 장착 시 스위치 데미지 +{val}%",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "무기 지식",
      maxLvl: 10,
      req: "상반기 검 Lv.25, 조합 Lv.5",
      template: "공격력 +{val}%(모든 무기)",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.699999999999999, 5][
          lvl - 1
        ] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "스위치 충전",
      maxLvl: 10,
      req: "상반기 검 Lv.30, 무기 지식 Lv.5",
      template: "1H 소드 장착 시, 스위치 스킬 사용 시 +{val} SP 회복",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "sp_recovery_flat",
      active: true,
    },
    {
      name: "Sword's Secret",
      maxLvl: 10,
      req: "상반기 소드 Lv.35, 스위치 차지 Lv.1",
      template: "상반기 소드 장착 시 공격력 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "소드 스킬 마스터리",
      maxLvl: 10,
      req: "상반기 검 Lv.40, 무기 지식 Lv.10",
      template: "소드 스킬 파워 +{val}% (모든 무기에 유효)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "ss_power",
      active: true,
    },
    {
      name: "과충전 I (1H 검)",
      maxLvl: 10,
      req: "상반기 검 Lv.45",
      template: "1H 소드 장착 시 스위치 게이지가 3레벨까지 충전됩니다. 3레벨 스위치 사용 시 데미지가 200% 증가합니다.",
      calc: (lvl) => 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "화염 글로우(1H 검)",
      maxLvl: 10,
      req: "상반기 소드 Lv.50, 소드 스킬 마스터리 Lv.5",
      template: "화속성 공격 및 반성검 장착 시 공격력 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "아쿠아 글로우(1H 소드)",
      maxLvl: 10,
      req: "상반기 소드 Lv.50, 소드 스킬 마스터리 Lv.5",
      template: "한손검 장착 시 수속성 공격 시 공격력 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "바람의 빛(1H 검)",
      maxLvl: 10,
      req: "상반기 소드 Lv.50, 소드 스킬 마스터리 Lv.5",
      template: "풍속성 공격 및 반성검 장착 시 공격력 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "대지의 빛(1H 검)",
      maxLvl: 10,
      req: "상반기 소드 Lv.50, 소드 스킬 마스터리 Lv.5",
      template: "대지속성 공격 및 반성검 장착 시 공격력 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "샤인 글로우(1H 소드)",
      maxLvl: 10,
      req: "상반기 소드 Lv.50, 소드 스킬 마스터리 Lv.5",
      template: "성속성 공격 및 반성검 장착 시 공격력 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "다크 글로우(1H 검)",
      maxLvl: 10,
      req: "상반기 소드 Lv.50, 소드 스킬 마스터리 Lv.5",
      template: "어둠속성 공격 및 반성검 장착 시 공격력 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "생존 숙련도(상반기 검)",
      maxLvl: 10,
      req: "상반기 소드 Lv.55, 소드 스킬 마스터리 Lv.5",
      template: "1H 소드 장착 시 HP +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "슬래시 숙련도(상반검)",
      maxLvl: 10,
      req: "상반기 검 Lv.60, 생존 숙련도(상반 검) Lv.5",
      template: "상반기 소드 장착 시, 베기에 약한 적에게 주는 데미지 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "강력한 방어 전문성(상반기 검)",
      maxLvl: 10,
      req: "상반기 검 Lv.65, 생존 숙련도(상반 검) Lv.5",
      template: "1H 검 장착 시 방어력 +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "def_flat",
      active: true,
    },
    {
      name: "화상 가드",
      maxLvl: 10,
      req: "상반신 검 Lv.70, 강력한 방어 숙련도(하반신 검) Lv.5",
      template: "상반기 소드 장착 시 화상 데미지 -{val}",
      calc: (lvl) =>
        [-4.5, -4, -3.5, -3, -2.5, -2, -1.5, -1, -0.5, 0][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "맹렬한 공격 전문성(상반검)",
      maxLvl: 10,
      req: "상반신 검 Lv.75, 강력한 방어 숙련도(하반신 검) Lv.5",
      template: "상반기 검 장착 시 공격력 +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "하드 브레이크(1H 검)",
      maxLvl: 10,
      req: "전반검 Lv.80, 맹렬한 공격 숙련도(상반검) Lv.5",
      template: "1H 소드 장착 시, 브레이크 사용 시 공격력 +{val}",
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "싱글 소드 스킬 마스터리(1H 소드)",
      maxLvl: 10,
      req: "상반기 검 Lv.85, 맹렬한 공격 숙련도(상승 검) Lv.5",
      template: "상반기 소드 장착 시 소드 스킬 파워(단일) +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "skill_power",
      active: true,
    },
    {
      name: "화염 상승(1H 검)",
      maxLvl: 10,
      req: "상반기 검 Lv.90, 맹렬한 공격 숙련도(상승 검) Lv.5",
      template: "1H 소드 장착 시, 화속성 사용 시 공격력 +{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "검술 숙련도(상반검)",
      maxLvl: 10,
      req: "상반기 소드 Lv.95,단검 스킬 마스터리(한성 소드) Lv.5",
      template: "소드 스킬 데미지 +{val}% (모든 무기에 유효)",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "화염 돌진(1H 검)",
      maxLvl: 10,
      req: "상반기 소드 Lv.100,소드 스킬 숙련도(상스 소드) Lv.5",
      template: "상반기 소드 장착 시, 화속성 대미지 +{val}%",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "damage_percent_fire",
      active: true,
    },
    {
      name: "역경의 수호자",
      maxLvl: 10,
      req: "한손 검 Lv.105,화염 충전(1H 검) Lv.5",
      template: "상반기 검 장착 시 방어력 +{val}, HP가 25% 이하일 때",
      calc: (lvl) => lvl * 10,
      bonusType: "def_flat",
      active: true,
    },
    ,
    {
      name: "과충전 I",
      maxLvl: 1,
      req: "상반기 검 숙련도 - 레벨 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 전문성",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 55 , 검 스킬 마스터리(1H 검) - 레벨 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 국방 전문성",
      maxLvl: 10,
      req: "1H 검 숙련도 - 레벨 65 , 생존 전문성(1H 검) - 레벨 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "치열한 공격 전문성",
      maxLvl: 10,
      req: "1H 검 숙련 - 75레벨, 강력한 방어 전문성(1H 검) - 5레벨",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "싱글 소드 스킬 마스터리",
      maxLvl: 10,
      req: "1H 검 숙련도 - 85레벨, 맹렬한 공격 숙련도(1H 검) - 5레벨",
      template: "단일 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "소드 스킬 숙련도",
      maxLvl: 10,
      req: "1H 소드 숙련 - 95레벨, 싱글 소드 스킬 마스터리(1H 소드) - 5레벨",
      template: "소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "하드 브레이크",
      maxLvl: 10,
      req: "1H 검 숙련도 - 80레벨, 맹렬한 공격 숙련도(1H 검) - 5레벨",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "화염 상승",
      maxLvl: 10,
      req: "1H 소드 숙련 - 90레벨, 싱글 소드 스킬 마스터리(1H 소드) - 5레벨",
      template: "불속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "화염폭약",
      maxLvl: 10,
      req: "1H 소드 숙련도 - 100레벨 , 소드 스킬 숙련도(1H 소드) - 5레벨",
      template: "불속성 데미지가 증가합니다. +{발}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "불꽃 글로우",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 50 , 소드 스킬 마스터리(1H 검) - 레벨 5",
      template: "불속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "아쿠아 글로우",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 50 , 소드 스킬 마스터리(1H 검) - 레벨 5",
      template: "물속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "바람의 빛",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 50 , 소드 스킬 마스터리(1H 검) - 레벨 5",
      template: "바람 속성 사용 시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "지구 빛",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 50 , 소드 스킬 마스터리(1H 검) - 레벨 5",
      template: "땅속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "샤인 글로우",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 50 , 소드 스킬 마스터리(1H 검) - 레벨 5",
      template: "신성속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "다크 글로우",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 50 , 소드 스킬 마스터리(1H 검) - 레벨 5",
      template: "어둠속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "적용 스탠스",
      maxLvl: 10,
      req: "릴리스 크리스탈(M) x 1",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 125,
      bonusType: "passive",
      active: true,
    },
    {
      name: "발전된 자세",
      maxLvl: 10,
      req: "릴리스 크리스탈(L) x 3",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "고급 검 기술",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 50 , 소드 스킬 마스터리(1H 검) - 레벨 5",
      template: "소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 깨기",
      maxLvl: 10,
      req: "1H 검 숙련 - 레벨 50 , 소드 스킬 마스터리(1H 검) - 레벨 5",
      template: "소드 스킬의 브레이크 값이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "결합된 체인 공격",
      maxLvl: 10,
      req: "1H 검 숙련도 - 레벨 110 , 역경 가드 - 레벨 5",
      template: "Switch에서 사용되는 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Rapier: [
    {
      name: "레이피어 훈련",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.1",
      template: "1H 레이피어 장착 시 일반공격 데미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "연쇄 공격",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.1",
      template: "레이피어 장착 시 단일 콤보의 HIT 수에 따라 공격력 증가+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Rapier's Blow",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.1",
      template: "스위치를 사용하여 적을 공격한 후 플레이어는 +{val}초 동안 치명타 발생률을 증가시키는 버프를 받습니다.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 자세",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "타겟 약점",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.5",
      template: "찌르기 공격에 약한 적에게 주는 대미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "레이피어 숙련도",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.5",
      template: "Increases rapier skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "검객의 표식",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.10",
      template: "크리티컬 히트+{val} 시 SP 회복",
      calc: (lvl) => lvl * 2,
      bonusType: "sp",
      active: true,
    },
    {
      name: "레이피어 제어 개선",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.10",
      template: "걷기에 필요한 SP 소모량 감소+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "전투 본능",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 본능",
      maxLvl: 10,
      req: "상반기 레이피어 숙련도 - 15레벨, 검객의 증표 - 1레벨",
      template: "최대 HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "번개 속도",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.20",
      template: "플레이어가 레이피어 장착 시 크리티컬 데미지 증가+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "무기 지식",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "유성",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.30",
      template: "레이피어 장착 시, 밟은 후 +{val}초 동안 크리티컬 확률이 증가합니다.",
      calc: (lvl) => [20, 25, 30, 35, 40, 45, 50, 55, 60, 65][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rapier's Secret",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.35",
      template: "레이피어 장착시 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "소드 스킬 마스터리",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "과충전 I (1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "불꽃의 빛(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.50",
      template: "불속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "아쿠아 글로우(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.50",
      template: "수속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "바람의 빛(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.50",
      template: "바람속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "대지의 빛(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.50",
      template: "땅속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "샤인 글로우(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.50",
      template: "성속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "다크 글로우(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.50",
      template: "어둠속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "생존 전문성(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "추력 숙련도(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.60",
      template: "찌르기 공격에 약한 적에게 주는 대미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강력한 방어 전문성(상반기 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "바이탈 포인트 공격",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.70",
      template: "크리티컬 데미지 증가 버프 적용 중 공격력 증가+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "맹렬한 공격 전문성(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "바이탈 포인트 찌르기",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.80",
      template: "스킬+{val} 사용 시 크리티컬 데미지 증가",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "정밀한 타격",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.85",
      template: "스킬 사용 시 크리티컬 확률이 +{val}% 증가합니다.",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "아쿠아 라이즈 (1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.90",
      template: "수속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "정교한 일격",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.95",
      template: "스위치를 사용하여 적을 타격한 후 플레이어에게 버프를 적용하여 +{val}초 동안 치명타 피해를 증가시킵니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "아쿠아 차지(1H 레이피어)",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.100",
      template: "수속성+{val} 데미지 증가",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "취약점 공격",
      maxLvl: 10,
      req: "상반기 레이피어 Lv.105",
      template: "Increases player's Attack when Critical Rate buff is active+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "과충전 I",
      maxLvl: 1,
      req: "상반기 레이피어 숙련도 - 45레벨",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 전문성",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 55레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 국방 전문성",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 65레벨, 생존 전문성(1H 레이피어) - 5레벨",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "치열한 공격 전문성",
      maxLvl: 10,
      req: "상반기 레이피어 숙련도 - 75레벨, 강력한 방어 전문성(한시간 레이피어) - 레벨 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "아쿠아 라이즈",
      maxLvl: 10,
      req: "상반기 레이피어 숙련도 - 90레벨, 정밀 타격 - 레벨 5",
      template: "물속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "아쿠아 차지",
      maxLvl: 10,
      req: "상반기 레이피어 숙련도 - 100레벨, 정교한 일격 - 레벨 5",
      template: "물속성 데미지가 증가합니다. +{발}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "불꽃 글로우",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 50레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "불속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "아쿠아 글로우",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 50레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "물속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "바람의 빛",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 50레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "바람 속성 사용 시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "지구 빛",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 50레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "땅속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "샤인 글로우",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 50레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "신성속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "다크 글로우",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 50레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "어둠속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "고급 검 기술",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 50레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 깨기",
      maxLvl: 10,
      req: "1H 레이피어 숙련도 - 50레벨, 소드 스킬 마스터리(1H 레이피어) - 5레벨",
      template: "소드 스킬의 브레이크 값이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "결합된 체인 공격",
      maxLvl: 10,
      req: "상반기 레이피어 숙련도 - 110레벨, 취약 공격 - 레벨 5",
      template: "Switch에서 사용되는 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Club: [
    {
      name: "클럽 연수",
      maxLvl: 10,
      req: "상반기 클럽 Lv.1",
      template: "메이스 장착시 일반공격 데미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "의약품에 대한 지식",
      maxLvl: 10,
      req: "상반기 클럽 Lv.1",
      template: "클럽 착용 시 힐링 아이템으로 회복되는 HP 회복량 증가+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Blow",
      maxLvl: 10,
      req: "상반기 클럽 Lv.1",
      template: "스위치를 사용하여 적을 공격한 후 플레이어와 파티는 +{val}초 동안 받는 데미지를 감소시키는 버프를 받습니다.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "기본 자세",
      maxLvl: 10,
      req: "상반기 클럽 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강타",
      maxLvl: 10,
      req: "상반기 클럽 Lv.5",
      template: "둔기 공격에 약한 적에게 주는 데미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "클럽의 숙련도",
      maxLvl: 10,
      req: "상반기 클럽 Lv.5",
      template: "Increases club skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "방어의 표식",
      maxLvl: 10,
      req: "상반기 클럽 Lv.10",
      template: "+{val}초마다 HP를 회복합니다.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "클럽 관리 개선",
      maxLvl: 10,
      req: "상반기 클럽 Lv.10",
      template: "걷기에 필요한 SP 소모량 감소+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "전투 본능",
      maxLvl: 10,
      req: "상반기 클럽 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 본능",
      maxLvl: 10,
      req: "상반기 클럽 숙련도 - 레벨 15, 방어 마크 - 레벨 1",
      template: "최대 HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "갑옷 브레이크",
      maxLvl: 10,
      req: "상반기 클럽 Lv.20",
      template: "모든 공격은 +{val}초 동안 공격받은 적에게 방어 디버프를 적용할 확률이 있습니다.",
      calc: (lvl) => [16, 17, 18, 19, 20, 21, 22, 23, 24, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "무기 지식",
      maxLvl: 10,
      req: "상반기 클럽 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "무기 브레이크",
      maxLvl: 10,
      req: "상반기 클럽 Lv.30",
      template: "모든 공격은 +{val}초 동안 공격받은 적에게 공격 디버프를 적용할 확률이 있습니다.",
      calc: (lvl) => [27, 29, 31, 33, 35, 37, 39, 41, 43, 45][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Secret",
      maxLvl: 10,
      req: "상반기 클럽 Lv.35",
      template: "메이스 장착시 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "소드 스킬 마스터리",
      maxLvl: 10,
      req: "상반기 클럽 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "과충전 I (1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "플레임 글로우(1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.50",
      template: "불속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "아쿠아 글로우 (1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.50",
      template: "수속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "윈드 글로우 (1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.50",
      template: "바람속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "어스 글로우(1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.50",
      template: "땅속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "샤인글로우 (1H클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.50",
      template: "성속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "다크 글로우 (1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.50",
      template: "어둠속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "생존 전문성(1H클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "무뚝뚝한 실력 (1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.60",
      template: "둔기 공격에 약한 적에게 주는 데미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강력한 방어 전문성(1H클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "조각된 일격",
      maxLvl: 10,
      req: "상반기 클럽 Lv.70",
      template: "[[표식 디버프]에 의해 디버프된 적에 대한 공격력이 증가합니다.",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "치열한 공격 전문성 (1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 백업",
      maxLvl: 10,
      req: "상반기 클럽 Lv.80",
      template: "스위치로 적 타격 시 파티원의 둔기 약점 데미지+{val} 증가로 버프",
      calc: (lvl) => lvl * 0.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "높은 방어력",
      maxLvl: 10,
      req: "상반기 클럽 Lv.85",
      template: "플레이어가 활성 버프를 가지고 있는 동안 방어력이 증가합니다.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "윈드라이즈 (1H클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.90",
      template: "바람속성+{val} 사용시 공격력 증가",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "격려",
      maxLvl: 10,
      req: "상반기 클럽 Lv.95",
      template: "스위치를 사용하여 적을 공격한 후 플레이어와 파티는 +{val}초 동안 공격력을 증가시키는 버프를 받습니다.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "윈드 차지(1H 클럽)",
      maxLvl: 10,
      req: "상반기 클럽 Lv.100",
      template: "풍속성+{val} 데미지 증가",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "새겨진 히트",
      maxLvl: 10,
      req: "상반기 클럽 Lv.105",
      template: "[[표식 디버프]에 의해 디버프된 적에 대한 공격력이 증가합니다.",
      calc: (lvl) => lvl * 20,
      bonusType: "atk_percent",
      active: true,
    },
  ],
  Dagger: [
    {
      name: "단검 훈련",
      maxLvl: 10,
      req: "단검 Lv.1",
      template: "단검 장착 시 일반 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "보복",
      maxLvl: 10,
      req: "단검 Lv.1",
      template: "HP가 +{val}% 미만일 때 공격력 증가",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "단검의 일격",
      maxLvl: 10,
      req: "단검 Lv.1",
      template: "Increases damage dealt to an enemy which isn't focused on the player",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "기본 자세",
      maxLvl: 10,
      req: "단검 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "잔인한 칼날",
      maxLvl: 10,
      req: "단검 Lv.5",
      template: "단검 장착 시 상태이상에 걸린 적에 대한 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "단검 숙련도",
      maxLvl: 10,
      req: "단검 Lv.5",
      template: "Increases dagger skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "도둑의 증거",
      maxLvl: 10,
      req: "단검 Lv.10",
      template: "스위치를 사용하여 적을 공격한 후 +{val}초 동안 중독시킵니다(1중첩).",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "단검 제어 개선",
      maxLvl: 10,
      req: "단검 Lv.10",
      template: "걷기에 필요한 SP 소모량 감소+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "전투 본능",
      maxLvl: 10,
      req: "단검 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 본능",
      maxLvl: 10,
      req: "상반기 단검 숙련도 - 15레벨, 도둑의 증명 - 1레벨",
      template: "최대 HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "회피",
      maxLvl: 10,
      req: "단검 Lv.20",
      template: "플레이어의 최대 HP가 +{val}% 미만일 때 모든 공격(집중 공격 제외)을 회피할 확률이 증가합니다.",
      calc: (lvl) => lvl * 2,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "무기 지식",
      maxLvl: 10,
      req: "단검 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Executer's Eyes",
      maxLvl: 10,
      req: "단검 Lv.30",
      template: "모든 공격은 다음 +{val}초 동안 다음 공격으로 적이 더 많은 피해를 입도록 만들 확률이 있습니다.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dagger's Secret",
      maxLvl: 10,
      req: "단검 Lv.35",
      template: "단검 장착 시 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "소드 스킬 마스터리",
      maxLvl: 10,
      req: "단검 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "과충전 I(단검)",
      maxLvl: 10,
      req: "단검 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "화염광(단검)",
      maxLvl: 10,
      req: "단검 Lv.50",
      template: "불속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "아쿠아 글로우(단검)",
      maxLvl: 10,
      req: "단검 Lv.50",
      template: "수속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "바람의 빛(단검)",
      maxLvl: 10,
      req: "단검 Lv.50",
      template: "바람속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "어스 글로우(단검)",
      maxLvl: 10,
      req: "단검 Lv.50",
      template: "땅속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "샤인 글로우(단검)",
      maxLvl: 10,
      req: "단검 Lv.50",
      template: "성속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "다크 글로우(단검)",
      maxLvl: 10,
      req: "단검 Lv.50",
      template: "어둠속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "생존 전문 지식(단검)",
      maxLvl: 10,
      req: "단검 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "슬래시 숙련도(단검)",
      maxLvl: 10,
      req: "단검 Lv.60",
      template: "베기 공격에 약한 적에게 주는 대미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강력한 방어 전문성(단검)",
      maxLvl: 10,
      req: "단검 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "후속 파업",
      maxLvl: 10,
      req: "단검 Lv.70",
      template: "[[독(상태 이상을 가하는 스킬)]에 걸린 적에 대한 공격력이 증가합니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "맹렬한 공격 전문성(단검)",
      maxLvl: 10,
      req: "단검 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "날카로운 플래시",
      maxLvl: 10,
      req: "단검 Lv.80",
      template: "[[독(상태 이상을 가하는 스킬)]에 걸린 적에 대한 공격력이 증가합니다.",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "상태 이상 보너스",
      maxLvl: 10,
      req: "단검 Lv.85",
      template: "상태 이상에 걸린 적에 대한 공격력이 증가합니다.",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "다크라이즈(단검)",
      maxLvl: 10,
      req: "단검 Lv.90",
      template: "어둠속성+{val} 사용시 공격력 증가",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "광택나는 일격",
      maxLvl: 10,
      req: "단검 Lv.95",
      template: "[[독(상태 이상을 가하는 스킬)]에 걸린 적에 대한 공격력이 증가합니다.",
      calc: (lvl) => lvl * 0.01,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "어둠의 돌진(단검)",
      maxLvl: 10,
      req: "단검 Lv.100",
      template: "암흑속성+{val} 데미지 증가",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "블러디 어썰트",
      maxLvl: 10,
      req: "단검 Lv.105",
      template: "Increases player's Attack when attacking enemies afflicted with [[Bleed (skill inflicting status ailment)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
  ],
  Axe: [
    {
      name: "도끼 훈련",
      maxLvl: 10,
      req: "2H 액스 Lv.1",
      template: "도끼 장착 시 일반 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Body's Enhancement",
      maxLvl: 10,
      req: "2H 액스 Lv.1",
      template: "도끼 장착 시 공격력 증가+{val}",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Axe's Blow",
      maxLvl: 10,
      req: "2H 액스 Lv.1",
      template: "스위치를 사용하여 적을 공격한 후 플레이어에게 버프를 주어 +{val}초 동안 받는 피해를 줄입니다.",
      calc: (lvl) => lvl * 2.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "기본 자세",
      maxLvl: 10,
      req: "2H 액스 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "투지",
      maxLvl: 10,
      req: "2H 액스 Lv.5",
      template: "스위치 게이지 충전율+{val} 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "도끼 숙련도",
      maxLvl: 10,
      req: "2H 액스 Lv.5",
      template: "Increases axe skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "용병의 징표",
      maxLvl: 10,
      req: "2H 액스 Lv.10",
      template: "모든 도끼 스킬 레코드의 SP 소모량 감소+{val}",
      calc: (lvl) => lvl * 15,
      bonusType: "sp",
      active: true,
    },
    {
      name: "도끼 제어 개선",
      maxLvl: 10,
      req: "2H 액스 Lv.10",
      template: "걷기에 필요한 SP 소모량 감소+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "전투 본능",
      maxLvl: 10,
      req: "2H 액스 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 본능",
      maxLvl: 10,
      req: "양손 도끼 숙련도 - 15레벨, 용병의 증표 - 1레벨",
      template: "최대 HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "쪼개짐",
      maxLvl: 10,
      req: "2H 액스 Lv.20",
      template: "최대 HP의 +{val}% 이상인 적에 대한 공격력이 증가합니다.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "무기 지식",
      maxLvl: 10,
      req: "2H 액스 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "콩고",
      maxLvl: 10,
      req: "2H 액스 Lv.30",
      template: "Decreases damage taken if it's more than +{val}% of character's max HP.",
      calc: (lvl) => [30, 35, 40, 45, 50, 55, 60, 65, 70, 75][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Axe's Secret",
      maxLvl: 10,
      req: "2H 액스 Lv.35",
      template: "도끼 장착 시 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "소드 스킬 마스터리",
      maxLvl: 10,
      req: "2H 액스 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "과충전 I (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "화염 글로우 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.50",
      template: "불속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "아쿠아 글로우 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.50",
      template: "수속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "바람의 빛 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.50",
      template: "바람속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "대지의 빛 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.50",
      template: "땅속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "샤인 글로우 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.50",
      template: "성속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "어둠의 빛 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.50",
      template: "어둠속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "생존 전문성 (양손 도끼)",
      maxLvl: 10,
      req: "2H 액스 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "둔기 숙련 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.60",
      template: "둔기 공격에 약한 적에게 주는 데미지 증가+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강력한 방어 전문성 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 힘",
      maxLvl: 10,
      req: "2H 액스 Lv.70",
      template: "남은 HP+{val}에 비례하여 공격력 증가",
      calc: (lvl) =>
        [210, 220, 230, 240, 250, 260, 270, 280, 290, 300][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "맹렬한 공격 전문성 (양손 도끼)",
      maxLvl: 10,
      req: "2H 액스 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "반전 강화",
      maxLvl: 10,
      req: "2H 액스 Lv.80",
      template: "When receiving a hit, there's a chance to obtain a buff which increases Attack+{val}",
      calc: (lvl) =>
        [15.5, 16, 16.5, 17, 17.5, 18, 18.5, 19, 19.5, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "다이나믹 어썰트",
      maxLvl: 10,
      req: "2H 액스 Lv.85",
      template: "플레이어 증가\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) => lvl * 0.25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "어스 라이즈 (2H 도끼)",
      maxLvl: 10,
      req: "2H 액스 Lv.90",
      template: "땅속성+{val} 사용시 공격력 증가",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "단검 스킬 마스터리 (2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.95",
      template: "단일 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "대지의 돌진(2H Axe)",
      maxLvl: 10,
      req: "2H 액스 Lv.100",
      template: "땅속성+{val} 데미지 증가",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강력한 공격",
      maxLvl: 10,
      req: "2H 액스 Lv.105",
      template: "Increases player's Attack proportionally to the percentage of remaining HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "과충전 I",
      maxLvl: 1,
      req: "양손 도끼 숙련도 - 레벨 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 전문성",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 55레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 국방 전문성",
      maxLvl: 10,
      req: "2H Axe 숙련도 - 레벨 65 , 생존 전문성(2H Axe) - 레벨 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "치열한 공격 전문성",
      maxLvl: 10,
      req: "2H Axe 숙련도 - 75레벨, 강력한 방어 전문성(2H Axe) - 5레벨",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "지구 상승",
      maxLvl: 10,
      req: "2H Axe 숙련도 - 90레벨, 다이나믹 어썰트 - 5레벨",
      template: "땅속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "지구 충전",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 100 레벨, 단검 스킬 마스터리(2H 도끼) - 레벨 5",
      template: "땅속성 데미지가 증가합니다. +{발}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "싱글 소드 스킬 마스터리",
      maxLvl: 10,
      req: "2H Axe 숙련도 - 95레벨, 다이나믹 어썰트 - 레벨 5",
      template: "단일 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "불꽃 글로우",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 50레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "불속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "아쿠아 글로우",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 50레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "물속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "바람의 빛",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 50레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "바람 속성 사용 시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "지구 빛",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 50레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "땅속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "샤인 글로우",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 50레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "신성속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "다크 글로우",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 50레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "어둠속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "고급 검 기술",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 50레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 깨기",
      maxLvl: 10,
      req: "2H 도끼 숙련도 - 50레벨, 소드 스킬 마스터리(2H 도끼) - 5레벨",
      template: "소드 스킬의 브레이크 값이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "결합된 체인 공격",
      maxLvl: 10,
      req: "양손 도끼 숙련도 - 110레벨, 강력한 공격 - 레벨 5",
      template: "Switch에서 사용되는 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Spear: [
    {
      name: "창 훈련",
      maxLvl: 10,
      req: "2H 스피어 Lv.1",
      template: "창 장착 시 일반 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "스탬피드",
      maxLvl: 10,
      req: "2H 스피어 Lv.1",
      template: "창 장착 시, 밟은 후 +{val}초 동안 공격력이 증가합니다.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Spear's Blow",
      maxLvl: 10,
      req: "2H 스피어 Lv.1",
      template: "스위치를 사용하여 적을 공격한 후 플레이어에게 버프를 주어 +{val}초 동안 치명타 발생률을 증가시킵니다.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 자세",
      maxLvl: 10,
      req: "2H 스피어 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강풍",
      maxLvl: 10,
      req: "2H 스피어 Lv.5",
      template: "창술기록+{val}의 쿨타임 단축",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "창 숙련도",
      maxLvl: 10,
      req: "2H 스피어 Lv.5",
      template: "Increases spear skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "기사의 표식",
      maxLvl: 10,
      req: "2H 스피어 Lv.10",
      template: "적 처치 시 SP 회복+{val}",
      calc: (lvl) => lvl * 3,
      bonusType: "sp",
      active: true,
    },
    {
      name: "창 제어 개선",
      maxLvl: 10,
      req: "2H 스피어 Lv.10",
      template: "걷기에 필요한 SP 소모량 감소+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "전투 본능",
      maxLvl: 10,
      req: "2H 스피어 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 본능",
      maxLvl: 10,
      req: "2H 창 숙련 - 15레벨, 기사의 증표 - 1레벨",
      template: "최대 HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "송곳니",
      maxLvl: 10,
      req: "하반기 스피어 Lv.20",
      template: "창 장착 시 상태이상에 걸린 적에 대한 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "무기 지식",
      maxLvl: 10,
      req: "2H 스피어 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "창춤",
      maxLvl: 10,
      req: "2H 스피어 Lv.30",
      template: "설명 보류 중(위키 스텁)",
      calc: (lvl) => 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Spear's Secret",
      maxLvl: 10,
      req: "2H 스피어 Lv.35",
      template: "창 장착 시 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "소드 스킬 마스터리",
      maxLvl: 10,
      req: "2H 스피어 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "과충전 I (2H 창)",
      maxLvl: 10,
      req: "2H 스피어 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "화염 글로우(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.50",
      template: "불속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "아쿠아 글로우(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.50",
      template: "수속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "윈드 글로우(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.50",
      template: "바람속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "어스 글로우(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.50",
      template: "땅속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "샤인 글로우(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.50",
      template: "성속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "다크 글로우(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.50",
      template: "어둠속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "생존 전문성(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "추력 숙련도(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.60",
      template: "찌르기 공격에 약한 적에게 주는 대미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강력한 방어 전문성(하반기 창)",
      maxLvl: 10,
      req: "2H 스피어 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "마킹 스위치",
      maxLvl: 10,
      req: "2H 스피어 Lv.70",
      template: "스위치로 적 타격 시, 일정 확률로 적에게 +{val}초 동안 [스티그마 디버프]]를 부여합니다.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    {
      name: "맹렬한 공격 전문성(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "약자의 추적",
      maxLvl: 10,
      req: "2H 스피어 Lv.80",
      template: "디버프가 걸린 적에 대한 공격력 증가+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "소드 스킬 마스터리 종합(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.85",
      template: "활성 슬롯 및 커넥트 체인에 포함된 슬롯의 소드 스킬 위력이 +{val}% 증가합니다.",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "윈드 라이즈(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.90",
      template: "바람속성+{val} 사용시 공격력 증가",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "파괴 예술",
      maxLvl: 10,
      req: "2H 스피어 Lv.95",
      template: "휴식 효율 증가+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "윈드 차지(2H 스피어)",
      maxLvl: 10,
      req: "2H 스피어 Lv.100",
      template: "풍속성+{val} 데미지 증가",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "갑옷 감쇠 스위치",
      maxLvl: 10,
      req: "2H 스피어 Lv.105",
      template: "스위치로 적 타격 시, 일정 확률로 적에게 +{val}초 동안 [[방어구 부패 디버프]]를 부여합니다.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "과충전 I",
      maxLvl: 1,
      req: "하반기 창 숙련 - 레벨 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 전문성",
      maxLvl: 10,
      req: "2H 창 숙련 - 55레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 국방 전문성",
      maxLvl: 10,
      req: "2H 창 숙련도 - 레벨 65 , 생존 전문성(2H 창) - 레벨 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "치열한 공격 전문성",
      maxLvl: 10,
      req: "2H 창 숙련도 - 75레벨, 강력한 방어 전문성(2H 창) - 5레벨",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "윈드 라이즈",
      maxLvl: 10,
      req: "2H 창 숙련 - 90 레벨, 검술 종합 숙련(2H 창) - 5 레벨",
      template: "바람 속성 사용 시 공격력이 증가합니다. +{발}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "풍력 충전",
      maxLvl: 10,
      req: "하반기 창 숙련 - 100레벨, 디스트럭션 아트 - 5레벨",
      template: "바람속성 데미지가 증가합니다. +{발}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "전반적인 소드 스킬 마스터리",
      maxLvl: 10,
      req: "창 숙련 - 85레벨, 맹렬한 공격 숙련(2H 창) - 5레벨",
      template: "활성 슬롯 및 커넥트 체인에 포함된 슬롯의 소드 스킬 위력이 +{val}% 증가합니다.",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "불꽃 글로우",
      maxLvl: 10,
      req: "2H 창 숙련 - 50레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "불속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "아쿠아 글로우",
      maxLvl: 10,
      req: "2H 창 숙련 - 50레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "물속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "바람의 빛",
      maxLvl: 10,
      req: "2H 창 숙련 - 50레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "바람 속성 사용 시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "지구 빛",
      maxLvl: 10,
      req: "2H 창 숙련 - 50레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "땅속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "샤인 글로우",
      maxLvl: 10,
      req: "2H 창 숙련 - 50레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "신성속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "다크 글로우",
      maxLvl: 10,
      req: "2H 창 숙련 - 50레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "어둠속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "고급 검 기술",
      maxLvl: 10,
      req: "2H 창 숙련 - 50레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 깨기",
      maxLvl: 10,
      req: "2H 창 숙련 - 50레벨, 소드 스킬 마스터리(2H 창) - 5레벨",
      template: "소드 스킬의 브레이크 값이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "결합된 체인 공격",
      maxLvl: 10,
      req: "2H 창 숙련도 - 레벨 110, 방어구 부패 스위치 - 레벨 1",
      template: "Switch에서 사용되는 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Bow: [
    {
      name: "활 훈련",
      maxLvl: 10,
      req: "활 Lv.1",
      template: "활 장착 시 일반 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "피어스",
      maxLvl: 10,
      req: "활 Lv.1",
      template: "HP가 +{val}% 이상일 때 공격력 증가",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "플래시",
      maxLvl: 10,
      req: "활 Lv.1",
      template: "스위치를 사용하여 적을 공격한 후 플레이어에게 버프를 주어 +{val}초 동안 치명타 발생률을 증가시킵니다.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 자세",
      maxLvl: 10,
      req: "활 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "정확한 샷",
      maxLvl: 10,
      req: "활 Lv.5",
      template: "찌르기 공격에 약한 적에게 주는 대미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "활 숙련도",
      maxLvl: 10,
      req: "활 Lv.5",
      template: "Increases bow skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "궁수의 증표",
      maxLvl: 10,
      req: "활 Lv.10",
      template: "일부 활 스킬 레코드+{val} 충전에 필요한 시간이 단축됩니다.",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    {
      name: "활 제어 개선",
      maxLvl: 10,
      req: "활 Lv.10",
      template: "걷기에 필요한 SP 소모량 감소+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "전투 본능",
      maxLvl: 10,
      req: "활 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 본능",
      maxLvl: 10,
      req: "활 숙련도 - 15레벨, 궁수의 증표 - 1레벨",
      template: "최대 HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Predator's Keen Eye",
      maxLvl: 10,
      req: "활 Lv.20",
      template: "최대 HP의 +{val}% 미만인 적에 대한 공격력이 증가합니다.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "무기 지식",
      maxLvl: 10,
      req: "활 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "초승달",
      maxLvl: 10,
      req: "활 Lv.30",
      template: "스위치에서 활 스킬로 적을 타격한 후 +{val}초 동안(또는 플레이어가 피해를 입을 때까지) 공격력이 +{val}% 증가하는 버프가 활성화됩니다.",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bow's Secret",
      maxLvl: 10,
      req: "활 Lv.35",
      template: "활 장착 시 공격력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "소드 스킬 마스터리",
      maxLvl: 10,
      req: "활 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "과충전 I (활)",
      maxLvl: 10,
      req: "활 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "화염광(활)",
      maxLvl: 10,
      req: "활 Lv.50",
      template: "불속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "아쿠아 글로우(활)",
      maxLvl: 10,
      req: "활 Lv.50",
      template: "수속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "바람의 빛(활)",
      maxLvl: 10,
      req: "활 Lv.50",
      template: "바람속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "어스 글로우(활)",
      maxLvl: 10,
      req: "활 Lv.50",
      template: "땅속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "샤인 글로우(활)",
      maxLvl: 10,
      req: "활 Lv.50",
      template: "성속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "다크 글로우(활)",
      maxLvl: 10,
      req: "활 Lv.50",
      template: "어둠속성+{val} 사용시 공격력 증가",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "생존 숙련도(활)",
      maxLvl: 10,
      req: "활 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "추력 숙련도(활)",
      maxLvl: 10,
      req: "활 Lv.60",
      template: "찌르기 공격에 약한 적에게 주는 대미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "강력한 방어 전문성(활)",
      maxLvl: 10,
      req: "활 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기습 공격",
      maxLvl: 10,
      req: "활 Lv.70",
      template: "플레이어를 타겟으로 하지 않는 적에 대한 공격력 증가+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "맹렬한 공격 전문성(활)",
      maxLvl: 10,
      req: "활 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "하드 브레이크(활)",
      maxLvl: 10,
      req: "활 Lv.80",
      template: "플레이어 증가\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "리버스 스트라이크",
      maxLvl: 10,
      req: "활 Lv.85",
      template: "남은 HP 비율에 따라 공격력 증가",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "샤인라이즈(활)",
      maxLvl: 10,
      req: "활 Lv.90",
      template: "성속성+{val} 사용 시 공격력 증가",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "단검 스킬 마스터리(활)",
      maxLvl: 10,
      req: "활 Lv.95",
      template: "단일 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "샤인 차지(활)",
      maxLvl: 10,
      req: "활 Lv.100",
      template: "성속성+{val} 데미지 증가",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "역습",
      maxLvl: 10,
      req: "활 Lv.105",
      template: "Increases player's Attack proportionally to the percentage of lost HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "과충전 I",
      maxLvl: 1,
      req: "활 숙련도 - 레벨 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "생존 전문성",
      maxLvl: 10,
      req: "활 숙련도 - 55레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 국방 전문성",
      maxLvl: 10,
      req: "활 숙련도 - 레벨 65 , 생존 전문성(활) - 레벨 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "치열한 공격 전문성",
      maxLvl: 10,
      req: "활 숙련도 - 75레벨, 강력한 방어 전문성(활) - 5레벨",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "하드 브레이크",
      maxLvl: 10,
      req: "활 숙련도 - 80레벨, 맹렬한 공격 숙련도(활) - 5레벨",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "샤인 라이즈",
      maxLvl: 10,
      req: "활 숙련도 - 레벨 90 , 리버스 스트라이크 - 레벨 5",
      template: "신성속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "샤인 차지",
      maxLvl: 10,
      req: "활 숙련도 - 100레벨, 단검 스킬 마스터리(활) - 5레벨",
      template: "홀리속성 데미지가 증가합니다. +{발}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "싱글 소드 스킬 마스터리",
      maxLvl: 10,
      req: "활 숙련도 - 레벨 95 , 리버스 스트라이크 - 레벨 5",
      template: "단일 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "불꽃 글로우",
      maxLvl: 10,
      req: "활 숙련도 - 50레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "불속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "아쿠아 글로우",
      maxLvl: 10,
      req: "활 숙련도 - 50레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "물속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "바람의 빛",
      maxLvl: 10,
      req: "활 숙련도 - 50레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "바람 속성 사용 시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "지구 빛",
      maxLvl: 10,
      req: "활 숙련도 - 50레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "땅속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "샤인 글로우",
      maxLvl: 10,
      req: "활 숙련도 - 50레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "신성속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "다크 글로우",
      maxLvl: 10,
      req: "활 숙련도 - 50레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "어둠속성 사용시 공격력이 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "고급 검 기술",
      maxLvl: 10,
      req: "활 숙련도 - 50레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "기본 깨기",
      maxLvl: 10,
      req: "활 숙련도 - 50레벨, 소드 스킬 마스터리(활) - 5레벨",
      template: "소드 스킬의 브레이크 값이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "결합된 체인 공격",
      maxLvl: 10,
      req: "활 숙련도 - 110레벨, 역습 - 레벨 5",
      template: "Switch에서 사용되는 소드 스킬의 위력이 +{val}% 증가합니다.",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Shield: [
    {
      name: "쉴드 트레이닝",
      maxLvl: 10,
      req: "방패 Lv.1",
      template: "방패 장착 시 방어력 증가+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "저항하다",
      maxLvl: 10,
      req: "방패 Lv.1",
      template: "방패 장착 시 피해를 주는 상태 이상에 대한 저항력 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "보호하다",
      maxLvl: 10,
      req: "방패 Lv.1",
      template: "스위치를 사용하여 적을 공격한 후 플레이어에게 버프를 주어 방어력을 +{val}초 동안 증가시킵니다.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "결단력 있는 가드",
      maxLvl: 10,
      req: "쉴드 Lv.5",
      template: "장착한 실드 스킬 레코드 수+{val}에 따라 받는 데미지를 백분율로 감소시킵니다.",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "반사",
      maxLvl: 10,
      req: "방패 Lv.10",
      template: "받은 피해의 일부를 적에게 반사+{val}",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "생존 본능",
      maxLvl: 10,
      req: "쉴드 숙련도 - 레벨 15, 반사 - 레벨 1",
      template: "최대 HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "활력",
      maxLvl: 10,
      req: "방패 Lv.20",
      template: "방패 장착 시 움츠러들기 저항 증가+{val}",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "쉴드 지식",
      maxLvl: 10,
      req: "방패 Lv.25",
      template: "Passively increases the player's Defense+{val}",
      calc: (lvl) =>
        [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "초월적인",
      maxLvl: 10,
      req: "방패 Lv.30",
      template: "방패 스킬 기록+{val}의 데미지 증가",
      calc: (lvl) => [30, 35, 40, 45, 50][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "쉴드 힐링",
      maxLvl: 10,
      req: "방패 Lv.55",
      template: "+{val}초마다 일정량의 HP를 회복합니다.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "복구 전문성",
      maxLvl: 10,
      req: "방패 Lv.60",
      template: "치유 아이템의 효과를 패시브로 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "신체강화(방패)",
      maxLvl: 10,
      req: "방패 Lv.65",
      template: "최대 HP +{val}",
      calc: (lvl) => lvl * 50,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "필드힐",
      maxLvl: 10,
      req: "방패 Lv.70",
      template: "치유 식물의 효과를 수동적으로 증가시킵니다.+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 타격",
      maxLvl: 10,
      req: "방패 Lv.75",
      template: "둔기에 약한 적에게 대미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "육체적 격려(방패)",
      maxLvl: 10,
      req: "방패 Lv.80",
      template: "Passively increases player's HP+{val}",
      calc: (lvl) =>
        [525, 550, 575, 600, 625, 650, 675, 700, 725, 750][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 슬래시",
      maxLvl: 10,
      req: "방패 Lv.85",
      template: "슬래시에 약한 적에게 주는 대미지 증가+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    ,
    {
      name: "신체적 격려",
      maxLvl: 10,
      req: "실드 숙련도 - 80레벨, 강력한 타격 - 레벨 5",
      template: "Passively increases player's HP. +{val}",
      calc: (lvl) => 500 + lvl * 25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "강력한 추진력",
      maxLvl: 10,
      req: "방패 숙련도 - 90레벨, 강력한 베기 - 5레벨",
      template: "찌르기에 약한 적에게 주는 피해가 증가합니다. +{발}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
  ],
};
