window.masteryData = {
  Sword: [
    {
      name: "Sword Training",
      maxLvl: 10,
      req: "1H Sword Lv.1",
      template: "When 1h Sword is equipped, normal attack's damage +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Chivalry",
      maxLvl: 10,
      req: "1H Sword Lv.1",
      template:
        "Increases Attack and Defense when a sword is equipped by +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "flat_atk_def",
      active: true,
    },
    {
      name: "Sword's Blow",
      maxLvl: 10,
      req: "1H Sword Lv.1",
      template:
        "After hitting an enemy with Switch, buffs the player's Attack and Defense for 8 seconds by +{val}%",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Basic Stance",
      maxLvl: 10,
      req: "1H Sword Lv.1",
      template:
        "Adds +{val} additional damage to enemy when attacking (All Weapons)",
      calc: (lvl) => lvl * 5,
      bonusType: "flat_damage",
      active: true,
    },
    {
      name: "Full Strike",
      maxLvl: 10,
      req: "Sword Training Lv.5",
      template:
        "When 1H Sword is equipped, Damage done to enemies weak to slashing +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "Sword Proficiency",
      maxLvl: 10,
      req: "Sword Training Lv.5, Full Strike Lv.5",
      template: "When 1H Sword is equipped, Sword Skill Power +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Mark of Warrior",
      maxLvl: 1,
      req: "1H Sword Lv.10, Full Strike Lv.5",
      template: "When 1H Sword is equipped, Restore +{val}% HP on Kill",
      calc: (lvl) => lvl * 2,
      bonusType: "healing_percent",
      active: true,
    },
    {
      name: "Sword Control Improvement",
      maxLvl: 1,
      req: "1H Sword Lv.10, Basic Stance Lv.5",
      template: "When 1H Sword is equipped, SP cost -{val} for stepping",
      calc: (lvl) => lvl * 1,
      bonusType: "step_reduction",
      active: true,
    },
    {
      name: "Battle Instinct",
      maxLvl: 10,
      req: "1H Sword Lv.10, Basic Stance Lv.5",
      template: "Attack +{val} (All Weapons)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Survival Instinct",
      maxLvl: 10,
      req: "1H Sword Lv.15, Mark of Warrior Lv.1",
      template: "Max HP +{val}% (All Weapons)",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Combination",
      maxLvl: 10,
      req: "1H Sword Lv.20, Survival Instinct Lv.5",
      template: "When 1H Sword is equipped, Switch Damage +{val}%",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Weapon Knowledge",
      maxLvl: 10,
      req: "1H Sword Lv.25, Combination Lv.5",
      template: "Attack +{val}% (All Weapons)",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.699999999999999, 5][
          lvl - 1
        ] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Switch Charge",
      maxLvl: 10,
      req: "1H Sword Lv.30, Weapon Knowledge Lv.5",
      template:
        "When 1H Sword is equipped,Recover +{val} SP on switch skill use",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "sp_recovery_flat",
      active: true,
    },
    {
      name: "Sword's Secret",
      maxLvl: 10,
      req: "1H Sword Lv.35, Switch Charge Lv.1",
      template: "When 1H Sword is equipped, Attack +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Sword Skill Mastery",
      maxLvl: 10,
      req: "1H Sword Lv.40, Weapon Knowledge Lv.10",
      template: "Sword skill power +{val}% (effective with all weapons)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "ss_power",
      active: true,
    },
    {
      name: "Overcharge I (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.45",
      template:
        "Switch Gauge will charge up to the third level When 1H Sword is equipped. Damage +200% when using switch on the third level. ",
      calc: (lvl) => 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Flame Glow (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.50, Sword Skill Mastery Lv.5",
      template:
        "Attack +{val}% when attacking with Fire Element and equipping a 1H Sword",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.50, Sword Skill Mastery Lv.5",
      template:
        "Attack +{val}% when attacking with Water Element and equipping a 1H Sword",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Wind Glow (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.50, Sword Skill Mastery Lv.5",
      template:
        "Attack +{val}% when attacking with Wind Element and equipping a 1H Sword",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Earth Glow (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.50, Sword Skill Mastery Lv.5",
      template:
        "Attack +{val}% when attacking with Earth Element and equipping a 1H Sword",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.50, Sword Skill Mastery Lv.5",
      template:
        "Attack +{val}% when attacking with Holy Element and equipping a 1H Sword",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Glow (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.50, Sword Skill Mastery Lv.5",
      template:
        "Attack +{val}% when attacking with Dark Element and equipping a 1H Sword",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Survival Expertise (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.55, Sword Skill Mastery Lv.5",
      template: "HP +{val} when equipping a 1H Sword",
      calc: (lvl) => lvl * 100,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "Slash Proficiency (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.60, Survival Expertise (1H Sword) Lv.5",
      template:
        "When 1H Sword is equipped, damage done to enemies weak to slashing +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "Strong Defense Expertise (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.65, Survival Expertise (1H Sword) Lv.5",
      template: "Defense +{val} when equipping a 1H Sword",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "def_flat",
      active: true,
    },
    {
      name: "Burn Guard",
      maxLvl: 10,
      req: "1H Sword Lv.70, Strong Defense Expertise (1H Sword) Lv.5",
      template: "When 1H Sword is equipped, Burn damage -{val}",
      calc: (lvl) =>
        [-4.5, -4, -3.5, -3, -2.5, -2, -1.5, -1, -0.5, 0][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fierce Attack Expertise (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.75, Strong Defense Expertise (1H Sword) Lv.5",
      template: "Attack +{val} when equipping a 1H Sword",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Hard Break (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.80, Fierce Attack Expertise (1H Sword) Lv.5",
      template: "When 1H Sword is equipped, attack +{val} when using Break",
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Single Sword Skill Mastery (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.85, Fierce Attack Expertise (1H Sword) Lv.5",
      template: "Sword skill power (single) +{val}% when equipping a 1H Sword",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "skill_power",
      active: true,
    },
    {
      name: "Flame Rise (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.90,Fierce Attack Expertise (1H Sword) Lv.5",
      template:
        "When equipping a 1H Sword,attack +{val} when using Fire element",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Sword Skill Proficiency (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.95,Single Sword Skill Mastery (1H Sword) Lv.5",
      template: "Sword Skill Damage +{val}% (effective with all weapons)",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Flame Charge (1H Sword)",
      maxLvl: 10,
      req: "1H Sword Lv.100,Sword Skill Proficiency (1H Sword) Lv.5",
      template: "When equipping a 1H Sword,Fire Element Damage +{val}%",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "damage_percent_fire",
      active: true,
    },
    {
      name: "Adversity Guard",
      maxLvl: 10,
      req: "1H Sword Lv.105,Flame Charge (1H Sword) Lv.5",
      template:
        "Defense +{val} when equipping a 1H Sword and HP is 25% or lower",
      calc: (lvl) => lvl * 10,
      bonusType: "def_flat",
      active: true,
    },
    ,
    {
      name: "Overcharge I",
      maxLvl: 1,
      req: "1H Sword Proficiency - Level 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Expertise",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 55 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Strong Defense Expertise",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 65 ,  Survival Expertise (1H Sword) - Level 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fierce Attack Expertise",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 75 ,  Strong Defense Expertise (1H Sword) - Level 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Single Sword Skill Mastery",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 85 ,  Fierce Attack Expertise (1H Sword) - Level 5",
      template:
        "Increases power of single Sword Skills by +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sword Skill Proficiency",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 95 ,  Single Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases power of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Hard Break",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 80 ,  Fierce Attack Expertise (1H Sword) - Level 5",
      template:
        "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Rise",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 90 ,  Single Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases Attack when using Fire element. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Charge",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 100 ,  Sword Skill Proficiency (1H Sword) - Level 5",
      template: "Increases damage dealt with Fire element. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 50 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases Attack when using Fire element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Glow",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 50 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases Attack when using Water element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Glow",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 50 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases Attack when using Wind element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Glow",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 50 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases Attack when using Earth element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shine Glow",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 50 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases Attack when using Holy element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dark Glow",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 50 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases Attack when using Dark element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Applied Stance",
      maxLvl: 10,
      req: "Release Crystal (M) x 1",
      template:
        "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 125,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Developed Stance",
      maxLvl: 10,
      req: "Release Crystal (L) x 3",
      template:
        "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Advancing Sword Technique",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 50 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template: "Increases power of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Breaking Fundamentals",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 50 ,  Sword Skill Mastery (1H Sword) - Level 5",
      template:
        "Increases Break value of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Bonded Chain Attack",
      maxLvl: 10,
      req: "1H Sword Proficiency - Level 110 ,  Adversity Guard - Level 5",
      template:
        "Increases power of Sword Skills used on Switch by +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Rapier: [
    {
      name: "Rapier Training",
      maxLvl: 10,
      req: "1H Rapier Lv.1",
      template:
        "Increases damage of regular attack when a 1H rapier is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Serial Attack",
      maxLvl: 10,
      req: "1H Rapier Lv.1",
      template:
        "Increases Attack accordingly to number of HITs dealt in a single combo, when rapier is equipped+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Rapier's Blow",
      maxLvl: 10,
      req: "1H Rapier Lv.1",
      template:
        "After hitting an enemy using Switch, player receives a buff which increases their Critical Rate for +{val} seconds.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Basic Stance",
      maxLvl: 10,
      req: "1H Rapier Lv.1",
      template:
        "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Target Weak Spot",
      maxLvl: 10,
      req: "1H Rapier Lv.5",
      template:
        "Increases damage dealt to enemies weak to thrust attacks+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Rapier Proficiency",
      maxLvl: 10,
      req: "1H Rapier Lv.5",
      template:
        "Increases rapier skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Mark of Swordsman",
      maxLvl: 10,
      req: "1H Rapier Lv.10",
      template: "Restores SP when dealing a Critical Hit+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Rapier Control Improvement",
      maxLvl: 10,
      req: "1H Rapier Lv.10",
      template: "Decreases SP cost needed for stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Battle Instinct",
      maxLvl: 10,
      req: "1H Rapier Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Instinct",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 15, Mark of Swordsman - Level 1",
      template: "Max HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Lightning Speed",
      maxLvl: 10,
      req: "1H Rapier Lv.20",
      template:
        "Increases Critical Damage when the player has a rapier equipped+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Weapon Knowledge",
      maxLvl: 10,
      req: "1H Rapier Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Meteor",
      maxLvl: 10,
      req: "1H Rapier Lv.30",
      template:
        "Increases Critical Rate for +{val} seconds after stepping, when a rapier is equipped.",
      calc: (lvl) => [20, 25, 30, 35, 40, 45, 50, 55, 60, 65][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rapier's Secret",
      maxLvl: 10,
      req: "1H Rapier Lv.35",
      template: "Increases Attack when a rapier is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Sword Skill Mastery",
      maxLvl: 10,
      req: "1H Rapier Lv.40",
      template:
        "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Overcharge I (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.45",
      template: 'Allows charging "Switch" meter to third level+{val}',
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.50",
      template: "Increases Attack when using Fire element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.50",
      template: "Increases Attack when using Water element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Wind Glow (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.50",
      template: "Increases Attack when using Wind element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Earth Glow (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.50",
      template: "Increases Attack when using Earth element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.50",
      template: "Increases Attack when using Holy element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Glow (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.50",
      template: "Increases Attack when using Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Survival Expertise (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Thrust Proficiency (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.60",
      template:
        "Increases damage dealt to enemies weak to thrust attacks+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Strong Defense Expertise (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Vital Point Assault",
      maxLvl: 10,
      req: "1H Rapier Lv.70",
      template:
        "Increases Attack while buff which increases Critical Damage is in effect+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fierce Attack Expertise (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Vital Point Stab",
      maxLvl: 10,
      req: "1H Rapier Lv.80",
      template: "Increases Critical Damage when using Skills+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Precise Strike",
      maxLvl: 10,
      req: "1H Rapier Lv.85",
      template: "Increases Critical Rate when using Skills by +{val}%",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Rise (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.90",
      template: "Increases Attack when using Water element+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Elaborate Strike",
      maxLvl: 10,
      req: "1H Rapier Lv.95",
      template:
        "After hitting an enemy using Switch, applies a buff to the player, which increases their Critical Damage for +{val} seconds.",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Charge (1H Rapier)",
      maxLvl: 10,
      req: "1H Rapier Lv.100",
      template: "Increases damage dealt with Water element+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Vulnerability Strike",
      maxLvl: 10,
      req: "1H Rapier Lv.105",
      template:
        "Increases player's Attack when Critical Rate buff is active+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Overcharge I",
      maxLvl: 1,
      req: "1H Rapier Proficiency - Level 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Expertise",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 55 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Strong Defense Expertise",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 65 ,  Survival Expertise (1H Rapier) - Level 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fierce Attack Expertise",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 75 ,  Strong Defense Expertise (1H Rapier) - Level 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Rise",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 90 ,  Precise Strike - Level 5",
      template: "Increases Attack when using Water element. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Charge",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 100 ,  Elaborate Strike - Level 5",
      template: "Increases damage dealt with Water element. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 50 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template: "Increases Attack when using Fire element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Glow",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 50 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template: "Increases Attack when using Water element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Glow",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 50 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template: "Increases Attack when using Wind element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Glow",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 50 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template: "Increases Attack when using Earth element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shine Glow",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 50 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template: "Increases Attack when using Holy element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dark Glow",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 50 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template: "Increases Attack when using Dark element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Advancing Sword Technique",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 50 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template: "Increases power of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Breaking Fundamentals",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 50 ,  Sword Skill Mastery (1H Rapier) - Level 5",
      template:
        "Increases Break value of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Bonded Chain Attack",
      maxLvl: 10,
      req: "1H Rapier Proficiency - Level 110 ,  Vulnerability Strike - Level 5",
      template:
        "Increases power of Sword Skills used on Switch by +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Club: [
    {
      name: "Club Training",
      maxLvl: 10,
      req: "1H Club Lv.1",
      template:
        "Increases damage of regular attack when a mace is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Knowledge for Meds",
      maxLvl: 10,
      req: "1H Club Lv.1",
      template:
        "Increases the amount of HP restored by healing items when club is equipped+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Blow",
      maxLvl: 10,
      req: "1H Club Lv.1",
      template:
        "After hitting an enemy using Switch, player and their party receive a buff which decreases damage they take for +{val} seconds.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Basic Stance",
      maxLvl: 10,
      req: "1H Club Lv.1",
      template:
        "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Hard Hit",
      maxLvl: 10,
      req: "1H Club Lv.5",
      template: "Increases damage dealt to enemies weak to blunt attacks+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Club Proficiency",
      maxLvl: 10,
      req: "1H Club Lv.5",
      template:
        "Increases club skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Mark of Defense",
      maxLvl: 10,
      req: "1H Club Lv.10",
      template: "Restores HP every +{val} seconds.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club Control Improvement",
      maxLvl: 10,
      req: "1H Club Lv.10",
      template: "Decreases SP cost needed for stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Battle Instinct",
      maxLvl: 10,
      req: "1H Club Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Instinct",
      maxLvl: 10,
      req: "1H Club Proficiency - Level 15, Mark of Defense - Level 1",
      template: "Max HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Armor Break",
      maxLvl: 10,
      req: "1H Club Lv.20",
      template:
        "Every attack has a chance to apply a defense debuff on the attacked enemy for +{val} seconds.",
      calc: (lvl) => [16, 17, 18, 19, 20, 21, 22, 23, 24, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Weapon Knowledge",
      maxLvl: 10,
      req: "1H Club Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Weapon Break",
      maxLvl: 10,
      req: "1H Club Lv.30",
      template:
        "Every attack has a chance to apply a attack debuff on the attacked enemy for +{val} seconds.",
      calc: (lvl) => [27, 29, 31, 33, 35, 37, 39, 41, 43, 45][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Secret",
      maxLvl: 10,
      req: "1H Club Lv.35",
      template: "Increases Attack when a mace is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Sword Skill Mastery",
      maxLvl: 10,
      req: "1H Club Lv.40",
      template:
        "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Overcharge I (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.45",
      template: 'Allows charging "Switch" meter to third level+{val}',
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.50",
      template: "Increases Attack when using Fire element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.50",
      template: "Increases Attack when using Water element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Wind Glow (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.50",
      template: "Increases Attack when using Wind element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Earth Glow (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.50",
      template: "Increases Attack when using Earth element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.50",
      template: "Increases Attack when using Holy element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Glow (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.50",
      template: "Increases Attack when using Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Survival Expertise (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Blunt Proficiency (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.60",
      template: "Increases damage dealt to enemies weak to blunt attacks+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Strong Defense Expertise (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carved Strike",
      maxLvl: 10,
      req: "1H Club Lv.70",
      template: "Increases Attack against enemies debuffed by [[Mark Debuff",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fierce Attack Expertise (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Powerful Backup",
      maxLvl: 10,
      req: "1H Club Lv.80",
      template:
        "When hitting an enemy using Switch, buffs party members by increasing their blunt weakness damage+{val}",
      calc: (lvl) => lvl * 0.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "High Defense",
      maxLvl: 10,
      req: "1H Club Lv.85",
      template: "Increases Defense while the player has an active buff",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Rise (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.90",
      template: "Increases Attack when using Wind element+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Encouragement",
      maxLvl: 10,
      req: "1H Club Lv.95",
      template:
        "After hitting an enemy using Switch, player and their party receive a buff which increases their Attack for +{val} seconds.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Charge (1H Club)",
      maxLvl: 10,
      req: "1H Club Lv.100",
      template: "Increases damage dealt with Wind element+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Engraved Hit",
      maxLvl: 10,
      req: "1H Club Lv.105",
      template: "Increases Attack against enemies debuffed by [[Mark Debuff",
      calc: (lvl) => lvl * 20,
      bonusType: "atk_percent",
      active: true,
    },
  ],
  Dagger: [
    {
      name: "Dagger Training",
      maxLvl: 10,
      req: "Dagger Lv.1",
      template: "Increases regular attack when a dagger is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Retaliation",
      maxLvl: 10,
      req: "Dagger Lv.1",
      template: "Increases Attack when HP is below +{val}%",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Blow of the Dagger",
      maxLvl: 10,
      req: "Dagger Lv.1",
      template:
        "Increases damage dealt to an enemy which isn't focused on the player",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Basic Stance",
      maxLvl: 10,
      req: "Dagger Lv.1",
      template:
        "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Cruel Blade",
      maxLvl: 10,
      req: "Dagger Lv.5",
      template:
        "Increases Attack against enemies with a status ailment when a dagger is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dagger Proficiency",
      maxLvl: 10,
      req: "Dagger Lv.5",
      template:
        "Increases dagger skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Proof of Thief",
      maxLvl: 10,
      req: "Dagger Lv.10",
      template:
        "After hitting an enemy using Switch, poisons him for +{val} seconds (1 stack)",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dagger Control Improvement",
      maxLvl: 10,
      req: "Dagger Lv.10",
      template: "Decreases SP cost needed for stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Battle Instinct",
      maxLvl: 10,
      req: "Dagger Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Instinct",
      maxLvl: 10,
      req: "1H Dagger Proficiency - Level 15, Proof of Thief - Level 1",
      template: "Max HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Evasion",
      maxLvl: 10,
      req: "Dagger Lv.20",
      template:
        "Increases a chance to evade any attack (except for focused ones) when the player has less than +{val}% of max HP.",
      calc: (lvl) => lvl * 2,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Weapon Knowledge",
      maxLvl: 10,
      req: "Dagger Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Executer's Eyes",
      maxLvl: 10,
      req: "Dagger Lv.30",
      template:
        "Every attack has a chance to make the enemy receive more damage with the next hit dealt during the next +{val} seconds.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dagger's Secret",
      maxLvl: 10,
      req: "Dagger Lv.35",
      template: "Increases Attack when a dagger is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Sword Skill Mastery",
      maxLvl: 10,
      req: "Dagger Lv.40",
      template:
        "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Overcharge I (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.45",
      template: 'Allows charging "Switch" meter to third level+{val}',
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.50",
      template: "Increases Attack when using Fire element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.50",
      template: "Increases Attack when using Water element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Wind Glow (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.50",
      template: "Increases Attack when using Wind element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Earth Glow (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.50",
      template: "Increases Attack when using Earth element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.50",
      template: "Increases Attack when using Holy element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Glow (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.50",
      template: "Increases Attack when using Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Survival Expertise (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Slash Proficiency (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.60",
      template: "Increases damage dealt to enemies weak to slash attacks+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Strong Defense Expertise (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Follow-Up Strike",
      maxLvl: 10,
      req: "Dagger Lv.70",
      template:
        "Increases Attack against enemies afflicted with [[Poison (skill inflicting status ailment)",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fierce Attack Expertise (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sharp Flash",
      maxLvl: 10,
      req: "Dagger Lv.80",
      template:
        "Increases Attack against enemies afflicted with [[Poison (skill inflicting status ailment)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Status Ailment Bonus",
      maxLvl: 10,
      req: "Dagger Lv.85",
      template:
        "Increases Attack against enemies affected by any Status Ailment",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Rise (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.90",
      template: "Increases Attack when using Dark element+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Polished Strike",
      maxLvl: 10,
      req: "Dagger Lv.95",
      template:
        "Increases Attack against enemies afflicted with [[Poison (skill inflicting status ailment)",
      calc: (lvl) => lvl * 0.01,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Charge (Dagger)",
      maxLvl: 10,
      req: "Dagger Lv.100",
      template: "Increases damage dealt with Dark element+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bloody Assault",
      maxLvl: 10,
      req: "Dagger Lv.105",
      template:
        "Increases player's Attack when attacking enemies afflicted with [[Bleed (skill inflicting status ailment)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
  ],
  Axe: [
    {
      name: "Axe Training",
      maxLvl: 10,
      req: "2H Axe Lv.1",
      template: "Increases regular attack when an axe is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Body's Enhancement",
      maxLvl: 10,
      req: "2H Axe Lv.1",
      template: "Increases Attack when an axe is equipped+{val}",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Axe's Blow",
      maxLvl: 10,
      req: "2H Axe Lv.1",
      template:
        "After hitting an enemy using Switch, buffs the player which makes him take less damage for +{val} seconds.",
      calc: (lvl) => lvl * 2.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Basic Stance",
      maxLvl: 10,
      req: "2H Axe Lv.1",
      template:
        "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fighting Spirit",
      maxLvl: 10,
      req: "2H Axe Lv.5",
      template: "Increases switch gauge fill rate+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Axe Proficiency",
      maxLvl: 10,
      req: "2H Axe Lv.5",
      template:
        "Increases axe skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Mark of Mercenary",
      maxLvl: 10,
      req: "2H Axe Lv.10",
      template: "Reduces SP cost of all Axe Skill Records+{val}",
      calc: (lvl) => lvl * 15,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Axe Control Improvement",
      maxLvl: 10,
      req: "2H Axe Lv.10",
      template: "Decreases SP cost needed for stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Battle Instinct",
      maxLvl: 10,
      req: "2H Axe Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Instinct",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 15, Mark of Mercenary - Level 1",
      template: "Max HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Cleave",
      maxLvl: 10,
      req: "2H Axe Lv.20",
      template:
        "Increases Attack against an enemy with more than +{val}% of its max HP.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Weapon Knowledge",
      maxLvl: 10,
      req: "2H Axe Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Kongou",
      maxLvl: 10,
      req: "2H Axe Lv.30",
      template:
        "Decreases damage taken if it's more than +{val}% of character's max HP.",
      calc: (lvl) => [30, 35, 40, 45, 50, 55, 60, 65, 70, 75][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Axe's Secret",
      maxLvl: 10,
      req: "2H Axe Lv.35",
      template: "Increases Attack when an axe is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Sword Skill Mastery",
      maxLvl: 10,
      req: "2H Axe Lv.40",
      template:
        "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Overcharge I (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.45",
      template: 'Allows charging "Switch" meter to third level+{val}',
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.50",
      template: "Increases Attack when using Fire element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.50",
      template: "Increases Attack when using Water element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Wind Glow (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.50",
      template: "Increases Attack when using Wind element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Earth Glow (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.50",
      template: "Increases Attack when using Earth element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.50",
      template: "Increases Attack when using Holy element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Glow (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.50",
      template: "Increases Attack when using Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Survival Expertise (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Blunt Proficiency (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.60",
      template: "Increases damage dealt to enemies weak to blunt attacks+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Strong Defense Expertise (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Powerful Power",
      maxLvl: 10,
      req: "2H Axe Lv.70",
      template: "Increases Attack in proportion to remaining HP+{val}",
      calc: (lvl) =>
        [210, 220, 230, 240, 250, 260, 270, 280, 290, 300][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fierce Attack Expertise (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Reversal Enhancement",
      maxLvl: 10,
      req: "2H Axe Lv.80",
      template:
        "When receiving a hit, there's a chance to obtain a buff which increases Attack+{val}",
      calc: (lvl) =>
        [15.5, 16, 16.5, 17, 17.5, 18, 18.5, 19, 19.5, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dynamic Assault",
      maxLvl: 10,
      req: "2H Axe Lv.85",
      template:
        'Increases player\'s Attack against enemies in "Break" state+{val}',
      calc: (lvl) => lvl * 0.25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Rise (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.90",
      template: "Increases Attack when using Earth element+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Single Sword Skill Mastery (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.95",
      template: "Increases power of single Sword Skills by +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Charge (2H Axe)",
      maxLvl: 10,
      req: "2H Axe Lv.100",
      template: "Increases damage dealt with Earth element+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Powerful Attack",
      maxLvl: 10,
      req: "2H Axe Lv.105",
      template:
        "Increases player's Attack proportionally to the percentage of remaining HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Overcharge I",
      maxLvl: 1,
      req: "2H Axe Proficiency - Level 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Expertise",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 55 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Strong Defense Expertise",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 65 ,  Survival Expertise (2H Axe) - Level 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fierce Attack Expertise",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 75 ,  Strong Defense Expertise (2H Axe) - Level 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Rise",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 90 ,  Dynamic Assault - Level 5",
      template: "Increases Attack when using Earth element. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Charge",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 100 ,  Single Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases damage dealt with Earth element. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Single Sword Skill Mastery",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 95 ,  Dynamic Assault - Level 5",
      template:
        "Increases power of single Sword Skills by +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 50 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases Attack when using Fire element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Glow",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 50 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases Attack when using Water element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Glow",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 50 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases Attack when using Wind element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Glow",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 50 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases Attack when using Earth element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shine Glow",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 50 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases Attack when using Holy element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dark Glow",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 50 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases Attack when using Dark element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Advancing Sword Technique",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 50 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template: "Increases power of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Breaking Fundamentals",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 50 ,  Sword Skill Mastery (2H Axe) - Level 5",
      template:
        "Increases Break value of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Bonded Chain Attack",
      maxLvl: 10,
      req: "2H Axe Proficiency - Level 110 ,  Powerful Attack - Level 5",
      template:
        "Increases power of Sword Skills used on Switch by +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Spear: [
    {
      name: "Spear Training",
      maxLvl: 10,
      req: "2H Spear Lv.1",
      template: "Increases regular attack when a spear is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Stampede",
      maxLvl: 10,
      req: "2H Spear Lv.1",
      template:
        "Increases Attack for +{val} seconds after stepping, when a spear is equipped.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Spear's Blow",
      maxLvl: 10,
      req: "2H Spear Lv.1",
      template:
        "After hitting an enemy using Switch, buffs the player which increases his Critical Rate for +{val} seconds.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Basic Stance",
      maxLvl: 10,
      req: "2H Spear Lv.1",
      template:
        "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Gale",
      maxLvl: 10,
      req: "2H Spear Lv.5",
      template: "Shortens cooldown time for Spear Skill Records+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Spear Proficiency",
      maxLvl: 10,
      req: "2H Spear Lv.5",
      template:
        "Increases spear skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Mark of Knight",
      maxLvl: 10,
      req: "2H Spear Lv.10",
      template: "Restores SP for every enemy defeated+{val}",
      calc: (lvl) => lvl * 3,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Spear Control Improvement",
      maxLvl: 10,
      req: "2H Spear Lv.10",
      template: "Decreases SP cost needed for stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Battle Instinct",
      maxLvl: 10,
      req: "2H Spear Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Instinct",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 15, Mark of Knight - Level 1",
      template: "Max HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Fang",
      maxLvl: 10,
      req: "2H Spear Lv.20",
      template:
        "Increases Attack against enemies with a status ailment when a spear is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Weapon Knowledge",
      maxLvl: 10,
      req: "2H Spear Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Spear Dance",
      maxLvl: 10,
      req: "2H Spear Lv.30",
      template: "Description pending (wiki stub)",
      calc: (lvl) => 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Spear's Secret",
      maxLvl: 10,
      req: "2H Spear Lv.35",
      template: "Increases Attack when a spear is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Sword Skill Mastery",
      maxLvl: 10,
      req: "2H Spear Lv.40",
      template:
        "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Overcharge I (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.45",
      template: 'Allows charging "Switch" meter to third level+{val}',
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.50",
      template: "Increases Attack when using Fire element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.50",
      template: "Increases Attack when using Water element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Wind Glow (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.50",
      template: "Increases Attack when using Wind element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Earth Glow (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.50",
      template: "Increases Attack when using Earth element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.50",
      template: "Increases Attack when using Holy element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Glow (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.50",
      template: "Increases Attack when using Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Survival Expertise (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Thrust Proficiency (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.60",
      template:
        "Increases damage dealt to enemies weak to thrust attacks+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Strong Defense Expertise (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Marking Switch",
      maxLvl: 10,
      req: "2H Spear Lv.70",
      template:
        "When hitting an enemy using Switch, has a chance to inflict enemy with [[Stigma Debuff]] for +{val} seconds.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fierce Attack Expertise (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Pursuit of the Weak",
      maxLvl: 10,
      req: "2H Spear Lv.80",
      template: "Increases Attack against debuffed enemies+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Overall Sword Skill Mastery (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.85",
      template:
        "Increases power of Sword Skills in active slots as well as these which are part of Connect Chain by +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Rise (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.90",
      template: "Increases Attack when using Wind element+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Destruction Art",
      maxLvl: 10,
      req: "2H Spear Lv.95",
      template: "Increases break efficiency+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Charge (2H Spear)",
      maxLvl: 10,
      req: "2H Spear Lv.100",
      template: "Increases damage dealt with Wind element+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Armor Decay Switch",
      maxLvl: 10,
      req: "2H Spear Lv.105",
      template:
        "When hitting an enemy using Switch, has a chance to inflict enemy with [[Armor Decay Debuff]] for +{val} seconds.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Overcharge I",
      maxLvl: 1,
      req: "2H Spear Proficiency - Level 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Expertise",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 55 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Strong Defense Expertise",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 65 ,  Survival Expertise (2H Spear) - Level 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fierce Attack Expertise",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 75 ,  Strong Defense Expertise (2H Spear) - Level 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Rise",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 90 ,  Overall Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases Attack when using Wind element. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Charge",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 100 ,  Destruction Art - Level 5",
      template: "Increases damage dealt with Wind element. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Overall Sword Skill Mastery",
      maxLvl: 10,
      req: "Spear Proficiency - Level 85 ,  Fierce Attack Expertise (2H Spear) - Level 5",
      template:
        "Increases power of Sword Skills in active slots as well as these which are part of Connect Chain by +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 50 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases Attack when using Fire element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Glow",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 50 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases Attack when using Water element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Glow",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 50 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases Attack when using Wind element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Glow",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 50 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases Attack when using Earth element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shine Glow",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 50 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases Attack when using Holy element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dark Glow",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 50 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases Attack when using Dark element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Advancing Sword Technique",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 50 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template: "Increases power of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Breaking Fundamentals",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 50 ,  Sword Skill Mastery (2H Spear) - Level 5",
      template:
        "Increases Break value of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Bonded Chain Attack",
      maxLvl: 10,
      req: "2H Spear Proficiency - Level 110 ,  Armor Decay Switch - Level 1",
      template:
        "Increases power of Sword Skills used on Switch by +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Bow: [
    {
      name: "Bow Training",
      maxLvl: 10,
      req: "Bow Lv.1",
      template: "Increases regular attack when a bow is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Pierce",
      maxLvl: 10,
      req: "Bow Lv.1",
      template: "Increases Attack when HP is above +{val}%",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Flash",
      maxLvl: 10,
      req: "Bow Lv.1",
      template:
        "After hitting an enemy using Switch, buffs the player which increases his Critical Rate for +{val} seconds.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Basic Stance",
      maxLvl: 10,
      req: "Bow Lv.1",
      template:
        "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Precise Shot",
      maxLvl: 10,
      req: "Bow Lv.5",
      template:
        "Increases damage dealt to enemies weak to thrust attacks+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bow Proficiency",
      maxLvl: 10,
      req: "Bow Lv.5",
      template:
        "Increases bow skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Proof of Archer",
      maxLvl: 10,
      req: "Bow Lv.10",
      template:
        "Shortens the time needed to charge up some of the Bow Skill Records+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Bow Control Improvement",
      maxLvl: 10,
      req: "Bow Lv.10",
      template: "Decreases SP cost needed for stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Battle Instinct",
      maxLvl: 10,
      req: "Bow Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Instinct",
      maxLvl: 10,
      req: "Bow Proficiency - Level 15, Proof of Archer - Level 1",
      template: "Max HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Predator's Keen Eye",
      maxLvl: 10,
      req: "Bow Lv.20",
      template:
        "Increases Attack against an enemy with less than +{val}% of its max HP.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Weapon Knowledge",
      maxLvl: 10,
      req: "Bow Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Crescent Moon",
      maxLvl: 10,
      req: "Bow Lv.30",
      template:
        "After hitting an enemy with a bow skill on Switch, activates a buff which for +{val} seconds (or until the player takes damage) increases Attack by +{val}%.",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bow's Secret",
      maxLvl: 10,
      req: "Bow Lv.35",
      template: "Increases Attack when a bow is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Sword Skill Mastery",
      maxLvl: 10,
      req: "Bow Lv.40",
      template:
        "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Overcharge I (Bow)",
      maxLvl: 10,
      req: "Bow Lv.45",
      template: 'Allows charging "Switch" meter to third level+{val}',
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow (Bow)",
      maxLvl: 10,
      req: "Bow Lv.50",
      template: "Increases Attack when using Fire element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Bow)",
      maxLvl: 10,
      req: "Bow Lv.50",
      template: "Increases Attack when using Water element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Wind Glow (Bow)",
      maxLvl: 10,
      req: "Bow Lv.50",
      template: "Increases Attack when using Wind element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Earth Glow (Bow)",
      maxLvl: 10,
      req: "Bow Lv.50",
      template: "Increases Attack when using Earth element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (Bow)",
      maxLvl: 10,
      req: "Bow Lv.50",
      template: "Increases Attack when using Holy element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Glow (Bow)",
      maxLvl: 10,
      req: "Bow Lv.50",
      template: "Increases Attack when using Dark element+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Survival Expertise (Bow)",
      maxLvl: 10,
      req: "Bow Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Thrust Proficiency (Bow)",
      maxLvl: 10,
      req: "Bow Lv.60",
      template:
        "Increases damage dealt to enemies weak to thrust attacks+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Strong Defense Expertise (Bow)",
      maxLvl: 10,
      req: "Bow Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Surprise Strike",
      maxLvl: 10,
      req: "Bow Lv.70",
      template:
        "Increases Attack against enemies which are not targetting the player+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fierce Attack Expertise (Bow)",
      maxLvl: 10,
      req: "Bow Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Hard Break (Bow)",
      maxLvl: 10,
      req: "Bow Lv.80",
      template:
        'Increases player\'s Attack against enemies in "Break" state+{val}',
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Reverse Strike",
      maxLvl: 10,
      req: "Bow Lv.85",
      template: "Increases Attack based on percentage of remaining HP",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Rise (Bow)",
      maxLvl: 10,
      req: "Bow Lv.90",
      template: "Increases Attack when using Holy element+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Single Sword Skill Mastery (Bow)",
      maxLvl: 10,
      req: "Bow Lv.95",
      template: "Increases power of single Sword Skills by +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shine Charge (Bow)",
      maxLvl: 10,
      req: "Bow Lv.100",
      template: "Increases damage dealt with Holy element+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Reverse Assault",
      maxLvl: 10,
      req: "Bow Lv.105",
      template:
        "Increases player's Attack proportionally to the percentage of lost HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Overcharge I",
      maxLvl: 1,
      req: "Bow Proficiency - Level 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Survival Expertise",
      maxLvl: 10,
      req: "Bow Proficiency - Level 55 ,  Sword Skill Mastery (Bow) - Level 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Strong Defense Expertise",
      maxLvl: 10,
      req: "Bow Proficiency - Level 65 ,  Survival Expertise (Bow) - Level 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fierce Attack Expertise",
      maxLvl: 10,
      req: "Bow Proficiency - Level 75 ,  Strong Defense Expertise (Bow) - Level 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Hard Break",
      maxLvl: 10,
      req: "Bow Proficiency - Level 80 ,  Fierce Attack Expertise (Bow) - Level 5",
      template:
        "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shine Rise",
      maxLvl: 10,
      req: "Bow Proficiency - Level 90 ,  Reverse Strike - Level 5",
      template: "Increases Attack when using Holy element. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shine Charge",
      maxLvl: 10,
      req: "Bow Proficiency - Level 100 ,  Single Sword Skill Mastery (Bow) - Level 5",
      template: "Increases damage dealt with Holy element. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Single Sword Skill Mastery",
      maxLvl: 10,
      req: "Bow Proficiency - Level 95 ,  Reverse Strike - Level 5",
      template:
        "Increases power of single Sword Skills by +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flame Glow",
      maxLvl: 10,
      req: "Bow Proficiency - Level 50 ,  Sword Skill Mastery (Bow) - Level 5",
      template: "Increases Attack when using Fire element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Glow",
      maxLvl: 10,
      req: "Bow Proficiency - Level 50 ,  Sword Skill Mastery (Bow) - Level 5",
      template: "Increases Attack when using Water element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Wind Glow",
      maxLvl: 10,
      req: "Bow Proficiency - Level 50 ,  Sword Skill Mastery (Bow) - Level 5",
      template: "Increases Attack when using Wind element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Earth Glow",
      maxLvl: 10,
      req: "Bow Proficiency - Level 50 ,  Sword Skill Mastery (Bow) - Level 5",
      template: "Increases Attack when using Earth element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shine Glow",
      maxLvl: 10,
      req: "Bow Proficiency - Level 50 ,  Sword Skill Mastery (Bow) - Level 5",
      template: "Increases Attack when using Holy element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dark Glow",
      maxLvl: 10,
      req: "Bow Proficiency - Level 50 ,  Sword Skill Mastery (Bow) - Level 5",
      template: "Increases Attack when using Dark element. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Advancing Sword Technique",
      maxLvl: 10,
      req: "Bow Proficiency - Level 50 ,  Sword Skill Mastery (Bow) - Level 5",
      template: "Increases power of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Breaking Fundamentals",
      maxLvl: 10,
      req: "Bow Proficiency - Level 50 ,  Sword Skill Mastery (Bow) - Level 5",
      template:
        "Increases Break value of Sword Skills by +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Bonded Chain Attack",
      maxLvl: 10,
      req: "Bow Proficiency - Level 110 ,  Reverse Assault - Level 5",
      template:
        "Increases power of Sword Skills used on Switch by +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Shield: [
    {
      name: "Shield Training",
      maxLvl: 10,
      req: "Shield Lv.1",
      template: "Increases Defense when a shield is equipped+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resist",
      maxLvl: 10,
      req: "Shield Lv.1",
      template:
        "Increases Resistance against damaging Status Ailments when a shield is equipped+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Protect",
      maxLvl: 10,
      req: "Shield Lv.1",
      template:
        "After hitting an enemy using Switch, buffs the player which increases his Defense for +{val} seconds.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Decisive Guard",
      maxLvl: 10,
      req: "Shield Lv.5",
      template:
        "Reduces damage taken by a percentage dependant on a number of Shield Skill Records equipped+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Reflection",
      maxLvl: 10,
      req: "Shield Lv.10",
      template: "Reflects a part of damage taken back to an enemy+{val}",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Survival Instinct",
      maxLvl: 10,
      req: "Shield Proficiency - Level 15, Reflection - Level 1",
      template: "Max HP +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Vitality",
      maxLvl: 10,
      req: "Shield Lv.20",
      template: "Increases flinch resistance when a shield is equipped+{val}",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Shield Knowledge",
      maxLvl: 10,
      req: "Shield Lv.25",
      template: "Passively increases the player's Defense+{val}",
      calc: (lvl) =>
        [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Transcendent",
      maxLvl: 10,
      req: "Shield Lv.30",
      template: "Increases damage done with shield skill records+{val}",
      calc: (lvl) => [30, 35, 40, 45, 50][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shield Healing",
      maxLvl: 10,
      req: "Shield Lv.55",
      template: "Recovers some amount of HP every +{val} seconds.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Recovery Expertise",
      maxLvl: 10,
      req: "Shield Lv.60",
      template: "Passively increases effectiveness of healing items+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Body Enhancement (Shield)",
      maxLvl: 10,
      req: "Shield Lv.65",
      template: "Max HP +{val}",
      calc: (lvl) => lvl * 50,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "Field Heal",
      maxLvl: 10,
      req: "Shield Lv.70",
      template: "Passively increases effectiveness of healing plants+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Powerful Blow",
      maxLvl: 10,
      req: "Shield Lv.75",
      template: "Increases damage against enemies weak to blunt+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Physical Encouragement (Shield)",
      maxLvl: 10,
      req: "Shield Lv.80",
      template: "Passively increases player's HP+{val}",
      calc: (lvl) =>
        [525, 550, 575, 600, 625, 650, 675, 700, 725, 750][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Powerful Slash",
      maxLvl: 10,
      req: "Shield Lv.85",
      template: "Increases damage against enemies weak to slash+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    ,
    {
      name: "Physical Encouragement",
      maxLvl: 10,
      req: "Shield Proficiency - Level 80 ,  Powerful Blow - Level 5",
      template: "Passively increases player's HP. +{val}",
      calc: (lvl) => 500 + lvl * 25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Powerful Thrust",
      maxLvl: 10,
      req: "Shield Proficiency - Level 90 ,  Powerful Slash - Level 5",
      template: "Increases damage against enemies weak to thrust. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
  ],
};
