window.masteryData = {
  Sword: [
    {
      name: "Entraînement à l'épée",
      maxLvl: 10,
      req: "Épée 1H Lv.1",
      template: "When 1h Sword is equipped, normal attack's damage +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Chevalerie",
      maxLvl: 10,
      req: "Épée 1H Lv.1",
      template: "Augmente l'attaque et la défense lorsqu'une épée est équipée de +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "flat_atk_def",
      active: true,
    },
    {
      name: "Sword's Blow",
      maxLvl: 10,
      req: "Épée 1H Lv.1",
      template: "After hitting an enemy with Switch, buffs the player's Attack and Defense for 8 seconds by +{val}%",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Position de base",
      maxLvl: 10,
      req: "Épée 1H Lv.1",
      template: "Ajoute +{val} dégâts supplémentaires à l'ennemi lors de l'attaque (toutes les armes)",
      calc: (lvl) => lvl * 5,
      bonusType: "flat_damage",
      active: true,
    },
    {
      name: "Frappe complète",
      maxLvl: 10,
      req: "Entraînement à l'épée Lv.5",
      template: "Lorsque l'épée 1H est équipée, dégâts infligés aux ennemis faibles à tranchants +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "Maîtrise de l'épée",
      maxLvl: 10,
      req: "Entraînement à l'épée Lv.5, Frappe complète Lv.5",
      template: "Lorsque l'épée 1H est équipée, puissance de la compétence de l'épée + {val} %",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Marque du guerrier",
      maxLvl: 1,
      req: "Épée 1H Lv.10, Frappe complète Lv.5",
      template: "Lorsque l'épée 1H est équipée, restaurez + {val} % de HP en tuant",
      calc: (lvl) => lvl * 2,
      bonusType: "healing_percent",
      active: true,
    },
    {
      name: "Amélioration du contrôle de l'épée",
      maxLvl: 1,
      req: "Épée 1H Lv.10, position de base Lv.5",
      template: "Lorsque l'épée 1H est équipée, le coût en SP - {val} pour le pas",
      calc: (lvl) => lvl * 1,
      bonusType: "step_reduction",
      active: true,
    },
    {
      name: "Instinct de combat",
      maxLvl: 10,
      req: "Épée 1H Lv.10, position de base Lv.5",
      template: "Attaque +{val} (Toutes les armes)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Instinct de survie",
      maxLvl: 10,
      req: "Épée 1H Lv.15, Marque du Guerrier Lv.1",
      template: "HP max +{val}% (toutes les armes)",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Combinaison",
      maxLvl: 10,
      req: "Épée 1H Lv.20, Instinct de Survie Lv.5",
      template: "Lorsque l'épée 1H est équipée, dégâts de commutation + {val} %",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Connaissance des armes",
      maxLvl: 10,
      req: "Épée 1H Lv.25, Combinaison Lv.5",
      template: "Attaque +{val}% (toutes les armes)",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.699999999999999, 5][
          lvl - 1
        ] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Changer de charge",
      maxLvl: 10,
      req: "Épée 1H Lv.30, Connaissance des armes Lv.5",
      template: "Lorsque l'épée 1H est équipée, récupérez + {val} SP lors de l'utilisation de la compétence de changement",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "sp_recovery_flat",
      active: true,
    },
    {
      name: "Sword's Secret",
      maxLvl: 10,
      req: "Épée 1H Lv.35, Charge de commutation Lv.1",
      template: "Lorsque l'épée 1H est équipée, Attaque +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée",
      maxLvl: 10,
      req: "Épée 1H Lv.40, Connaissance des armes Lv.10",
      template: "Puissance de compétence d'épée + {val} % (efficace avec toutes les armes)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "ss_power",
      active: true,
    },
    {
      name: "Surcharge I (Épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.45",
      template: "La jauge de commutation se chargera jusqu'au troisième niveau lorsque l'épée 1H est équipée. Dégâts +200% lors de l'utilisation du commutateur au troisième niveau. ",
      calc: (lvl) => 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Flamme Lueur (Épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.50, Maîtrise des compétences d'épée Lv.5",
      template: "Attaque + {val} % en attaquant avec l'élément Feu et en équipant une épée 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.50, Maîtrise des compétences d'épée Lv.5",
      template: "Attaque + {val} % en attaquant avec l'élément Eau et en équipant une épée 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur du vent (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.50, Maîtrise des compétences d'épée Lv.5",
      template: "Attaque + {val} % en attaquant avec l'élément Vent et en équipant une épée 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur de la Terre (Épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.50, Maîtrise des compétences d'épée Lv.5",
      template: "Attaque + {val} % en attaquant avec l'élément Terre et en équipant une épée 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (Épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.50, Maîtrise des compétences d'épée Lv.5",
      template: "Attaque + {val} % en attaquant avec Holy Element et en équipant une épée 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur sombre (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.50, Maîtrise des compétences d'épée Lv.5",
      template: "Attaque +{val}% en attaquant avec Dark Element et en équipant une épée 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise de survie (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.55, Maîtrise des compétences d'épée Lv.5",
      template: "HP +{val} en équipant une épée 1H",
      calc: (lvl) => lvl * 100,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "Maîtrise du Slash (Épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.60, Expertise de survie (Épée 1H) Lv.5",
      template: "Lorsque l'épée 1H est équipée, les dégâts infligés aux ennemis sont faibles jusqu'à trancher +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "Forte expertise en défense (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.65, Expertise de survie (Épée 1H) Lv.5",
      template: "Défense +{val} en équipant une épée 1H",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "def_flat",
      active: true,
    },
    {
      name: "Garde-brûlure",
      maxLvl: 10,
      req: "Épée 1H Lv.70, forte expertise en défense (Épée 1H) Lv.5",
      template: "Lorsque l'épée 1H est équipée, dégâts de brûlure -{val}",
      calc: (lvl) =>
        [-4.5, -4, -3.5, -3, -2.5, -2, -1.5, -1, -0.5, 0][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise en attaque féroce (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.75, forte expertise en défense (Épée 1H) Lv.5",
      template: "Attaque +{val} en équipant une épée 1H",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Coup dur (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.80, Expertise en attaque féroce (Épée 1H) Lv.5",
      template: "Lorsque 1H Sword est équipé, attaquez +{val} lors de l'utilisation de Break",
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Maîtrise de la compétence d'une seule épée (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.85, Expertise en attaque féroce (Épée 1H) Lv.5",
      template: "Puissance de compétence d'épée (simple) + {val} % lors de l'équipement d'une épée 1H",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "skill_power",
      active: true,
    },
    {
      name: "Flamme Rise (Épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.90, Expertise en attaque féroce (Épée 1H) Lv.5",
      template: "Lorsque vous équipez une épée 1H, attaquez +{val} lorsque vous utilisez l'élément Feu",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.95, Maîtrise des compétences d'épée unique (Épée 1H) Lv.5",
      template: "Dégâts des compétences d'épée + {val} % (efficace avec toutes les armes)",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Charge de flamme (épée 1H)",
      maxLvl: 10,
      req: "Épée 1H Lv.100, maîtrise des compétences d'épée (épée 1H) Lv.5",
      template: "Lorsque vous équipez une épée 1H, dégâts de l'élément feu + {val} %",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "damage_percent_fire",
      active: true,
    },
    {
      name: "Garde de l'adversité",
      maxLvl: 10,
      req: "Épée 1H Lv.105, Charge de flamme (Épée 1H) Lv.5",
      template: "Défense + {val} lorsque vous équipez une épée 1H et que les PV sont de 25 % ou moins",
      calc: (lvl) => lvl * 10,
      bonusType: "def_flat",
      active: true,
    },
    ,
    {
      name: "Surcharge I",
      maxLvl: 1,
      req: "Maîtrise de l'épée 1H - Niveau 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise de survie",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 55, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Forte expertise en matière de défense",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 65, Expertise en survie (Épée 1H) - Niveau 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise en attaque féroce",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 75, Forte expertise en défense (Épée 1H) - Niveau 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Maîtrise de la compétence d'une seule épée",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 85, Expertise en attaque féroce (Épée 1H) - Niveau 5",
      template: "Augmente la puissance des compétences d'épée unique de + {val} %",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 95, Maîtrise des compétences d'épée unique (Épée 1H) - Niveau 5",
      template: "Augmente la puissance des compétences d'épée de +{val} %",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Pause dure",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 80, Expertise en attaque féroce (Épée 1H) - Niveau 5",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Montée des flammes",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 90, Maîtrise des compétences d'épée unique (Épée 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge de flamme",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 100, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente les dégâts infligés par l'élément Feu. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme Lueur",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 50, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqualueur",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 50, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur du vent",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 50, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur de la Terre",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 50, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briller Éclat",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 50, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur sombre",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 50, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Position appliquée",
      maxLvl: 10,
      req: "Libérer le cristal (M) x 1",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 125,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Position développée",
      maxLvl: 10,
      req: "Cristal de libération (L) x 3",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Avancement de la technique de l'épée",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 50, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente la puissance des compétences d'épée de +{val} %",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briser les fondamentaux",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 50, Maîtrise des compétences d'épée (Épée 1H) - Niveau 5",
      template: "Augmente la valeur de rupture des compétences d'épée de + {val} %",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Attaque en chaîne liée",
      maxLvl: 10,
      req: "Maîtrise de l'épée 1H - Niveau 110, Adversity Guard - Niveau 5",
      template: "Augmente la puissance des compétences d'épée utilisées sur Switch de + {val} %",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Rapier: [
    {
      name: "Entraînement à la rapière",
      maxLvl: 10,
      req: "Rapière 1H Lv.1",
      template: "Augmente les dégâts d'une attaque régulière lorsqu'une rapière 1H est équipée + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Attaque en série",
      maxLvl: 10,
      req: "Rapière 1H Lv.1",
      template: "Augmente l'attaque en fonction du nombre de HIT infligés dans un seul combo, lorsque la rapière est équipée + {val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Rapier's Blow",
      maxLvl: 10,
      req: "Rapière 1H Lv.1",
      template: "Après avoir touché un ennemi à l'aide de Switch, le joueur reçoit un buff qui augmente son taux critique pendant +{val} secondes.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Position de base",
      maxLvl: 10,
      req: "Rapière 1H Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Cibler le point faible",
      maxLvl: 10,
      req: "Rapière 1H Lv.5",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques de poussée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise de la rapière",
      maxLvl: 10,
      req: "Rapière 1H Lv.5",
      template: "Increases rapier skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Marque de l'épéiste",
      maxLvl: 10,
      req: "Rapière 1H Lv.10",
      template: "Restaure SP lors d'un coup critique+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Amélioration du contrôle des rapières",
      maxLvl: 10,
      req: "Rapière 1H Lv.10",
      template: "Diminue le coût SP nécessaire pour le stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinct de combat",
      maxLvl: 10,
      req: "Rapière 1H Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinct de survie",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 15, Marque de l'épéiste - Niveau 1",
      template: "PV max +{val} %",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Vitesse de l'éclair",
      maxLvl: 10,
      req: "Rapière 1H Lv.20",
      template: "Augmente les dégâts critiques lorsque le joueur est équipé d'une rapière + {val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Connaissance des armes",
      maxLvl: 10,
      req: "Rapière 1H Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Météore",
      maxLvl: 10,
      req: "Rapière 1H Lv.30",
      template: "Augmente le taux critique pendant +{val} secondes après le pas, lorsqu'une rapière est équipée.",
      calc: (lvl) => [20, 25, 30, 35, 40, 45, 50, 55, 60, 65][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rapier's Secret",
      maxLvl: 10,
      req: "Rapière 1H Lv.35",
      template: "Augmente l'attaque lorsqu'une rapière est équipée + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée",
      maxLvl: 10,
      req: "Rapière 1H Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Surcharge I (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme Lueur (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur du vent (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Earth Glow (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur sombre (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise de survie (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Compétence en poussée (rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Niv.60",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques de poussée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Forte expertise en défense (1H Rapière)",
      maxLvl: 10,
      req: "Rapière 1H Niv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Assaut de points vitaux",
      maxLvl: 10,
      req: "Rapière 1H Lv.70",
      template: "Augmente l'attaque pendant que le buff qui augmente les dégâts critiques est en vigueur + {val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise en attaque féroce (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Coup de point vital",
      maxLvl: 10,
      req: "Rapière 1H Niv.80",
      template: "Augmente les dégâts critiques lors de l'utilisation de Skills+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Frappe précise",
      maxLvl: 10,
      req: "Rapière 1H Niv.85",
      template: "Augmente le taux critique lors de l'utilisation des compétences de +{val} %",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Rise (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Lv.90",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau + {val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Frappe élaborée",
      maxLvl: 10,
      req: "Rapière 1H Lv.95",
      template: "Après avoir touché un ennemi à l'aide de Switch, applique un buff au joueur, qui augmente ses dégâts critiques pendant +{val} secondes.",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Charge (Rapière 1H)",
      maxLvl: 10,
      req: "Rapière 1H Niv.100",
      template: "Augmente les dégâts infligés par l'élément Eau+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Frappe de vulnérabilité",
      maxLvl: 10,
      req: "Rapière 1H Lv.105",
      template: "Increases player's Attack when Critical Rate buff is active+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Surcharge I",
      maxLvl: 1,
      req: "Maîtrise de la rapière 1H - Niveau 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise de survie",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 55, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Forte expertise en matière de défense",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 65, Expertise en survie (Rapière 1H) - Niveau 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise en attaque féroce",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 75, Forte expertise en défense (Rapière 1H) - Niveau 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Rise",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 90, Frappe précise - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge aquatique",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 100, Frappe élaborée - Niveau 5",
      template: "Augmente les dégâts infligés par l'élément Eau. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme Lueur",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 50, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqualueur",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 50, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur du vent",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 50, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur de la Terre",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 50, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briller Éclat",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 50, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur sombre",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 50, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Avancement de la technique de l'épée",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 50, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Augmente la puissance des compétences d'épée de +{val} %",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briser les fondamentaux",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 50, Maîtrise des compétences d'épée (Rapière 1H) - Niveau 5",
      template: "Augmente la valeur de rupture des compétences d'épée de + {val} %",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Attaque en chaîne liée",
      maxLvl: 10,
      req: "Maîtrise de la rapière 1H - Niveau 110, Frappe de vulnérabilité - Niveau 5",
      template: "Augmente la puissance des compétences d'épée utilisées sur Switch de + {val} %",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Club: [
    {
      name: "Entraînement des clubs",
      maxLvl: 10,
      req: "Club 1H Niv.1",
      template: "Augmente les dégâts des attaques régulières lorsqu'une masse est équipée + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Connaissances pour les médicaments",
      maxLvl: 10,
      req: "Club 1H Niv.1",
      template: "Augmente la quantité de PV restaurés par les objets de guérison lorsque le club est équipé + {val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Blow",
      maxLvl: 10,
      req: "Club 1H Niv.1",
      template: "Après avoir touché un ennemi à l'aide de Switch, le joueur et son groupe reçoivent un buff qui réduit les dégâts qu'ils subissent pendant +{val} secondes.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Position de base",
      maxLvl: 10,
      req: "Club 1H Niv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Coup dur",
      maxLvl: 10,
      req: "Club 1H Niv.5",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques contondantes+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Compétence du club",
      maxLvl: 10,
      req: "Club 1H Niv.5",
      template: "Increases club skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Marque de défense",
      maxLvl: 10,
      req: "Club 1H Niv.10",
      template: "Restaure les HP toutes les +{val} secondes.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Amélioration du contrôle des clubs",
      maxLvl: 10,
      req: "Club 1H Niv.10",
      template: "Diminue le coût SP nécessaire pour le stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinct de combat",
      maxLvl: 10,
      req: "Club 1H Niv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinct de survie",
      maxLvl: 10,
      req: "Maîtrise du club 1H - Niveau 15, Marque de défense - Niveau 1",
      template: "PV max +{val} %",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Brise armure",
      maxLvl: 10,
      req: "Club 1H Niv.20",
      template: "Chaque attaque a une chance d'appliquer un débuff de défense à l'ennemi attaqué pendant +{val} secondes.",
      calc: (lvl) => [16, 17, 18, 19, 20, 21, 22, 23, 24, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Connaissance des armes",
      maxLvl: 10,
      req: "Club 1H Niv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Casse d'arme",
      maxLvl: 10,
      req: "Club 1H Niv.30",
      template: "Chaque attaque a une chance d'appliquer un débuff d'attaque sur l'ennemi attaqué pendant +{val} secondes.",
      calc: (lvl) => [27, 29, 31, 33, 35, 37, 39, 41, 43, 45][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Secret",
      maxLvl: 10,
      req: "Club 1H Niv.35",
      template: "Augmente l'attaque lorsqu'une masse est équipée + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée",
      maxLvl: 10,
      req: "Club 1H Niv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Surcharge I (1H Club)",
      maxLvl: 10,
      req: "Club 1H Niv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme Lueur (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur du vent (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur de la Terre (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Brillance Éclat (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur sombre (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise de Survie (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Compétence émoussée (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.60",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques contondantes+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Forte expertise en défense (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Frappe sculptée",
      maxLvl: 10,
      req: "Club 1H Niv.70",
      template: "Augmente l'attaque contre les ennemis affaiblis par [[Mark Debuff",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise en attaque féroce (1H Club)",
      maxLvl: 10,
      req: "Club 1H Niv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sauvegarde puissante",
      maxLvl: 10,
      req: "Club 1H Niv.80",
      template: "Lorsque vous frappez un ennemi à l'aide de Switch, améliore les membres du groupe en augmentant leurs dégâts de faiblesse contondante + {val}",
      calc: (lvl) => lvl * 0.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Haute Défense",
      maxLvl: 10,
      req: "Club 1H Niv.85",
      template: "Augmente la défense lorsque le joueur a un buff actif",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lever du vent (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.90",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Encouragements",
      maxLvl: 10,
      req: "Club 1H Niv.95",
      template: "Après avoir touché un ennemi à l'aide de Switch, le joueur et son groupe reçoivent un buff qui augmente leur attaque pendant +{val} secondes.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge de vent (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Niv.100",
      template: "Augmente les dégâts infligés par l'élément Vent+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Coup gravé",
      maxLvl: 10,
      req: "Club 1H Niv.105",
      template: "Augmente l'attaque contre les ennemis affaiblis par [[Mark Debuff",
      calc: (lvl) => lvl * 20,
      bonusType: "atk_percent",
      active: true,
    },
  ],
  Dagger: [
    {
      name: "Entraînement au poignard",
      maxLvl: 10,
      req: "Dague Lv.1",
      template: "Augmente l'attaque régulière lorsqu'un poignard est équipé+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Représailles",
      maxLvl: 10,
      req: "Dague Lv.1",
      template: "Augmente l'attaque lorsque les PV sont inférieurs à +{val} %",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Coup de poignard",
      maxLvl: 10,
      req: "Dague Lv.1",
      template: "Increases damage dealt to an enemy which isn't focused on the player",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Position de base",
      maxLvl: 10,
      req: "Dague Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lame cruelle",
      maxLvl: 10,
      req: "Dague Lv.5",
      template: "Augmente l'attaque contre les ennemis souffrant d'une maladie de statut lorsqu'un poignard est équipé + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise du poignard",
      maxLvl: 10,
      req: "Dague Lv.5",
      template: "Increases dagger skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Preuve de vol",
      maxLvl: 10,
      req: "Dague Lv.10",
      template: "Après avoir touché un ennemi avec Switch, l'empoisonne pendant +{val} secondes (1 stack)",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Amélioration du contrôle des dagues",
      maxLvl: 10,
      req: "Dague Lv.10",
      template: "Diminue le coût SP nécessaire pour le stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinct de combat",
      maxLvl: 10,
      req: "Dague Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinct de survie",
      maxLvl: 10,
      req: "Maîtrise de la dague 1H – Niveau 15, Preuve de voleur – Niveau 1",
      template: "PV max +{val} %",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Évasion",
      maxLvl: 10,
      req: "Dague Niv.20",
      template: "Augmente les chances d'échapper à toute attaque (sauf celles ciblées) lorsque le joueur a moins de +{val}% de ses PV max.",
      calc: (lvl) => lvl * 2,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Connaissance des armes",
      maxLvl: 10,
      req: "Dague Niv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Executer's Eyes",
      maxLvl: 10,
      req: "Dague Niv.30",
      template: "Chaque attaque a une chance de faire subir à l'ennemi plus de dégâts lors du prochain coup infligé au cours des +{val} secondes suivantes.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dagger's Secret",
      maxLvl: 10,
      req: "Dague Lv.35",
      template: "Augmente l'Attaque lorsqu'un poignard est équipé+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée",
      maxLvl: 10,
      req: "Dague Niv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Surcharge I (Dague)",
      maxLvl: 10,
      req: "Dague Niv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur de flamme (Dague)",
      maxLvl: 10,
      req: "Dague Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Dague)",
      maxLvl: 10,
      req: "Dague Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur du vent (Dague)",
      maxLvl: 10,
      req: "Dague Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur terrestre (Dague)",
      maxLvl: 10,
      req: "Dague Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (Dague)",
      maxLvl: 10,
      req: "Dague Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur sombre (Dague)",
      maxLvl: 10,
      req: "Dague Niv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise de survie (Dague)",
      maxLvl: 10,
      req: "Dague Niv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Maîtrise de l'entaille (Dague)",
      maxLvl: 10,
      req: "Dague Niv.60",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques tranchantes + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Forte expertise en défense (Dague)",
      maxLvl: 10,
      req: "Dague Niv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Grève de suivi",
      maxLvl: 10,
      req: "Dague Niv.70",
      template: "Augmente l'attaque contre les ennemis affectés par [[Poison (compétence infligeant une maladie de statut)",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise en attaque féroce (Dague)",
      maxLvl: 10,
      req: "Dague Niv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flash pointu",
      maxLvl: 10,
      req: "Dague Niv.80",
      template: "Augmente l'attaque contre les ennemis affectés par [[Poison (compétence infligeant une maladie de statut)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bonus de maladie de statut",
      maxLvl: 10,
      req: "Dague Niv.85",
      template: "Augmente l'attaque contre les ennemis affectés par n'importe quelle maladie de statut.",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dark Rise (Dague)",
      maxLvl: 10,
      req: "Dague Niv.90",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre + {val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Frappe polie",
      maxLvl: 10,
      req: "Dague Lv.95",
      template: "Augmente l'attaque contre les ennemis affectés par [[Poison (compétence infligeant une maladie de statut)",
      calc: (lvl) => lvl * 0.01,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Charge sombre (Dague)",
      maxLvl: 10,
      req: "Dague Niv.100",
      template: "Augmente les dégâts infligés par l'élément sombre+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Assaut sanglant",
      maxLvl: 10,
      req: "Dague Niv.105",
      template: "Increases player's Attack when attacking enemies afflicted with [[Bleed (skill inflicting status ailment)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
  ],
  Axe: [
    {
      name: "Entraînement à la hache",
      maxLvl: 10,
      req: "Hache 2H Lv.1",
      template: "Augmente l'attaque régulière lorsqu'une hache est équipée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Body's Enhancement",
      maxLvl: 10,
      req: "Hache 2H Lv.1",
      template: "Augmente l'attaque lorsqu'une hache est équipée+{val}",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Axe's Blow",
      maxLvl: 10,
      req: "Hache 2H Lv.1",
      template: "Après avoir touché un ennemi à l'aide de Switch, améliore le joueur, ce qui lui fait subir moins de dégâts pendant +{val} secondes.",
      calc: (lvl) => lvl * 2.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Position de base",
      maxLvl: 10,
      req: "Hache 2H Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Esprit combatif",
      maxLvl: 10,
      req: "Hache 2H Lv.5",
      template: "Augmente le taux de remplissage de la jauge de commutation + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Maîtrise de la hache",
      maxLvl: 10,
      req: "Hache 2H Lv.5",
      template: "Increases axe skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Marque de mercenaire",
      maxLvl: 10,
      req: "Hache 2H Lv.10",
      template: "Réduit le coût en SP de tous les enregistrements de compétences de hache+{val}",
      calc: (lvl) => lvl * 15,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Amélioration du contrôle de la hache",
      maxLvl: 10,
      req: "Hache 2H Lv.10",
      template: "Diminue le coût SP nécessaire pour le stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinct de combat",
      maxLvl: 10,
      req: "Hache 2H Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinct de survie",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H – Niveau 15, Marque du mercenaire – Niveau 1",
      template: "PV max +{val} %",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Cliver",
      maxLvl: 10,
      req: "Hache 2H Lv.20",
      template: "Augmente l'attaque contre un ennemi avec plus de +{val} % de ses PV max.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Connaissance des armes",
      maxLvl: 10,
      req: "Hache 2H Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Kongou",
      maxLvl: 10,
      req: "Hache 2H Lv.30",
      template: "Decreases damage taken if it's more than +{val}% of character's max HP.",
      calc: (lvl) => [30, 35, 40, 45, 50, 55, 60, 65, 70, 75][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Axe's Secret",
      maxLvl: 10,
      req: "Hache 2H Lv.35",
      template: "Augmente l'attaque lorsqu'une hache est équipée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée",
      maxLvl: 10,
      req: "Hache 2H Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Surcharge I (Hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur de flamme (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur du vent (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur terrestre (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (Hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur sombre (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise de survie (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Compétence émoussée (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.60",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques contondantes+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Forte expertise en défense (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Puissance puissante",
      maxLvl: 10,
      req: "Hache 2H Lv.70",
      template: "Augmente l'attaque proportionnellement aux PV restants + {val}",
      calc: (lvl) =>
        [210, 220, 230, 240, 250, 260, 270, 280, 290, 300][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise en attaque féroce (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Amélioration de l'inversion",
      maxLvl: 10,
      req: "Hache 2H Lv.80",
      template: "When receiving a hit, there's a chance to obtain a buff which increases Attack+{val}",
      calc: (lvl) =>
        [15.5, 16, 16.5, 17, 17.5, 18, 18.5, 19, 19.5, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Assaut dynamique",
      maxLvl: 10,
      req: "Hache 2H Lv.85",
      template: "Augmente le joueur\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) => lvl * 0.25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Élévation de la Terre (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.90",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise de la compétence d'une seule épée (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.95",
      template: "Augmente la puissance des compétences d'épée unique de + {val} %",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge de terre (hache 2H)",
      maxLvl: 10,
      req: "Hache 2H Lv.100",
      template: "Augmente les dégâts infligés par l'élément Terre+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Attaque puissante",
      maxLvl: 10,
      req: "Hache 2H Lv.105",
      template: "Increases player's Attack proportionally to the percentage of remaining HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Surcharge I",
      maxLvl: 1,
      req: "Maîtrise de la hache 2H – Niveau 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise de survie",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 55, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Forte expertise en matière de défense",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 65, Expertise en survie (hache 2H) - Niveau 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise en attaque féroce",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 75, Forte expertise en défense (hache 2H) - Niveau 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "L'élévation de la Terre",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 90, Assaut dynamique - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge de terre",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 100, Maîtrise des compétences d'épée unique (hache 2H) - Niveau 5",
      template: "Augmente les dégâts infligés par l'élément Terre. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Maîtrise de la compétence d'une seule épée",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 95, Assaut dynamique - Niveau 5",
      template: "Augmente la puissance des compétences d'épée unique de + {val} %",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme Lueur",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 50, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqualueur",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 50, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur du vent",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 50, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur de la Terre",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 50, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briller Éclat",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 50, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur sombre",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 50, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Avancement de la technique de l'épée",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 50, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Augmente la puissance des compétences d'épée de +{val} %",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briser les fondamentaux",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H - Niveau 50, Maîtrise des compétences d'épée (hache 2H) - Niveau 5",
      template: "Augmente la valeur de rupture des compétences d'épée de + {val} %",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Attaque en chaîne liée",
      maxLvl: 10,
      req: "Maîtrise de la hache 2H – Niveau 110, Attaque puissante – Niveau 5",
      template: "Augmente la puissance des compétences d'épée utilisées sur Switch de + {val} %",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Spear: [
    {
      name: "Entraînement à la lance",
      maxLvl: 10,
      req: "Lance 2H Lv.1",
      template: "Augmente l'attaque régulière lorsqu'une lance est équipée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Bousculade",
      maxLvl: 10,
      req: "Lance 2H Lv.1",
      template: "Augmente l'attaque pendant +{val} secondes après le pas, lorsqu'une lance est équipée.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Spear's Blow",
      maxLvl: 10,
      req: "Lance 2H Lv.1",
      template: "Après avoir touché un ennemi à l'aide de Switch, améliore le joueur, ce qui augmente son taux critique pendant +{val} secondes.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Position de base",
      maxLvl: 10,
      req: "Lance 2H Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Coup de vent",
      maxLvl: 10,
      req: "Lance 2H Lv.5",
      template: "Réduit le temps de recharge pour Spear Skill Records+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Maîtrise de la lance",
      maxLvl: 10,
      req: "Lance 2H Lv.5",
      template: "Increases spear skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Marque de chevalier",
      maxLvl: 10,
      req: "Lance 2H Lv.10",
      template: "Restaure SP pour chaque ennemi vaincu+{val}",
      calc: (lvl) => lvl * 3,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Amélioration du contrôle de la lance",
      maxLvl: 10,
      req: "Lance 2H Lv.10",
      template: "Diminue le coût SP nécessaire pour le stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinct de combat",
      maxLvl: 10,
      req: "Lance 2H Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinct de survie",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 15, Marque de chevalier - Niveau 1",
      template: "PV max +{val} %",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Croc",
      maxLvl: 10,
      req: "Lance 2H Lv.20",
      template: "Augmente l'attaque contre les ennemis souffrant d'une maladie de statut lorsqu'une lance est équipée + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Connaissance des armes",
      maxLvl: 10,
      req: "Lance 2H Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Danse de la lance",
      maxLvl: 10,
      req: "Lance 2H Lv.30",
      template: "Description en attente (stub wiki)",
      calc: (lvl) => 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Spear's Secret",
      maxLvl: 10,
      req: "Lance 2H Lv.35",
      template: "Augmente l'Attaque lorsqu'une lance est équipée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée",
      maxLvl: 10,
      req: "Lance 2H Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Surcharge I (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme Lueur (Lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur du vent (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur terrestre (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (Lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur sombre (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise de survie (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Compétence en poussée (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.60",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques de poussée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Forte expertise en défense (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Commutateur de marquage",
      maxLvl: 10,
      req: "Lance 2H Lv.70",
      template: "Lorsque vous frappez un ennemi à l'aide de Switch, a une chance d'infliger à l'ennemi [[Stigma Debuff]] pendant +{val} secondes.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise en attaque féroce (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "À la poursuite des faibles",
      maxLvl: 10,
      req: "Lance 2H Lv.80",
      template: "Augmente l'attaque contre les ennemis affaiblis + {val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise globale des compétences d'épée (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.85",
      template: "Augmente la puissance des compétences d'épée dans les emplacements actifs ainsi que ceux qui font partie de Connect Chain de +{val} %",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lever du vent (Lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.90",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Art de destruction",
      maxLvl: 10,
      req: "Lance 2H Lv.95",
      template: "Augmente l'efficacité des pauses+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge de vent (lance 2H)",
      maxLvl: 10,
      req: "Lance 2H Lv.100",
      template: "Augmente les dégâts infligés par l'élément Vent+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Commutateur de dégradation d'armure",
      maxLvl: 10,
      req: "Lance 2H Lv.105",
      template: "Lorsque vous frappez un ennemi à l'aide de Switch, a une chance d'infliger à l'ennemi [[Armor Decay Debuff]] pendant +{val} secondes.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Surcharge I",
      maxLvl: 1,
      req: "Maîtrise de la lance 2H - Niveau 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise de survie",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 55, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Forte expertise en matière de défense",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 65, Expertise de survie (Lance 2H) - Niveau 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise en attaque féroce",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 75, Forte expertise en défense (Lance 2H) - Niveau 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Montée du vent",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 90, Maîtrise globale des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge de vent",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 100, Art de la destruction - Niveau 5",
      template: "Augmente les dégâts infligés par l'élément Vent. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Maîtrise globale des compétences d’épée",
      maxLvl: 10,
      req: "Maîtrise de la lance - Niveau 85, Expertise en attaque féroce (Lance 2H) - Niveau 5",
      template: "Augmente la puissance des compétences d'épée dans les emplacements actifs ainsi que ceux qui font partie de Connect Chain de +{val} %",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme Lueur",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 50, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqualueur",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 50, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur du vent",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 50, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur de la Terre",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 50, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briller Éclat",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 50, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur sombre",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 50, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Avancement de la technique de l'épée",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 50, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente la puissance des compétences d'épée de +{val} %",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briser les fondamentaux",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 50, Maîtrise des compétences d'épée (lance 2H) - Niveau 5",
      template: "Augmente la valeur de rupture des compétences d'épée de + {val} %",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Attaque en chaîne liée",
      maxLvl: 10,
      req: "Maîtrise de la lance 2H - Niveau 110, Commutateur de dégradation d'armure - Niveau 1",
      template: "Augmente la puissance des compétences d'épée utilisées sur Switch de + {val} %",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Bow: [
    {
      name: "Entraînement à l'arc",
      maxLvl: 10,
      req: "Arc Lv.1",
      template: "Augmente l'attaque régulière lorsqu'un arc est équipé+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Pierce",
      maxLvl: 10,
      req: "Arc Lv.1",
      template: "Augmente l'attaque lorsque les PV sont supérieurs à +{val} %",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Flash",
      maxLvl: 10,
      req: "Arc Lv.1",
      template: "Après avoir touché un ennemi à l'aide de Switch, améliore le joueur, ce qui augmente son taux critique pendant +{val} secondes.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Position de base",
      maxLvl: 10,
      req: "Arc Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Tir précis",
      maxLvl: 10,
      req: "Arc Lv.5",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques de poussée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise de l'arc",
      maxLvl: 10,
      req: "Arc Lv.5",
      template: "Increases bow skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Preuve d'Archer",
      maxLvl: 10,
      req: "Arc Lv.10",
      template: "Réduit le temps nécessaire pour charger certains records de compétences d'arc+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Amélioration du contrôle de l'arc",
      maxLvl: 10,
      req: "Arc Lv.10",
      template: "Diminue le coût SP nécessaire pour le stepping+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinct de combat",
      maxLvl: 10,
      req: "Arc Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinct de survie",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 15, Preuve d'Archer - Niveau 1",
      template: "PV max +{val} %",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Predator's Keen Eye",
      maxLvl: 10,
      req: "Arc Lv.20",
      template: "Augmente l'attaque contre un ennemi avec moins de +{val} % de ses PV max.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Connaissance des armes",
      maxLvl: 10,
      req: "Arc Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Croissant de Lune",
      maxLvl: 10,
      req: "Arc Lv.30",
      template: "Après avoir touché un ennemi avec une compétence d'arc sur Switch, active un buff qui pendant +{val} secondes (ou jusqu'à ce que le joueur subisse des dégâts) augmente l'attaque de +{val} %.",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bow's Secret",
      maxLvl: 10,
      req: "Arc Lv.35",
      template: "Augmente l'attaque lorsqu'un arc est équipé+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise des compétences d'épée",
      maxLvl: 10,
      req: "Arc Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Surcharge I (Arc)",
      maxLvl: 10,
      req: "Arc Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme brillante (arc)",
      maxLvl: 10,
      req: "Arc Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow (Arc)",
      maxLvl: 10,
      req: "Arc Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur du vent (arc)",
      maxLvl: 10,
      req: "Arc Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur terrestre (arc)",
      maxLvl: 10,
      req: "Arc Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Glow (Arc)",
      maxLvl: 10,
      req: "Arc Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Lueur sombre (arc)",
      maxLvl: 10,
      req: "Arc Lv.50",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise de survie (arc)",
      maxLvl: 10,
      req: "Arc Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Compétence en poussée (arc)",
      maxLvl: 10,
      req: "Arc Niv.60",
      template: "Augmente les dégâts infligés aux ennemis faibles aux attaques de poussée+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Forte expertise en défense (arc)",
      maxLvl: 10,
      req: "Arc Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Grève surprise",
      maxLvl: 10,
      req: "Arc Lv.70",
      template: "Augmente l'attaque contre les ennemis qui ne ciblent pas le joueur + {val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Expertise en attaque féroce (arc)",
      maxLvl: 10,
      req: "Arc Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Pause dure (arc)",
      maxLvl: 10,
      req: "Arc Lv.80",
      template: "Augmente le joueur\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Frappe inversée",
      maxLvl: 10,
      req: "Arc Lv.85",
      template: "Augmente l'attaque en fonction du pourcentage de PV restants",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Shine Rise (Arc)",
      maxLvl: 10,
      req: "Arc Lv.90",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Maîtrise de la compétence d'une seule épée (arc)",
      maxLvl: 10,
      req: "Arc Lv.95",
      template: "Augmente la puissance des compétences d'épée unique de + {val} %",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge brillante (arc)",
      maxLvl: 10,
      req: "Arc Lv.100",
      template: "Augmente les dégâts infligés par l'élément sacré+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Assaut inversé",
      maxLvl: 10,
      req: "Arc Lv.105",
      template: "Increases player's Attack proportionally to the percentage of lost HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Surcharge I",
      maxLvl: 1,
      req: "Maîtrise de l'arc - Niveau 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise de survie",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 55, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Forte expertise en matière de défense",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 65, Expertise de survie (Arc) - Niveau 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise en attaque féroce",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 75, Forte expertise en défense (Arc) - Niveau 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Pause dure",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 80, Expertise en attaque féroce (Arc) - Niveau 5",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Brillance",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 90, Frappe inversée - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré. +{val}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Charge de brillance",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 100, Maîtrise des compétences d'épée unique (Arc) - Niveau 5",
      template: "Augmente les dégâts infligés par l'élément sacré. +{val}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Maîtrise de la compétence d'une seule épée",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 95, Frappe inversée - Niveau 5",
      template: "Augmente la puissance des compétences d'épée unique de + {val} %",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Flamme Lueur",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 50, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Feu. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqualueur",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 50, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Eau. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur du vent",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 50, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Vent. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur de la Terre",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 50, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément Terre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briller Éclat",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 50, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sacré. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Lueur sombre",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 50, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Augmente l'attaque lors de l'utilisation de l'élément sombre. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Avancement de la technique de l'épée",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 50, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Augmente la puissance des compétences d'épée de +{val} %",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Briser les fondamentaux",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 50, Maîtrise des compétences d'épée (arc) - Niveau 5",
      template: "Augmente la valeur de rupture des compétences d'épée de + {val} %",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Attaque en chaîne liée",
      maxLvl: 10,
      req: "Maîtrise de l'arc - Niveau 110, Assaut inversé - Niveau 5",
      template: "Augmente la puissance des compétences d'épée utilisées sur Switch de + {val} %",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Shield: [
    {
      name: "Formation au bouclier",
      maxLvl: 10,
      req: "Bouclier Lv.1",
      template: "Augmente la défense lorsqu'un bouclier est équipé+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Résister",
      maxLvl: 10,
      req: "Bouclier Lv.1",
      template: "Augmente la résistance aux altérations de statut dommageables lorsqu'un bouclier est équipé + {val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Protéger",
      maxLvl: 10,
      req: "Bouclier Lv.1",
      template: "Après avoir touché un ennemi à l'aide de Switch, améliore le joueur, ce qui augmente sa défense pendant +{val} secondes.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Garde décisive",
      maxLvl: 10,
      req: "Bouclier Lv.5",
      template: "Réduit les dégâts subis d'un pourcentage en fonction du nombre de records de compétences de bouclier équipés + {val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Réflexion",
      maxLvl: 10,
      req: "Bouclier Lv.10",
      template: "Renvoie une partie des dégâts subis par un ennemi+{val}",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Instinct de survie",
      maxLvl: 10,
      req: "Maîtrise du bouclier - Niveau 15, Réflexion - Niveau 1",
      template: "PV max +{val} %",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Vitalité",
      maxLvl: 10,
      req: "Bouclier Niv.20",
      template: "Augmente la résistance au tressaillement lorsqu'un bouclier est équipé+{val}",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Connaissance du Bouclier",
      maxLvl: 10,
      req: "Bouclier Lv.25",
      template: "Passively increases the player's Defense+{val}",
      calc: (lvl) =>
        [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Transcendant",
      maxLvl: 10,
      req: "Bouclier Lv.30",
      template: "Augmente les dégâts infligés avec les enregistrements de compétences de bouclier+{val}",
      calc: (lvl) => [30, 35, 40, 45, 50][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Guérison du bouclier",
      maxLvl: 10,
      req: "Bouclier Lv.55",
      template: "Récupère une certaine quantité de HP toutes les +{val} secondes.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Expertise en récupération",
      maxLvl: 10,
      req: "Bouclier Niv.60",
      template: "Augmente passivement l'efficacité des objets de guérison+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Amélioration du corps (bouclier)",
      maxLvl: 10,
      req: "Bouclier Niv.65",
      template: "PV max +{val}",
      calc: (lvl) => lvl * 50,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "Guérison sur le terrain",
      maxLvl: 10,
      req: "Bouclier Niv.70",
      template: "Augmente passivement l'efficacité des plantes médicinales+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Coup puissant",
      maxLvl: 10,
      req: "Bouclier Niv.75",
      template: "Augmente les dégâts contre les ennemis faibles à contondants+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Encouragement physique (bouclier)",
      maxLvl: 10,
      req: "Bouclier Niv.80",
      template: "Passively increases player's HP+{val}",
      calc: (lvl) =>
        [525, 550, 575, 600, 625, 650, 675, 700, 725, 750][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Tranche puissante",
      maxLvl: 10,
      req: "Bouclier Niv.85",
      template: "Augmente les dégâts contre les ennemis faibles pour trancher+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    ,
    {
      name: "Encouragement physique",
      maxLvl: 10,
      req: "Maîtrise du bouclier – Niveau 80, Coup puissant – Niveau 5",
      template: "Passively increases player's HP. +{val}",
      calc: (lvl) => 500 + lvl * 25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Poussée puissante",
      maxLvl: 10,
      req: "Maîtrise du bouclier – Niveau 90, Slash puissant – Niveau 5",
      template: "Augmente les dégâts contre les ennemis faibles à la poussée. +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
  ],
};
