window.masteryData = {
  Sword: [
    {
      name: "劍術訓練",
      maxLvl: 10,
      req: "1H 劍 Lv.1",
      template: "When 1h Sword is equipped, normal attack's damage +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "騎士精神",
      maxLvl: 10,
      req: "1H 劍 Lv.1",
      template: "裝備劍時攻擊力和防禦力增加 +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "flat_atk_def",
      active: true,
    },
    {
      name: "Sword's Blow",
      maxLvl: 10,
      req: "1H 劍 Lv.1",
      template: "After hitting an enemy with Switch, buffs the player's Attack and Defense for 8 seconds by +{val}%",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "基本立場",
      maxLvl: 10,
      req: "1H 劍 Lv.1",
      template: "攻擊時對敵人造成 +{val} 點額外傷害（所有武器）",
      calc: (lvl) => lvl * 5,
      bonusType: "flat_damage",
      active: true,
    },
    {
      name: "全面打擊",
      maxLvl: 10,
      req: "劍修Lv.5",
      template: "裝備 1H 劍時，對砍伐能力較弱的敵人造成的傷害 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "劍術熟練度",
      maxLvl: 10,
      req: "劍修Lv.5、全力攻擊Lv.5",
      template: "裝備1H劍時，劍技威力+{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "戰士印記",
      maxLvl: 1,
      req: "1H 劍 Lv.10、全力攻擊 Lv.5",
      template: "裝備 1H 劍時，擊殺時回復+{val}% HP",
      calc: (lvl) => lvl * 2,
      bonusType: "healing_percent",
      active: true,
    },
    {
      name: "劍控提升",
      maxLvl: 1,
      req: "1H 劍 Lv.10、基礎姿勢 Lv.5",
      template: "裝備1H劍時，步行SP消耗-{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "step_reduction",
      active: true,
    },
    {
      name: "戰鬥本能",
      maxLvl: 10,
      req: "1H 劍 Lv.10、基礎姿勢 Lv.5",
      template: "攻擊力+{val}（所有武器）",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "生存本能",
      maxLvl: 10,
      req: "1H 劍 Lv.15、戰士印記 Lv.1",
      template: "最大生命值+{val}%（所有武器）",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "組合",
      maxLvl: 10,
      req: "1H 劍 Lv.20、生存本能 Lv.5",
      template: "裝備1H劍時，切換傷害+{val}%",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "武器知識",
      maxLvl: 10,
      req: "1H 劍 Lv.25、組合 Lv.5",
      template: "攻擊力 +{val}%（所有武器）",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.699999999999999, 5][
          lvl - 1
        ] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "開關充電",
      maxLvl: 10,
      req: "1H 劍 Lv.30、武器知識 Lv.5",
      template: "裝備1H劍時，切換技能時SP恢復+{val}",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "sp_recovery_flat",
      active: true,
    },
    {
      name: "劍的秘密",
      maxLvl: 10,
      req: "1H 劍 Lv.35、切換衝鋒 Lv.1",
      template: "裝備1H劍時，攻擊力+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍技掌握",
      maxLvl: 10,
      req: "1H 劍 Lv.40、武器知識 Lv.10",
      template: "劍技威力+{val}%（對所有武器都有效）",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "ss_power",
      active: true,
    },
    {
      name: "過度充電 I (1H 劍)",
      maxLvl: 10,
      req: "1H 劍 Lv.45",
      template: "當裝備 1H 劍時，開關量表將充能至第三級。使用第三級開關時傷害+200%。 ",
      calc: (lvl) => 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "火焰光輝 (1H 劍)",
      maxLvl: 10,
      req: "1H 劍Lv.50、劍技掌握Lv.5",
      template: "火屬性攻擊並裝備1H劍時，攻擊力+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "水色輝光 (1H 劍)",
      maxLvl: 10,
      req: "1H 劍Lv.50、劍技掌握Lv.5",
      template: "使用水屬性攻擊並裝備 1H 劍時，攻擊力 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "風光 (1H 劍)",
      maxLvl: 10,
      req: "1H 劍Lv.50、劍技掌握Lv.5",
      template: "風屬性攻擊並裝備1H劍時攻擊力+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "大地之光 (1H 劍)",
      maxLvl: 10,
      req: "1H 劍Lv.50、劍技掌握Lv.5",
      template: "使用土屬性攻擊並裝備 1H 劍時，攻擊力 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃耀光芒 (1H 劍)",
      maxLvl: 10,
      req: "1H 劍Lv.50、劍技掌握Lv.5",
      template: "聖屬性攻擊並裝備1H劍時，攻擊力+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "暗光 (1H 劍)",
      maxLvl: 10,
      req: "1H 劍Lv.50、劍技掌握Lv.5",
      template: "使用暗屬性攻擊並裝備1H劍時，攻擊力+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "生存專長（1H 劍）",
      maxLvl: 10,
      req: "1H 劍Lv.55、劍技掌握Lv.5",
      template: "裝備 1H 劍時 HP +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "斬擊熟練度（1H劍）",
      maxLvl: 10,
      req: "1H劍Lv.60，生存專長（1H劍）Lv.5",
      template: "裝備 1H 劍時，對斬擊較弱的敵人造成的傷害 +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "強大的防禦專長（1H劍）",
      maxLvl: 10,
      req: "1H劍Lv.65，生存專長（1H劍）Lv.5",
      template: "裝備 1H 劍時防禦 +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "def_flat",
      active: true,
    },
    {
      name: "燒傷防護",
      maxLvl: 10,
      req: "1H劍Lv.70、強防禦專精（1H劍）Lv.5",
      template: "裝備 1H 劍時，燃燒傷害 -{val}",
      calc: (lvl) =>
        [-4.5, -4, -3.5, -3, -2.5, -2, -1.5, -1, -0.5, 0][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "猛烈攻擊專長（1H劍）",
      maxLvl: 10,
      req: "1H劍Lv.75、強防禦專精（1H劍）Lv.5",
      template: "裝備 1H 劍時攻擊力 +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "硬擊（1H 劍）",
      maxLvl: 10,
      req: "1H劍Lv.80，猛攻專長（1H劍）Lv.5",
      template: "裝備1H劍時，使用Break時攻擊力+{val}",
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "單劍技能精通（1H劍）",
      maxLvl: 10,
      req: "1H劍Lv.85，猛攻專長（1H劍）Lv.5",
      template: "裝備1H劍時劍技能威力（單次）+{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "skill_power",
      active: true,
    },
    {
      name: "火焰崛起 (1H 劍)",
      maxLvl: 10,
      req: "1H劍Lv.90，猛攻專長（1H劍）Lv.5",
      template: "裝備1H劍時，使用火屬性時攻擊力+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "劍技熟練度（1H劍）",
      maxLvl: 10,
      req: "1H劍Lv.95,單劍技能精通(1H劍)Lv.5",
      template: "劍技傷害+{val}%（對所有武器都有效）",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "火焰衝鋒（1H 劍）",
      maxLvl: 10,
      req: "1H劍Lv.100,劍技熟練度(1H劍)Lv.5",
      template: "裝備1H劍時，火屬性傷害+{val}%",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "damage_percent_fire",
      active: true,
    },
    {
      name: "逆境守護者",
      maxLvl: 10,
      req: "1H劍Lv.105,炎衝鋒(1H劍)Lv.5",
      template: "配備 1H 劍且 HP 為 25% 或更低時，防禦力 +{val}",
      calc: (lvl) => lvl * 10,
      bonusType: "def_flat",
      active: true,
    },
    ,
    {
      name: "過度充電我",
      maxLvl: 1,
      req: "1H 劍熟練度 - 45 級",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存專長",
      maxLvl: 10,
      req: "1H 劍熟練度 - 55 級，劍技精通（1H 劍） - 5 級",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強大的國防專業知識",
      maxLvl: 10,
      req: "1H 劍熟練度 - 65 級，生存專長（1H 劍） - 5 級",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "猛烈攻擊專長",
      maxLvl: 10,
      req: "1H 劍熟練度 - 75 級，強防禦專精（1H 劍） - 5 級",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "單劍技能掌握",
      maxLvl: 10,
      req: "1H 劍熟練度 - 85 級，猛攻專精（1H 劍） - 5 級",
      template: "單一劍技威力增加+{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "劍技熟練度",
      maxLvl: 10,
      req: "1H 劍熟練度 - 95 級，單劍技能精通（1H 劍） - 5 級",
      template: "劍技威力增加+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "硬突破",
      maxLvl: 10,
      req: "1H 劍熟練度 - 80 級，猛攻專精（1H 劍） - 5 級",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰崛起",
      maxLvl: 10,
      req: "1H 劍熟練度 - 90 級，單劍技能精通（1H 劍） - 5 級",
      template: "使用火元素時攻擊力增加。 +{值}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰衝鋒",
      maxLvl: 10,
      req: "1H 劍熟練度 - 100 級，劍技熟練度（1H 劍） - 5 級",
      template: "增加火元素造成的傷害。 +{值}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光",
      maxLvl: 10,
      req: "1H 劍熟練度 - 50 級，劍技精通（1H 劍） - 5 級",
      template: "使用火元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "水色發光",
      maxLvl: 10,
      req: "1H 劍熟練度 - 50 級，劍技精通（1H 劍） - 5 級",
      template: "使用水元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風輝",
      maxLvl: 10,
      req: "1H 劍熟練度 - 50 級，劍技精通（1H 劍） - 5 級",
      template: "使用風屬性時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "地球輝光",
      maxLvl: 10,
      req: "1H 劍熟練度 - 50 級，劍技精通（1H 劍） - 5 級",
      template: "使用土元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "閃耀光芒",
      maxLvl: 10,
      req: "1H 劍熟練度 - 50 級，劍技精通（1H 劍） - 5 級",
      template: "使用聖元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "暗光",
      maxLvl: 10,
      req: "1H 劍熟練度 - 50 級，劍技精通（1H 劍） - 5 級",
      template: "使用暗元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "應用立場",
      maxLvl: 10,
      req: "釋放水晶(M) x 1",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 125,
      bonusType: "passive",
      active: true,
    },
    {
      name: "發達的姿態",
      maxLvl: 10,
      req: "釋放水晶(大) x 3",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "進階劍術",
      maxLvl: 10,
      req: "1H 劍熟練度 - 50 級，劍技精通（1H 劍） - 5 級",
      template: "劍技威力增加+{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "打破基本原理",
      maxLvl: 10,
      req: "1H 劍熟練度 - 50 級，劍技精通（1H 劍） - 5 級",
      template: "劍技的破壞值增加+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "綁定鏈攻擊",
      maxLvl: 10,
      req: "1H 劍術熟練度 - 110 級，逆境守衛 - 5 級",
      template: "Switch 上使用的劍技威力增加 +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Rapier: [
    {
      name: "劍桿培訓",
      maxLvl: 10,
      req: "1H 劍 Lv.1",
      template: "裝備1H細劍時普通攻擊傷害增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "連續攻擊",
      maxLvl: 10,
      req: "1H 劍 Lv.1",
      template: "裝備劍時，攻擊力會根據單次連擊的命中數而增加+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Rapier's Blow",
      maxLvl: 10,
      req: "1H 劍 Lv.1",
      template: "使用 Switch 擊中敵人後，玩家會收到一個增益效果，可提高其暴擊率，持續 +{val} 秒。",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "基本立場",
      maxLvl: 10,
      req: "1H 劍 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "瞄準弱點",
      maxLvl: 10,
      req: "1H 劍 Lv.5",
      template: "增加對推力攻擊較弱的敵人造成的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍術熟練度",
      maxLvl: 10,
      req: "1H 劍 Lv.5",
      template: "Increases rapier skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍客印記",
      maxLvl: 10,
      req: "1H 劍 Lv.10",
      template: "造成暴擊時恢復SP+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "sp",
      active: true,
    },
    {
      name: "劍桿控制改進",
      maxLvl: 10,
      req: "1H 劍 Lv.10",
      template: "減少步進所需的 SP 成本+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "戰鬥本能",
      maxLvl: 10,
      req: "1H 劍 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存本能",
      maxLvl: 10,
      req: "1H 劍術熟練度 - 15 級，劍客印記 - 1 級",
      template: "最大生命值+{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "閃電般的速度",
      maxLvl: 10,
      req: "1H 劍 Lv.20",
      template: "當玩家裝備劍增加暴擊傷害+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "武器知識",
      maxLvl: 10,
      req: "1H 劍 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "流星",
      maxLvl: 10,
      req: "1H 劍 Lv.30",
      template: "當裝備劍時，邁步後暴擊率增加 +{val} 秒。",
      calc: (lvl) => [20, 25, 30, 35, 40, 45, 50, 55, 60, 65][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "劍的秘密",
      maxLvl: 10,
      req: "1H 劍 Lv.35",
      template: "裝備劍時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍技掌握",
      maxLvl: 10,
      req: "1H 劍 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "過度充電 I (1H 劍桿)",
      maxLvl: 10,
      req: "1H 劍 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光 (1H 劍桿)",
      maxLvl: 10,
      req: "1H 劍 Lv.50",
      template: "使用火元素+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "水色輝光 (1H 劍桿)",
      maxLvl: 10,
      req: "1H 劍 Lv.50",
      template: "使用水元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "風輝 (1H 劍桿)",
      maxLvl: 10,
      req: "1H 劍 Lv.50",
      template: "使用風屬性+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "大地輝光 (1H 劍桿)",
      maxLvl: 10,
      req: "1H 劍 Lv.50",
      template: "使用土元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃亮 (1H 劍桿)",
      maxLvl: 10,
      req: "1H 劍 Lv.50",
      template: "使用聖元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "暗光 (1H 劍桿)",
      maxLvl: 10,
      req: "1H 劍 Lv.50",
      template: "使用暗元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "生存專長（1H 劍劍）",
      maxLvl: 10,
      req: "1H 劍 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "推力熟練度（1H 劍桿）",
      maxLvl: 10,
      req: "1H 劍 Lv.60",
      template: "增加對推力攻擊較弱的敵人造成的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "強大的防禦專長（1H劍劍）",
      maxLvl: 10,
      req: "1H 劍 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "要點突擊",
      maxLvl: 10,
      req: "1H 劍 Lv.70",
      template: "增加暴擊傷害的增益效果生效時攻擊力增加+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "猛烈攻擊專長（1H 劍）",
      maxLvl: 10,
      req: "1H 劍 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "刺擊要害",
      maxLvl: 10,
      req: "1H 劍 Lv.80",
      template: "使用技能時增加暴擊傷害+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "精準打擊",
      maxLvl: 10,
      req: "1H 劍 Lv.85",
      template: "使用技能時暴擊率提高+{val}%",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Rise（1H 劍桿）",
      maxLvl: 10,
      req: "1H 劍 Lv.90",
      template: "使用水元素時攻擊力增加+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "精心打擊",
      maxLvl: 10,
      req: "1H 劍 Lv.95",
      template: "使用 Switch 擊中敵人後，會對玩家施加增益，增加其暴擊傷害，持續 +{val} 秒。",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "水族衝鋒 (1H 劍桿)",
      maxLvl: 10,
      req: "1H 劍 Lv.100",
      template: "增加水元素造成的傷害+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "漏洞打擊",
      maxLvl: 10,
      req: "1H 劍 Lv.105",
      template: "Increases player's Attack when Critical Rate buff is active+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "過度充電我",
      maxLvl: 1,
      req: "1H 劍術熟練度 - 45 級",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存專長",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 55 級，劍技掌握（1H 細劍）- 5 級",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強大的國防專業知識",
      maxLvl: 10,
      req: "1H 劍術熟練度 - 65 級，生存專長（1H 劍術） - 5 級",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "猛烈攻擊專長",
      maxLvl: 10,
      req: "1H 劍術熟練度 - 75 級，強防禦專長（1H 劍術） - 5 級",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "水族崛起",
      maxLvl: 10,
      req: "1H 劍術熟練度 - 90 級，精準打擊 - 5 級",
      template: "使用水元素時攻擊力增加。 +{值}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "水族充能",
      maxLvl: 10,
      req: "1H 劍術熟練度 - 100 級，精細攻擊 - 5 級",
      template: "增加水元素造成的伤害。 +{值}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 50 級，劍技掌握（1H 細劍）- 5 級",
      template: "使用火元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "水色發光",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 50 級，劍技掌握（1H 細劍）- 5 級",
      template: "使用水元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風輝",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 50 級，劍技掌握（1H 細劍）- 5 級",
      template: "使用風屬性時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "地球輝光",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 50 級，劍技掌握（1H 細劍）- 5 級",
      template: "使用土元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "閃耀光芒",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 50 級，劍技掌握（1H 細劍）- 5 級",
      template: "使用聖元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "暗光",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 50 級，劍技掌握（1H 細劍）- 5 級",
      template: "使用暗元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "進階劍術",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 50 級，劍技掌握（1H 細劍）- 5 級",
      template: "劍技威力增加+{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "打破基本原理",
      maxLvl: 10,
      req: "1H 細劍熟練度 - 50 級，劍技掌握（1H 細劍）- 5 級",
      template: "劍技的破壞值增加+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "綁定鏈攻擊",
      maxLvl: 10,
      req: "1H 劍術熟練度 - 110 級，脆弱打擊 - 5 級",
      template: "Switch 上使用的劍技威力增加 +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Club: [
    {
      name: "俱樂部培訓",
      maxLvl: 10,
      req: "1H俱樂部Lv.1",
      template: "装备狼牙棒时增加普通攻击伤害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "藥物知識",
      maxLvl: 10,
      req: "1H俱樂部Lv.1",
      template: "裝備球桿時增加治療物品恢復的生命值+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Blow",
      maxLvl: 10,
      req: "1H俱樂部Lv.1",
      template: "使用 Switch 擊中敵人後，玩家及其隊伍會收到增益效果，減少他們受到的傷害，持續 +{val} 秒。",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "基本立場",
      maxLvl: 10,
      req: "1H俱樂部Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "重擊",
      maxLvl: 10,
      req: "1H俱樂部Lv.5",
      template: "增加對弱於鈍擊的敵人造成的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "俱樂部熟練程度",
      maxLvl: 10,
      req: "1H俱樂部Lv.5",
      template: "Increases club skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "防禦印記",
      maxLvl: 10,
      req: "1H俱樂部Lv.10",
      template: "每+{val}秒恢復生命值。",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "俱樂部控制改進",
      maxLvl: 10,
      req: "1H俱樂部Lv.10",
      template: "減少步進所需的 SP 成本+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "戰鬥本能",
      maxLvl: 10,
      req: "1H俱樂部Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存本能",
      maxLvl: 10,
      req: "1H 俱樂部熟練度 - 15 級，防禦印記 - 1 級",
      template: "最大生命值+{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "破甲",
      maxLvl: 10,
      req: "1H俱樂部Lv.20",
      template: "每次攻擊都有機會對被攻擊的敵人施加防禦減益效果，持續+{val}秒。",
      calc: (lvl) => [16, 17, 18, 19, 20, 21, 22, 23, 24, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "武器知識",
      maxLvl: 10,
      req: "1H 俱樂部 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "武器破壞",
      maxLvl: 10,
      req: "1H俱樂部Lv.30",
      template: "每次攻擊都有機會對被攻擊的敵人施加攻擊減益效果，持續+{val}秒。",
      calc: (lvl) => [27, 29, 31, 33, 35, 37, 39, 41, 43, 45][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "俱樂部的秘密",
      maxLvl: 10,
      req: "1H 俱樂部 Lv.35",
      template: "裝備狼牙棒時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍技掌握",
      maxLvl: 10,
      req: "1H俱樂部Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "超額收費 I（1H 俱樂部）",
      maxLvl: 10,
      req: "1H 俱樂部 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光（1H 俱樂部）",
      maxLvl: 10,
      req: "1H俱樂部Lv.50",
      template: "使用火元素+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Aqua Glow（1H 俱樂部）",
      maxLvl: 10,
      req: "1H俱樂部Lv.50",
      template: "使用水元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "風輝 (1H Club)",
      maxLvl: 10,
      req: "1H俱樂部Lv.50",
      template: "使用風屬性+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "地球之光（1H 俱樂部）",
      maxLvl: 10,
      req: "1H俱樂部Lv.50",
      template: "使用土元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃亮 (1H 俱樂部)",
      maxLvl: 10,
      req: "1H俱樂部Lv.50",
      template: "使用聖元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "暗光（1H 俱樂部）",
      maxLvl: 10,
      req: "1H俱樂部Lv.50",
      template: "使用暗元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "生存專業知識（1H 俱樂部）",
      maxLvl: 10,
      req: "1H 俱樂部 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "鈍器熟練度（1H 俱樂部）",
      maxLvl: 10,
      req: "1H俱樂部Lv.60",
      template: "增加對弱於鈍擊的敵人造成的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "強大的防守專長（1H俱樂部）",
      maxLvl: 10,
      req: "1H 俱樂部 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "雕擊",
      maxLvl: 10,
      req: "1H俱樂部Lv.70",
      template: "增加對被[[標記減益效果]減益的敵人的攻擊力",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "猛烈攻擊專長（1H俱樂部）",
      maxLvl: 10,
      req: "1H 俱樂部 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強大的備份",
      maxLvl: 10,
      req: "1H俱樂部Lv.80",
      template: "當使用 Switch 擊中敵人時，會透過增加隊友的鈍性弱點傷害來增強他們的能力+{val}",
      calc: (lvl) => lvl * 0.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "高防禦",
      maxLvl: 10,
      req: "1H 俱樂部 Lv.85",
      template: "當玩家有活躍增益效果時增加防禦",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風起 (1H 俱樂部)",
      maxLvl: 10,
      req: "1H俱樂部Lv.90",
      template: "使用風屬性+{val}時攻擊力增加",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "鼓勵",
      maxLvl: 10,
      req: "1H俱樂部Lv.95",
      template: "使用 Switch 擊中敵人後，玩家及其隊伍會收到增益效果，增加他們的攻擊力，持續 +{val} 秒。",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風之充能（1H俱樂部）",
      maxLvl: 10,
      req: "1H俱樂部Lv.100",
      template: "風屬性傷害增加+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "刻擊",
      maxLvl: 10,
      req: "1H俱樂部Lv.105",
      template: "增加對被[[標記減益效果]減益的敵人的攻擊力",
      calc: (lvl) => lvl * 20,
      bonusType: "atk_percent",
      active: true,
    },
  ],
  Dagger: [
    {
      name: "匕首訓練",
      maxLvl: 10,
      req: "匕首 Lv.1",
      template: "裝備匕首時增加普通攻擊+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "報復",
      maxLvl: 10,
      req: "匕首 Lv.1",
      template: "HP低於+{val}%時攻擊力增加",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "匕首之擊",
      maxLvl: 10,
      req: "匕首 Lv.1",
      template: "Increases damage dealt to an enemy which isn't focused on the player",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "基本立場",
      maxLvl: 10,
      req: "匕首 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "殘酷之刃",
      maxLvl: 10,
      req: "匕首 Lv.5",
      template: "裝備匕首時增加對異常狀態敵人的攻擊力+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "匕首熟練度",
      maxLvl: 10,
      req: "匕首 Lv.5",
      template: "Increases dagger skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "小偷的證明",
      maxLvl: 10,
      req: "匕首 Lv.10",
      template: "使用 Switch 擊中敵人後，使他中毒 +{val} 秒（1 層）",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "匕首控制改進",
      maxLvl: 10,
      req: "匕首 Lv.10",
      template: "減少步進所需的 SP 成本+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "戰鬥本能",
      maxLvl: 10,
      req: "匕首 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存本能",
      maxLvl: 10,
      req: "1H 匕首熟練度 - 15 級，盜賊證明 - 1 級",
      template: "最大生命值+{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "閃避",
      maxLvl: 10,
      req: "匕首 Lv.20",
      template: "當玩家的生命值低於 +{val}% 最大生命值時，增加躲避任何攻擊（重點攻擊除外）的幾率。",
      calc: (lvl) => lvl * 2,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "武器知識",
      maxLvl: 10,
      req: "匕首 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Executer's Eyes",
      maxLvl: 10,
      req: "匕首 Lv.30",
      template: "每次攻擊都有機會使敵人在接下來的 +{val} 秒內受到下一次攻擊時受到更多傷害。",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dagger's Secret",
      maxLvl: 10,
      req: "匕首 Lv.35",
      template: "裝備匕首時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍技掌握",
      maxLvl: 10,
      req: "匕首 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "過度充電 I（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰光輝（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.50",
      template: "使用火元素+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "水色輝光（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.50",
      template: "使用水元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "風輝（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.50",
      template: "使用風屬性+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "大地之光（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.50",
      template: "使用土元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃耀光芒（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.50",
      template: "使用聖元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "暗光（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.50",
      template: "使用暗元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "生存專長（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "斬擊熟練度（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.60",
      template: "增加無法進行斬擊攻擊的敵人所造成的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "強大的防禦專長（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "後續罷工",
      maxLvl: 10,
      req: "匕首 Lv.70",
      template: "增加對患有[[毒藥（造成異常狀態的技能）的敵人的攻擊力]",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "猛烈攻擊專長（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "銳利閃光",
      maxLvl: 10,
      req: "匕首 Lv.80",
      template: "增加對患有[[毒藥（造成異常狀態的技能）的敵人的攻擊力]",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "狀態疾病獎勵",
      maxLvl: 10,
      req: "匕首 Lv.85",
      template: "增加對受到任何異常狀態影響的敵人的攻擊力",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "黑暗崛起（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.90",
      template: "使用暗元素時攻擊力增加+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "拋光罷工",
      maxLvl: 10,
      req: "匕首 Lv.95",
      template: "增加對患有[[毒藥（造成異常狀態的技能）的敵人的攻擊力]",
      calc: (lvl) => lvl * 0.01,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "黑暗衝鋒（匕首）",
      maxLvl: 10,
      req: "匕首 Lv.100",
      template: "增加暗元素造成的傷害+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "血腥襲擊",
      maxLvl: 10,
      req: "匕首 Lv.105",
      template: "Increases player's Attack when attacking enemies afflicted with [[Bleed (skill inflicting status ailment)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
  ],
  Axe: [
    {
      name: "斧頭訓練",
      maxLvl: 10,
      req: "2H 斧 Lv.1",
      template: "裝備斧頭時增加普通攻擊力+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Body's Enhancement",
      maxLvl: 10,
      req: "2H 斧 Lv.1",
      template: "裝備斧頭時攻擊力增加+{val}",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Axe's Blow",
      maxLvl: 10,
      req: "2H 斧 Lv.1",
      template: "使用 Switch 擊中敵人後，會對玩家進行增益，使他在 +{val} 秒內受到更少的傷害。",
      calc: (lvl) => lvl * 2.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "基本立場",
      maxLvl: 10,
      req: "2H 斧 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "戰鬥精神",
      maxLvl: 10,
      req: "2H 斧 Lv.5",
      template: "增加開關量表填充率+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "斧頭熟練度",
      maxLvl: 10,
      req: "2H 斧 Lv.5",
      template: "Increases axe skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "僱傭兵印記",
      maxLvl: 10,
      req: "2H 斧 Lv.10",
      template: "減少所有斧頭技能記錄+{val}的SP消耗",
      calc: (lvl) => lvl * 15,
      bonusType: "sp",
      active: true,
    },
    {
      name: "斧頭控制改進",
      maxLvl: 10,
      req: "2H 斧 Lv.10",
      template: "減少步進所需的 SP 成本+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "戰鬥本能",
      maxLvl: 10,
      req: "2H 斧 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存本能",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 15 級，傭兵印記 - 1 級",
      template: "最大生命值+{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "劈砍",
      maxLvl: 10,
      req: "2H 斧 Lv.20",
      template: "增加對最大生命值 +{val}% 以上的敵人的攻擊力。",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "武器知識",
      maxLvl: 10,
      req: "2H 斧 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "金剛",
      maxLvl: 10,
      req: "2H 斧 Lv.30",
      template: "Decreases damage taken if it's more than +{val}% of character's max HP.",
      calc: (lvl) => [30, 35, 40, 45, 50, 55, 60, 65, 70, 75][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "斧頭的秘密",
      maxLvl: 10,
      req: "2H 斧 Lv.35",
      template: "裝備斧頭時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍技掌握",
      maxLvl: 10,
      req: "2H 斧 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "過度充電 I (2H 軸)",
      maxLvl: 10,
      req: "2H 斧 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光 (2H 斧頭)",
      maxLvl: 10,
      req: "2H 斧 Lv.50",
      template: "使用火元素+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "水色輝光 (2H 斧頭)",
      maxLvl: 10,
      req: "2H 斧 Lv.50",
      template: "使用水元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "風輝 (2H 斧頭)",
      maxLvl: 10,
      req: "2H 斧 Lv.50",
      template: "使用風屬性+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "大地輝光 (2H 斧頭)",
      maxLvl: 10,
      req: "2H 斧 Lv.50",
      template: "使用土元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃耀光芒 (2H 斧頭)",
      maxLvl: 10,
      req: "2H 斧 Lv.50",
      template: "使用聖元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "暗光（2H 斧頭）",
      maxLvl: 10,
      req: "2H 斧 Lv.50",
      template: "使用暗元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "生存專長（2H 斧頭）",
      maxLvl: 10,
      req: "2H 斧 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "鈍器熟練度（2H 斧頭）",
      maxLvl: 10,
      req: "2H 斧 Lv.60",
      template: "增加對弱於鈍擊的敵人造成的傷害+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "強大的防禦專長（2H 斧頭）",
      maxLvl: 10,
      req: "2H 斧 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強大動力",
      maxLvl: 10,
      req: "2H 斧 Lv.70",
      template: "攻擊力與剩餘HP+{val}成比例增加",
      calc: (lvl) =>
        [210, 220, 230, 240, 250, 260, 270, 280, 290, 300][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "猛烈攻擊專長（2H 斧）",
      maxLvl: 10,
      req: "2H 斧 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "逆轉強化",
      maxLvl: 10,
      req: "2H 斧 Lv.80",
      template: "When receiving a hit, there's a chance to obtain a buff which increases Attack+{val}",
      calc: (lvl) =>
        [15.5, 16, 16.5, 17, 17.5, 18, 18.5, 19, 19.5, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "動態突擊",
      maxLvl: 10,
      req: "2H 斧 Lv.85",
      template: "增加玩家\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) => lvl * 0.25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "大地崛起 (2H 斧頭)",
      maxLvl: 10,
      req: "2H 斧 Lv.90",
      template: "使用土元素時攻擊力增加+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "單劍技能精通（2H 斧頭）",
      maxLvl: 10,
      req: "2H 斧 Lv.95",
      template: "單一劍技威力增加+{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "大地衝鋒 (2H 斧頭)",
      maxLvl: 10,
      req: "2H 斧 Lv.100",
      template: "增加土元素造成的傷害+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "強力攻擊",
      maxLvl: 10,
      req: "2H 斧 Lv.105",
      template: "Increases player's Attack proportionally to the percentage of remaining HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "過度充電我",
      maxLvl: 1,
      req: "2H 斧頭熟練度 - 45 級",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存專長",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 55 級，劍技掌握（2H 斧頭） - 5 級",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強大的國防專業知識",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 65 級，生存專長（2H 斧頭） - 5 級",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "猛烈攻擊專長",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 75 級，強防禦專長（2H 斧頭） - 5 級",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "地球崛起",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 90 級，動態攻擊 - 5 級",
      template: "使用土元素時攻擊力增加。 +{值}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "地球電荷",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 100 級，單劍技能精通（2H 斧頭） - 5 級",
      template: "增加土元素造成的傷害。 +{值}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "單劍技能掌握",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 95 級，動態攻擊 - 5 級",
      template: "單一劍技威力增加+{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 50 級，劍技精通（2H 斧頭） - 5 級",
      template: "使用火元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "水色發光",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 50 級，劍技精通（2H 斧頭） - 5 級",
      template: "使用水元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風輝",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 50 級，劍技精通（2H 斧頭） - 5 級",
      template: "使用風屬性時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "地球輝光",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 50 級，劍技精通（2H 斧頭） - 5 級",
      template: "使用土元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "閃耀光芒",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 50 級，劍技精通（2H 斧頭） - 5 級",
      template: "使用聖元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "暗光",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 50 級，劍技精通（2H 斧頭） - 5 級",
      template: "使用暗元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "進階劍術",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 50 級，劍技精通（2H 斧頭） - 5 級",
      template: "劍技威力增加+{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "打破基本原理",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 50 級，劍技精通（2H 斧頭） - 5 級",
      template: "劍技的破壞值增加+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "綁定鏈攻擊",
      maxLvl: 10,
      req: "2H 斧頭熟練度 - 110 級，強力攻擊 - 5 級",
      template: "Switch 上使用的劍技威力增加 +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Spear: [
    {
      name: "矛訓練",
      maxLvl: 10,
      req: "2H 槍 Lv.1",
      template: "裝備長矛時增加普通攻擊力+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "踩踏",
      maxLvl: 10,
      req: "2H 槍 Lv.1",
      template: "當裝備長矛時，邁步後攻擊力增加 +{val} 秒。",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Spear's Blow",
      maxLvl: 10,
      req: "2H 槍 Lv.1",
      template: "使用 Switch 擊中敵人後，對玩家進行增益效果，提高他的暴擊率，持續 +{val} 秒。",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "基本立場",
      maxLvl: 10,
      req: "2H 槍 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "大風",
      maxLvl: 10,
      req: "2H 槍 Lv.5",
      template: "縮短矛技能記錄+{val}的冷卻時間",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "矛熟練度",
      maxLvl: 10,
      req: "2H 槍 Lv.5",
      template: "Increases spear skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "騎士印記",
      maxLvl: 10,
      req: "2H 槍 Lv.10",
      template: "每擊敗一個敵人就會恢復 SP+{val}",
      calc: (lvl) => lvl * 3,
      bonusType: "sp",
      active: true,
    },
    {
      name: "矛控制改良",
      maxLvl: 10,
      req: "2H 槍 Lv.10",
      template: "減少步進所需的 SP 成本+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "戰鬥本能",
      maxLvl: 10,
      req: "2H 槍 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存本能",
      maxLvl: 10,
      req: "2H 矛熟練度 - 15 級，騎士印記 - 1 級",
      template: "最大生命值+{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "方",
      maxLvl: 10,
      req: "2H 槍 Lv.20",
      template: "裝備長矛時，增加對異常狀態敵人的攻擊力+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "武器知識",
      maxLvl: 10,
      req: "2H 槍 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "槍舞",
      maxLvl: 10,
      req: "2H 槍 Lv.30",
      template: "描述待定（wiki 存根）",
      calc: (lvl) => 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "長矛的秘密",
      maxLvl: 10,
      req: "2H 槍 Lv.35",
      template: "裝備長矛時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍技掌握",
      maxLvl: 10,
      req: "2H 槍 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "過度充電 I (2H 矛)",
      maxLvl: 10,
      req: "2H 槍 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光 (2H 矛)",
      maxLvl: 10,
      req: "2H 槍 Lv.50",
      template: "使用火元素+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "水色輝光 (2H 矛)",
      maxLvl: 10,
      req: "2H 槍 Lv.50",
      template: "使用水元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "風光 (2H 矛)",
      maxLvl: 10,
      req: "2H 槍 Lv.50",
      template: "使用風屬性+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "大地之光 (2H 矛)",
      maxLvl: 10,
      req: "2H 槍 Lv.50",
      template: "使用土元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃耀光芒 (2H 矛)",
      maxLvl: 10,
      req: "2H 槍 Lv.50",
      template: "使用聖元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "暗光 (2H 矛)",
      maxLvl: 10,
      req: "2H 槍 Lv.50",
      template: "使用暗元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "生存專長（2H 矛）",
      maxLvl: 10,
      req: "2H 槍 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "推力熟練度（2H 矛）",
      maxLvl: 10,
      req: "2H 槍 Lv.60",
      template: "增加對推力攻擊較弱的敵人造成的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "強大的防禦專長（2H 矛）",
      maxLvl: 10,
      req: "2H 槍 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "標記開關",
      maxLvl: 10,
      req: "2H 槍 Lv.70",
      template: "使用 Switch 擊中敵人時，有幾率對敵人造成 [[聖痕減益]]，持續 +{val} 秒。",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    {
      name: "猛烈攻擊專長（2H 矛）",
      maxLvl: 10,
      req: "2H 槍 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "追尋弱者",
      maxLvl: 10,
      req: "2H 槍 Lv.80",
      template: "增加對減益敵人的攻擊力+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍技綜合掌握（2H 槍）",
      maxLvl: 10,
      req: "2H 槍 Lv.85",
      template: "將活動插槽以及連接鏈中的劍技能的力量提高 +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風起 (2H 矛)",
      maxLvl: 10,
      req: "2H 槍 Lv.90",
      template: "使用風屬性+{val}時攻擊力增加",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "破壞藝術",
      maxLvl: 10,
      req: "2H 槍 Lv.95",
      template: "提高斷裂效率+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風之衝鋒 (2H 槍)",
      maxLvl: 10,
      req: "2H 槍 Lv.100",
      template: "風屬性傷害增加+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "裝甲衰減開關",
      maxLvl: 10,
      req: "2H 槍 Lv.105",
      template: "使用 Switch 擊中敵人時，有幾率對敵人造成 [[護甲衰減減益]]，持續 +{val} 秒。",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "過度充電我",
      maxLvl: 1,
      req: "2H 矛熟練度 - 45 級",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存專長",
      maxLvl: 10,
      req: "2H 槍熟練度 - 55 級，劍技精通（2H 槍） - 5 級",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強大的國防專業知識",
      maxLvl: 10,
      req: "2H 矛熟練度 - 65 級，生存專長（2H 矛） - 5 級",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "猛烈攻擊專長",
      maxLvl: 10,
      req: "2H 槍熟練度 - 75 級，強防禦專長（2H 槍） - 5 級",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風起",
      maxLvl: 10,
      req: "2H 槍熟練度 - 90 級，整體劍技精通（2H 槍） - 5 級",
      template: "使用風屬性時攻擊力增加。 +{值}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風能充能",
      maxLvl: 10,
      req: "2H 矛熟練度 - 100 級，破壞藝術 - 5 級",
      template: "增加風屬性的傷害。 +{值}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "劍技綜合掌握",
      maxLvl: 10,
      req: "槍熟練度 - 85級，猛烈攻擊專精（2H槍） - 5級",
      template: "將活動插槽以及連接鏈中的劍技能的力量提高 +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光",
      maxLvl: 10,
      req: "2H 槍熟練度 - 50 級，劍技精通（2H 槍） - 5 級",
      template: "使用火元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "水色發光",
      maxLvl: 10,
      req: "2H 槍熟練度 - 50 級，劍技精通（2H 槍） - 5 級",
      template: "使用水元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風輝",
      maxLvl: 10,
      req: "2H 槍熟練度 - 50 級，劍技精通（2H 槍） - 5 級",
      template: "使用風屬性時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "地球輝光",
      maxLvl: 10,
      req: "2H 槍熟練度 - 50 級，劍技精通（2H 槍） - 5 級",
      template: "使用土元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "閃耀光芒",
      maxLvl: 10,
      req: "2H 槍熟練度 - 50 級，劍技精通（2H 槍） - 5 級",
      template: "使用聖元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "暗光",
      maxLvl: 10,
      req: "2H 槍熟練度 - 50 級，劍技精通（2H 槍） - 5 級",
      template: "使用暗元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "進階劍術",
      maxLvl: 10,
      req: "2H 槍熟練度 - 50 級，劍技精通（2H 槍） - 5 級",
      template: "劍技威力增加+{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "打破基本原理",
      maxLvl: 10,
      req: "2H 槍熟練度 - 50 級，劍技精通（2H 槍） - 5 級",
      template: "劍技的破壞值增加+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "綁定鏈攻擊",
      maxLvl: 10,
      req: "2H 矛熟練度 - 110 級，護甲衰減開關 - 1 級",
      template: "Switch 上使用的劍技威力增加 +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Bow: [
    {
      name: "弓訓練",
      maxLvl: 10,
      req: "弓 Lv.1",
      template: "裝備弓時增加普通攻擊力+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "皮爾斯",
      maxLvl: 10,
      req: "弓 Lv.1",
      template: "HP高於+{val}%時攻擊力增加",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃光燈",
      maxLvl: 10,
      req: "弓 Lv.1",
      template: "使用 Switch 擊中敵人後，對玩家進行增益效果，提高他的暴擊率，持續 +{val} 秒。",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "基本立場",
      maxLvl: 10,
      req: "弓 Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "精準射擊",
      maxLvl: 10,
      req: "弓 Lv.5",
      template: "增加對推力攻擊較弱的敵人造成的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "弓熟練度",
      maxLvl: 10,
      req: "弓 Lv.5",
      template: "Increases bow skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "弓箭手證明",
      maxLvl: 10,
      req: "弓 Lv.10",
      template: "縮短部分弓技能充能所需的時間記錄+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    {
      name: "弓控制改進",
      maxLvl: 10,
      req: "弓 Lv.10",
      template: "減少步進所需的 SP 成本+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "戰鬥本能",
      maxLvl: 10,
      req: "弓 Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存本能",
      maxLvl: 10,
      req: "弓熟練度 - 15 級，弓箭手證明 - 1 級",
      template: "最大生命值+{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "掠食者的銳利之眼",
      maxLvl: 10,
      req: "弓 Lv.20",
      template: "增加對最大生命值+{val}%以下的敵人的攻擊力。",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "武器知識",
      maxLvl: 10,
      req: "弓 Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "新月",
      maxLvl: 10,
      req: "弓 Lv.30",
      template: "在 Switch 上用弓技能擊中敵人後，會啟動一個增益效果，持續 +{val} 秒（或直到玩家受到傷害），攻擊力提高 +{val}%。",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bow's Secret",
      maxLvl: 10,
      req: "弓 Lv.35",
      template: "裝備弓時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "劍技掌握",
      maxLvl: 10,
      req: "弓 Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "過度充電 I（弓）",
      maxLvl: 10,
      req: "弓 Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光（弓）",
      maxLvl: 10,
      req: "弓 Lv.50",
      template: "使用火元素+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "水色輝光（弓）",
      maxLvl: 10,
      req: "弓 Lv.50",
      template: "使用水元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "風輝（弓）",
      maxLvl: 10,
      req: "弓 Lv.50",
      template: "使用風屬性+{val}時攻擊力增加",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "大地之光（弓）",
      maxLvl: 10,
      req: "弓 Lv.50",
      template: "使用土元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃耀光芒（弓）",
      maxLvl: 10,
      req: "弓 Lv.50",
      template: "使用聖元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "暗光（弓）",
      maxLvl: 10,
      req: "弓 Lv.50",
      template: "使用暗元素時攻擊力增加+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "生存專長（弓）",
      maxLvl: 10,
      req: "弓 Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "推力熟練度（弓）",
      maxLvl: 10,
      req: "弓 Lv.60",
      template: "增加對推力攻擊較弱的敵人造成的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "強大的防禦專長（弓）",
      maxLvl: 10,
      req: "弓 Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "奇襲",
      maxLvl: 10,
      req: "弓 Lv.70",
      template: "增加對不以玩家為目標的敵人的攻擊力+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "猛烈攻擊專長（弓）",
      maxLvl: 10,
      req: "弓 Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "硬擊（弓）",
      maxLvl: 10,
      req: "弓 Lv.80",
      template: "增加玩家\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "反向打擊",
      maxLvl: 10,
      req: "弓 Lv.85",
      template: "根據剩餘HP百分比增加攻擊力",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "閃耀崛起（弓）",
      maxLvl: 10,
      req: "弓 Lv.90",
      template: "使用聖元素時攻擊力增加+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "單劍技巧掌握（弓）",
      maxLvl: 10,
      req: "弓 Lv.95",
      template: "單一劍技威力增加+{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "閃耀衝鋒（弓）",
      maxLvl: 10,
      req: "弓 Lv.100",
      template: "聖元素造成的傷害增加+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "反向突擊",
      maxLvl: 10,
      req: "弓 Lv.105",
      template: "Increases player's Attack proportionally to the percentage of lost HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "過度充電我",
      maxLvl: 1,
      req: "弓熟練度 - 45 級",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "生存專長",
      maxLvl: 10,
      req: "弓熟練度 - 55 級，劍技精通（弓） - 5 級",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強大的國防專業知識",
      maxLvl: 10,
      req: "弓熟練度 - 65 級，生存專長（弓） - 5 級",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "猛烈攻擊專長",
      maxLvl: 10,
      req: "弓熟練度 - 75級，強防禦專長（弓） - 5級",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "硬突破",
      maxLvl: 10,
      req: "弓熟練度 - 80級，猛烈攻擊專長（弓） - 5級",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "閃耀崛起",
      maxLvl: 10,
      req: "弓熟練度 - 90級，反向攻擊 - 5級",
      template: "使用聖元素時攻擊力增加。 +{值}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "閃耀充電",
      maxLvl: 10,
      req: "弓熟練度 - 100級，單劍技能掌握（弓） - 5級",
      template: "增加聖元素造成的傷害。 +{值}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "單劍技能掌握",
      maxLvl: 10,
      req: "弓熟練度 - 95級，反向攻擊 - 5級",
      template: "單一劍技威力增加+{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "火焰輝光",
      maxLvl: 10,
      req: "弓熟練度 - 50級，劍技精通（弓） - 5級",
      template: "使用火元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "水色發光",
      maxLvl: 10,
      req: "弓熟練度 - 50級，劍技精通（弓） - 5級",
      template: "使用水元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "風輝",
      maxLvl: 10,
      req: "弓熟練度 - 50級，劍技精通（弓） - 5級",
      template: "使用風屬性時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "地球輝光",
      maxLvl: 10,
      req: "弓熟練度 - 50級，劍技精通（弓） - 5級",
      template: "使用土元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "閃耀光芒",
      maxLvl: 10,
      req: "弓熟練度 - 50級，劍技精通（弓） - 5級",
      template: "使用聖元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "暗光",
      maxLvl: 10,
      req: "弓熟練度 - 50級，劍技精通（弓） - 5級",
      template: "使用暗元素時攻擊力增加。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "進階劍術",
      maxLvl: 10,
      req: "弓熟練度 - 50級，劍技精通（弓） - 5級",
      template: "劍技威力增加+{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "打破基本原理",
      maxLvl: 10,
      req: "弓熟練度 - 50級，劍技精通（弓） - 5級",
      template: "劍技的破壞值增加+{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "綁定鏈攻擊",
      maxLvl: 10,
      req: "弓熟練度 - 110級，反向攻擊 - 5級",
      template: "Switch 上使用的劍技威力增加 +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Shield: [
    {
      name: "盾牌訓練",
      maxLvl: 10,
      req: "護盾Lv.1",
      template: "裝備盾牌時防禦力增加+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "抵抗",
      maxLvl: 10,
      req: "護盾Lv.1",
      template: "裝備護盾時提高對傷害性異常狀態的抵抗力+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "保護",
      maxLvl: 10,
      req: "護盾Lv.1",
      template: "使用 Switch 擊中敵人後，會增強玩家的防禦力，持續 +{val} 秒。",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "果斷後衛",
      maxLvl: 10,
      req: "護盾Lv.5",
      template: "減少受到的傷害，百分比取決於裝備的盾牌技能記錄數量+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "反思",
      maxLvl: 10,
      req: "護盾 Lv.10",
      template: "將受到的部分傷害反射回敵人+{val}",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "生存本能",
      maxLvl: 10,
      req: "盾牌熟練度 - 15 級，反射 - 1 級",
      template: "最大生命值+{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "活力",
      maxLvl: 10,
      req: "護盾 Lv.20",
      template: "裝備盾牌時增加退縮抵抗力+{val}",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "盾牌知識",
      maxLvl: 10,
      req: "護盾 Lv.25",
      template: "Passively increases the player's Defense+{val}",
      calc: (lvl) =>
        [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "超越",
      maxLvl: 10,
      req: "護盾 Lv.30",
      template: "增加護盾技能記錄+{val}造成的傷害",
      calc: (lvl) => [30, 35, 40, 45, 50][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "護盾治療",
      maxLvl: 10,
      req: "護盾 Lv.55",
      template: "每+{val}秒恢復一定量的HP。",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "恢復專業知識",
      maxLvl: 10,
      req: "護盾 Lv.60",
      template: "被動提高治療物品的效果+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "身體強化（盾）",
      maxLvl: 10,
      req: "護盾 Lv.65",
      template: "最大生命值+{val}",
      calc: (lvl) => lvl * 50,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "現場治療",
      maxLvl: 10,
      req: "護盾 Lv.70",
      template: "被動提高治療植物的效能+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強力一擊",
      maxLvl: 10,
      req: "護盾 Lv.75",
      template: "增加對弱於鈍器的敵人的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "物理鼓勵（盾）",
      maxLvl: 10,
      req: "護盾 Lv.80",
      template: "Passively increases player's HP+{val}",
      calc: (lvl) =>
        [525, 550, 575, 600, 625, 650, 675, 700, 725, 750][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強力斬擊",
      maxLvl: 10,
      req: "護盾 Lv.85",
      template: "增加對無法砍殺的敵人的傷害+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    ,
    {
      name: "身體上的鼓勵",
      maxLvl: 10,
      req: "盾牌熟練度 - 80級，強力打擊 - 5級",
      template: "Passively increases player's HP. +{val}",
      calc: (lvl) => 500 + lvl * 25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "強大的推力",
      maxLvl: 10,
      req: "盾牌熟練度 - 90級，強力斬擊 - 5級",
      template: "增加對推力較弱的敵人的傷害。 +{值}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
  ],
};
