window.masteryData = {
  Sword: [
    {
      name: "Entrenamiento con espada",
      maxLvl: 10,
      req: "Espada 1H Lv.1",
      template: "When 1h Sword is equipped, normal attack's damage +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "caballería",
      maxLvl: 10,
      req: "Espada 1H Lv.1",
      template: "Aumenta el ataque y la defensa cuando se equipa una espada en +{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "flat_atk_def",
      active: true,
    },
    {
      name: "Sword's Blow",
      maxLvl: 10,
      req: "Espada 1H Lv.1",
      template: "After hitting an enemy with Switch, buffs the player's Attack and Defense for 8 seconds by +{val}%",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Postura básica",
      maxLvl: 10,
      req: "Espada 1H Lv.1",
      template: "Agrega +{val} daño adicional al enemigo al atacar (Todas las armas)",
      calc: (lvl) => lvl * 5,
      bonusType: "flat_damage",
      active: true,
    },
    {
      name: "Huelga completa",
      maxLvl: 10,
      req: "Entrenamiento con espada Lv.5",
      template: "Cuando se equipa la Espada 1H, el daño infligido a los enemigos débiles para cortar +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "Competencia con la espada",
      maxLvl: 10,
      req: "Entrenamiento con espada Nv.5, Golpe completo Nv.5",
      template: "Cuando 1H Sword está equipado, Sword Skill Power +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Marca de guerrero",
      maxLvl: 1,
      req: "Espada 1H Lv.10, Golpe Completo Lv.5",
      template: "Cuando la espada 1H está equipada, restaura +{val}% HP al matar",
      calc: (lvl) => lvl * 2,
      bonusType: "healing_percent",
      active: true,
    },
    {
      name: "Mejora del control de la espada",
      maxLvl: 1,
      req: "Espada 1H Nv.10, Postura Básica Nv.5",
      template: "Cuando se equipa 1H Sword, el costo de SP es -{val} por avanzar",
      calc: (lvl) => lvl * 1,
      bonusType: "step_reduction",
      active: true,
    },
    {
      name: "Instinto de batalla",
      maxLvl: 10,
      req: "Espada 1H Nv.10, Postura Básica Nv.5",
      template: "Ataque +{val} (Todas las armas)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Instinto de supervivencia",
      maxLvl: 10,
      req: "1H Espada Lv.15, Marca de Guerrero Lv.1",
      template: "HP máximo +{val}% (todas las armas)",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "combinación",
      maxLvl: 10,
      req: "Espada 1H Lv.20, Instinto de Supervivencia Lv.5",
      template: "Cuando 1H Sword está equipado, daño de cambio +{val}%",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Conocimiento de armas",
      maxLvl: 10,
      req: "Espada 1H Nv.25, Combinación Nv.5",
      template: "Ataque +{val}% (Todas las armas)",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.699999999999999, 5][
          lvl - 1
        ] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Cambiar carga",
      maxLvl: 10,
      req: "Espada 1H Nv.30, Conocimiento de armas Nv.5",
      template: "Cuando 1H Sword está equipado, recupera +{val} SP al usar la habilidad de cambio",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "sp_recovery_flat",
      active: true,
    },
    {
      name: "Sword's Secret",
      maxLvl: 10,
      req: "Espada 1H Lv.35, Carga de Cambio Lv.1",
      template: "Cuando la Espada 1H está equipada, Ataque +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con la espada",
      maxLvl: 10,
      req: "Espada 1H Lv.40, Conocimiento de armas Lv.10",
      template: "Poder de habilidad con espada +{val}% (efectivo con todas las armas)",
      calc: (lvl) => [2, 3, 4, 5, 6, 7, 8, 9, 10, 11][lvl - 1] || 0,
      bonusType: "ss_power",
      active: true,
    },
    {
      name: "Sobrecarga I (Espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.45",
      template: "Switch Gauge se cargará hasta el tercer nivel cuando 1H Sword esté equipado. Daño +200% al usar el interruptor en el tercer nivel. ",
      calc: (lvl) => 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor de llamas (espada 1H)",
      maxLvl: 10,
      req: "1H Espada Lv.50, Dominio de Habilidad de Espada Lv.5",
      template: "Ataque +{val}% al atacar con Elemento Fuego y equipar una Espada 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor acuático (espada 1H)",
      maxLvl: 10,
      req: "1H Espada Lv.50, Dominio de Habilidad de Espada Lv.5",
      template: "Ataque +{val}% al atacar con Elemento Agua y equipar una Espada 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor del viento (espada 1H)",
      maxLvl: 10,
      req: "1H Espada Lv.50, Dominio de Habilidad de Espada Lv.5",
      template: "Ataque +{val}% al atacar con Elemento Viento y equipar una Espada 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor de la Tierra (Espada 1H)",
      maxLvl: 10,
      req: "1H Espada Lv.50, Dominio de Habilidad de Espada Lv.5",
      template: "Ataque +{val}% al atacar con Elemento Tierra y equipar una Espada 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Brillo Brillo (Espada 1H)",
      maxLvl: 10,
      req: "1H Espada Lv.50, Dominio de Habilidad de Espada Lv.5",
      template: "Ataque +{val}% al atacar con Elemento Sagrado y equipar una Espada 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor oscuro (espada 1H)",
      maxLvl: 10,
      req: "1H Espada Lv.50, Dominio de Habilidad de Espada Lv.5",
      template: "Ataque +{val}% al atacar con Elemento Oscuro y equipar una Espada 1H",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en supervivencia (espada 1H)",
      maxLvl: 10,
      req: "1H Espada Lv.55, Dominio de Habilidad de Espada Lv.5",
      template: "HP +{val} al equipar una espada 1H",
      calc: (lvl) => lvl * 100,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "Competencia con corte (espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.60, Experiencia en Supervivencia (Espada 1H) Lv.5",
      template: "Cuando se equipa 1H Sword, el daño infligido a los enemigos débiles para cortar +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent_slash_weakness",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa (espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.65, Experiencia en Supervivencia (Espada 1H) Lv.5",
      template: "Defensa +{val} al equipar una Espada 1H",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "def_flat",
      active: true,
    },
    {
      name: "Guardia de quemaduras",
      maxLvl: 10,
      req: "Espada 1H Lv.70, Fuerte experiencia en defensa (Espada 1H) Lv.5",
      template: "Cuando 1H Sword está equipado, daño por quemaduras -{val}",
      calc: (lvl) =>
        [-4.5, -4, -3.5, -3, -2.5, -2, -1.5, -1, -0.5, 0][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces (espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.75, Fuerte experiencia en defensa (Espada 1H) Lv.5",
      template: "Ataque +{val} al equipar una Espada 1H",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Hard Break (Espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.80, Experiencia en ataque feroz (Espada 1H) Lv.5",
      template: "Cuando 1H Sword está equipado, ataca +{val} al usar Break",
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Dominio de la habilidad con una sola espada (espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.85, Experiencia en ataque feroz (Espada 1H) Lv.5",
      template: "Poder de habilidad con espada (única) +{val}% al equipar una espada 1H",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "skill_power",
      active: true,
    },
    {
      name: "Elevación de llamas (espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.90, Experiencia en ataque feroz (Espada 1H) Lv.5",
      template: "Al equipar una espada 1H, ataca +{val} cuando uses el elemento Fuego",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_flat",
      active: true,
    },
    {
      name: "Dominio de la habilidad con la espada (espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.95, Dominio de habilidad con espada única (Espada 1H) Lv.5",
      template: "Daño de habilidad con espada +{val}% (efectivo con todas las armas)",
      calc: (lvl) => lvl * 1,
      bonusType: "damage_percent",
      active: true,
    },
    {
      name: "Carga de llamas (espada 1H)",
      maxLvl: 10,
      req: "Espada 1H Lv.100, Dominio de habilidad con espada (Espada 1H) Lv.5",
      template: "Al equipar una espada 1H, daño del elemento fuego +{val}%",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "damage_percent_fire",
      active: true,
    },
    {
      name: "Guardia de la adversidad",
      maxLvl: 10,
      req: "Espada 1H Lv.105, Carga de Llamas (Espada 1H) Lv.5",
      template: "Defensa +{val} al equipar una espada 1H y HP es 25% o menos",
      calc: (lvl) => lvl * 10,
      bonusType: "def_flat",
      active: true,
    },
    ,
    {
      name: "Sobrecargo yo",
      maxLvl: 1,
      req: "Competencia con espada 1H - Nivel 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en supervivencia",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 55, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa",
      maxLvl: 10,
      req: "Competencia con espada 1H - Nivel 65, Experiencia en supervivencia (Espada 1H) - Nivel 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces",
      maxLvl: 10,
      req: "Competencia con espada 1H - Nivel 75, Fuerte experiencia en defensa (Espada 1H) - Nivel 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dominio de la habilidad con una sola espada",
      maxLvl: 10,
      req: "Competencia con espada 1H - Nivel 85, Experiencia en ataques feroces (Espada 1H) - Nivel 5",
      template: "Aumenta el poder de las habilidades con espada única en +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia con la habilidad con la espada",
      maxLvl: 10,
      req: "Competencia con espada 1H - Nivel 95, Dominio de habilidad con espada única (Espada 1H) - Nivel 5",
      template: "Aumenta el poder de las habilidades con la espada en +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ruptura dura",
      maxLvl: 10,
      req: "Competencia con espada 1H - Nivel 80, Experiencia en ataque feroz (Espada 1H) - Nivel 5",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aumento de la llama",
      maxLvl: 10,
      req: "Competencia con espada 1H - Nivel 90, Dominio de habilidad con espada única (Espada 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Fuego. +{valor}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga de llama",
      maxLvl: 10,
      req: "Competencia con espada 1H - Nivel 100, Competencia con habilidad con espada (Espada 1H) - Nivel 5",
      template: "Aumenta el daño infligido con el elemento Fuego. +{valor}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llama",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 50, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Fuego. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor acuático",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 50, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Agua. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor del viento",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 50, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Viento. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de la Tierra",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 50, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Tierra. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Brillo Brillo",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 50, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "resplandor oscuro",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 50, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento oscuro. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Postura aplicada",
      maxLvl: 10,
      req: "Liberar cristal (M) x 1",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 125,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Postura desarrollada",
      maxLvl: 10,
      req: "Liberar cristal (L) x 3",
      template: "Passively increases the player's damage dealt with every attack. +{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Técnica de espada avanzada",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 50, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Aumenta el poder de las habilidades con la espada en +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rompiendo los fundamentos",
      maxLvl: 10,
      req: "Dominio de la espada 1H - Nivel 50, Dominio de la habilidad con la espada (Espada 1H) - Nivel 5",
      template: "Aumenta el valor de ruptura de las habilidades con espada en +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Ataque en cadena vinculado",
      maxLvl: 10,
      req: "1H Competencia con la espada - Nivel 110, Guardia de la adversidad - Nivel 5",
      template: "Aumenta el poder de las habilidades con espada utilizadas en Switch en +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Rapier: [
    {
      name: "Entrenamiento con estoque",
      maxLvl: 10,
      req: "1H Estoque Lv.1",
      template: "Aumenta el daño del ataque normal cuando se equipa un estoque 1H+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Ataque en serie",
      maxLvl: 10,
      req: "1H Estoque Lv.1",
      template: "Aumenta el ataque de acuerdo con la cantidad de HIT realizados en un solo combo, cuando el estoque está equipado+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Rapier's Blow",
      maxLvl: 10,
      req: "1H Estoque Lv.1",
      template: "Después de golpear a un enemigo usando Switch, el jugador recibe un beneficio que aumenta su tasa de críticos durante +{val} segundos.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Postura básica",
      maxLvl: 10,
      req: "1H Estoque Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Apuntar al punto débil",
      maxLvl: 10,
      req: "1H Estoque Lv.5",
      template: "Aumenta el daño infligido a los enemigos débiles a los ataques de empuje+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Competencia con estoque",
      maxLvl: 10,
      req: "1H Estoque Lv.5",
      template: "Increases rapier skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Marca de espadachín",
      maxLvl: 10,
      req: "1H Estoque Lv.10",
      template: "Restaura SP al dar un golpe crítico+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Mejora del control del estoque",
      maxLvl: 10,
      req: "1H Estoque Lv.10",
      template: "Disminuye el costo de SP necesario para dar el paso+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinto de batalla",
      maxLvl: 10,
      req: "1H Estoque Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinto de supervivencia",
      maxLvl: 10,
      req: "1H Competencia con estoque - Nivel 15, Marca de espadachín - Nivel 1",
      template: "HP máx. +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Velocidad del rayo",
      maxLvl: 10,
      req: "1H Estoque Lv.20",
      template: "Aumenta el daño crítico cuando el jugador tiene un estoque equipado+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Conocimiento de armas",
      maxLvl: 10,
      req: "1H Estoque Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "meteorito",
      maxLvl: 10,
      req: "1H Estoque Lv.30",
      template: "Aumenta la tasa crítica durante +{val} segundos después de dar un paso, cuando se equipa un estoque.",
      calc: (lvl) => [20, 25, 30, 35, 40, 45, 50, 55, 60, 65][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rapier's Secret",
      maxLvl: 10,
      req: "1H Estoque Lv.35",
      template: "Aumenta el ataque cuando se equipa un estoque+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con la espada",
      maxLvl: 10,
      req: "1H Estoque Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sobrecarga I (Estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llamas (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.50",
      template: "Aumenta el ataque al usar el elemento Fuego+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor acuático (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.50",
      template: "Aumenta el ataque al usar el elemento Agua+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor del viento (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Viento+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor de la Tierra (Estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.50",
      template: "Aumenta el ataque al usar el elemento Tierra+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Brillo brillante (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor oscuro (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.50",
      template: "Aumenta el ataque al usar el elemento oscuro+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en supervivencia (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia de empuje (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.60",
      template: "Aumenta el daño infligido a los enemigos débiles a los ataques de empuje+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Asalto al punto vital",
      maxLvl: 10,
      req: "1H Estoque Lv.70",
      template: "Aumenta el ataque mientras la mejora que aumenta el daño crítico está vigente+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Puñalada de punto vital",
      maxLvl: 10,
      req: "1H Estoque Lv.80",
      template: "Aumenta el daño crítico al usar habilidades+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Golpe preciso",
      maxLvl: 10,
      req: "1H Estoque Lv.85",
      template: "Aumenta la tasa de críticos al usar habilidades en +{val}%",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aqua Rise (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.90",
      template: "Aumenta el ataque al usar el elemento Agua+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Golpe elaborado",
      maxLvl: 10,
      req: "Estoque 1H Lv.95",
      template: "Después de golpear a un enemigo usando Switch, aplica un beneficio al jugador, lo que aumenta su daño crítico durante +{val} segundos.",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Carga acuática (estoque 1H)",
      maxLvl: 10,
      req: "1H Estoque Lv.100",
      template: "Aumenta el daño infligido con el elemento Agua+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Golpe de vulnerabilidad",
      maxLvl: 10,
      req: "1H Estoque Lv.105",
      template: "Increases player's Attack when Critical Rate buff is active+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Sobrecargo yo",
      maxLvl: 1,
      req: "Competencia con estoque 1H - Nivel 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en supervivencia",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 55, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 65, Experiencia en supervivencia (Estoque 1H) - Nivel 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces",
      maxLvl: 10,
      req: "Competencia con estoque 1H: nivel 75, gran experiencia en defensa (estoque 1H): nivel 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Ascenso acuático",
      maxLvl: 10,
      req: "Competencia con estoque 1H: nivel 90, golpe preciso: nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Agua. +{valor}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga acuática",
      maxLvl: 10,
      req: "1H Competencia con estoque: nivel 100, golpe elaborado: nivel 5",
      template: "Aumenta el daño causado por el elemento Agua. +{valor}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llama",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 50, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Fuego. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor acuático",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 50, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Agua. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor del viento",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 50, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Viento. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de la Tierra",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 50, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Tierra. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Brillo Brillo",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 50, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "resplandor oscuro",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 50, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento oscuro. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Técnica de espada avanzada",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 50, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Aumenta el poder de las habilidades con la espada en +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rompiendo los fundamentos",
      maxLvl: 10,
      req: "Competencia con estoque 1H - Nivel 50, Dominio de la habilidad con la espada (Estoque 1H) - Nivel 5",
      template: "Aumenta el valor de ruptura de las habilidades con espada en +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Ataque en cadena vinculado",
      maxLvl: 10,
      req: "1H Competencia con estoque - Nivel 110, Golpe de vulnerabilidad - Nivel 5",
      template: "Aumenta el poder de las habilidades con espada utilizadas en Switch en +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Club: [
    {
      name: "Entrenamiento de clubes",
      maxLvl: 10,
      req: "Club 1H Nivel 1",
      template: "Aumenta el daño del ataque normal cuando se equipa una maza+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Conocimiento para medicamentos",
      maxLvl: 10,
      req: "Club 1H Nivel 1",
      template: "Aumenta la cantidad de HP restaurado por elementos curativos cuando el garrote está equipado+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Blow",
      maxLvl: 10,
      req: "Club 1H Nivel 1",
      template: "Después de golpear a un enemigo usando Switch, el jugador y su grupo reciben una mejora que reduce el daño que reciben durante +{val} segundos.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Postura básica",
      maxLvl: 10,
      req: "Club 1H Nivel 1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Golpe duro",
      maxLvl: 10,
      req: "Club 1H Nivel 5",
      template: "Aumenta el daño infligido a enemigos débiles a ataques contundentes+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Competencia del club",
      maxLvl: 10,
      req: "Club 1H Nivel 5",
      template: "Increases club skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Marca de defensa",
      maxLvl: 10,
      req: "1H Club Lv.10",
      template: "Restaura HP cada +{val} segundos.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Mejora del control del club",
      maxLvl: 10,
      req: "1H Club Lv.10",
      template: "Disminuye el costo de SP necesario para dar el paso+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinto de batalla",
      maxLvl: 10,
      req: "1H Club Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinto de supervivencia",
      maxLvl: 10,
      req: "Competencia con garrote 1H - Nivel 15, Marca de defensa - Nivel 1",
      template: "HP máx. +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Rotura de armadura",
      maxLvl: 10,
      req: "Club 1H Lv.20",
      template: "Cada ataque tiene la posibilidad de aplicar una desventaja de defensa al enemigo atacado durante +{val} segundos.",
      calc: (lvl) => [16, 17, 18, 19, 20, 21, 22, 23, 24, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Conocimiento de armas",
      maxLvl: 10,
      req: "Club 1H Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rotura de arma",
      maxLvl: 10,
      req: "1H Club Lv.30",
      template: "Cada ataque tiene la posibilidad de aplicar una desventaja de ataque al enemigo atacado durante +{val} segundos.",
      calc: (lvl) => [27, 29, 31, 33, 35, 37, 39, 41, 43, 45][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Club's Secret",
      maxLvl: 10,
      req: "1H Club Lv.35",
      template: "Aumenta el ataque cuando se equipa una maza+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con la espada",
      maxLvl: 10,
      req: "1H Club Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sobrecarga I (Club 1H)",
      maxLvl: 10,
      req: "1H Club Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llamas (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Nivel 50",
      template: "Aumenta el ataque al usar el elemento Fuego+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor acuático (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Nivel 50",
      template: "Aumenta el ataque al usar el elemento Agua+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor del viento (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Nivel 50",
      template: "Aumenta el ataque cuando se usa el elemento Viento+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor de la Tierra (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Nivel 50",
      template: "Aumenta el ataque al usar el elemento Tierra+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Brillo Brillo (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Nivel 50",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor oscuro (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Nivel 50",
      template: "Aumenta el ataque al usar el elemento oscuro+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en supervivencia (Club 1H)",
      maxLvl: 10,
      req: "1H Club Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia contundente (Club 1H)",
      maxLvl: 10,
      req: "1H Club Lv.60",
      template: "Aumenta el daño infligido a enemigos débiles a ataques contundentes+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Golpe tallado",
      maxLvl: 10,
      req: "1H Club Lv.70",
      template: "Aumenta el ataque contra enemigos debilitados por [[Mark Debuff",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Potente copia de seguridad",
      maxLvl: 10,
      req: "1H Club Lv.80",
      template: "Al golpear a un enemigo usando Switch, mejora a los miembros del grupo aumentando su daño de debilidad contundente+{val}",
      calc: (lvl) => lvl * 0.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Alta defensa",
      maxLvl: 10,
      req: "Club 1H Lv.85",
      template: "Aumenta la defensa mientras el jugador tiene un beneficio activo.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Subida del viento (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Lv.90",
      template: "Aumenta el ataque cuando se usa el elemento Viento+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "estímulo",
      maxLvl: 10,
      req: "Club 1H Lv.95",
      template: "Después de golpear a un enemigo usando Switch, el jugador y su grupo reciben un beneficio que aumenta su ataque durante +{val} segundos.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga de viento (Club 1H)",
      maxLvl: 10,
      req: "Club 1H Nivel 100",
      template: "Aumenta el daño infligido con el elemento Viento+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Golpe grabado",
      maxLvl: 10,
      req: "Club 1H Lv.105",
      template: "Aumenta el ataque contra enemigos debilitados por [[Mark Debuff",
      calc: (lvl) => lvl * 20,
      bonusType: "atk_percent",
      active: true,
    },
  ],
  Dagger: [
    {
      name: "Entrenamiento con daga",
      maxLvl: 10,
      req: "Daga Lv.1",
      template: "Aumenta el ataque regular cuando se equipa una daga+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Represalias",
      maxLvl: 10,
      req: "Daga Lv.1",
      template: "Aumenta el ataque cuando HP está por debajo de +{val}%",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Golpe de daga",
      maxLvl: 10,
      req: "Daga Lv.1",
      template: "Increases damage dealt to an enemy which isn't focused on the player",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Postura básica",
      maxLvl: 10,
      req: "Daga Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Espada cruel",
      maxLvl: 10,
      req: "Daga Lv.5",
      template: "Aumenta el ataque contra enemigos con un estado alterado cuando se equipa una daga+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Competencia con la daga",
      maxLvl: 10,
      req: "Daga Lv.5",
      template: "Increases dagger skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Prueba de ladrón",
      maxLvl: 10,
      req: "Daga Lv.10",
      template: "Después de golpear a un enemigo usando Switch, lo envenena durante +{val} segundos (1 acumulación)",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Mejora del control de la daga",
      maxLvl: 10,
      req: "Daga Lv.10",
      template: "Disminuye el costo de SP necesario para dar el paso+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinto de batalla",
      maxLvl: 10,
      req: "Daga Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinto de supervivencia",
      maxLvl: 10,
      req: "Competencia con daga 1H - Nivel 15, Prueba de ladrón - Nivel 1",
      template: "HP máx. +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Evasión",
      maxLvl: 10,
      req: "Daga Lv.20",
      template: "Aumenta la posibilidad de evadir cualquier ataque (excepto los enfocados) cuando el jugador tiene menos del +{val}% del HP máximo.",
      calc: (lvl) => lvl * 2,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Conocimiento de armas",
      maxLvl: 10,
      req: "Daga Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Executer's Eyes",
      maxLvl: 10,
      req: "Daga Lv.30",
      template: "Cada ataque tiene la posibilidad de hacer que el enemigo reciba más daño con el siguiente golpe realizado durante los siguientes +{val} segundos.",
      calc: (lvl) =>
        [1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dagger's Secret",
      maxLvl: 10,
      req: "Daga Lv.35",
      template: "Aumenta el ataque cuando se equipa una daga+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con la espada",
      maxLvl: 10,
      req: "Daga Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sobrecarga I (Daga)",
      maxLvl: 10,
      req: "Daga Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llamas (daga)",
      maxLvl: 10,
      req: "Daga Lv.50",
      template: "Aumenta el ataque al usar el elemento Fuego+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor acuático (daga)",
      maxLvl: 10,
      req: "Daga Lv.50",
      template: "Aumenta el ataque al usar el elemento Agua+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor del viento (daga)",
      maxLvl: 10,
      req: "Daga Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Viento+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor de la Tierra (Daga)",
      maxLvl: 10,
      req: "Daga Lv.50",
      template: "Aumenta el ataque al usar el elemento Tierra+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Brillo Brillo (Daga)",
      maxLvl: 10,
      req: "Daga Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor oscuro (daga)",
      maxLvl: 10,
      req: "Daga Lv.50",
      template: "Aumenta el ataque al usar el elemento oscuro+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en supervivencia (daga)",
      maxLvl: 10,
      req: "Daga Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia con corte (daga)",
      maxLvl: 10,
      req: "Daga Lv.60",
      template: "Aumenta el daño infligido a los enemigos débiles para cortar ataques+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa (daga)",
      maxLvl: 10,
      req: "Daga Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Huelga de seguimiento",
      maxLvl: 10,
      req: "Daga Lv.70",
      template: "Aumenta el ataque contra enemigos afectados por [[Veneno (habilidad que inflige estado alterado)",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces (daga)",
      maxLvl: 10,
      req: "Daga Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Destello nítido",
      maxLvl: 10,
      req: "Daga Lv.80",
      template: "Aumenta el ataque contra enemigos afectados por [[Veneno (habilidad que inflige estado alterado)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bonificación por dolencia de estado",
      maxLvl: 10,
      req: "Daga Lv.85",
      template: "Aumenta el ataque contra enemigos afectados por cualquier estado alterado.",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Ascenso oscuro (daga)",
      maxLvl: 10,
      req: "Daga Lv.90",
      template: "Aumenta el ataque al usar el elemento oscuro+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Golpe pulido",
      maxLvl: 10,
      req: "Daga Lv.95",
      template: "Aumenta el ataque contra enemigos afectados por [[Veneno (habilidad que inflige estado alterado)",
      calc: (lvl) => lvl * 0.01,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Carga oscura (daga)",
      maxLvl: 10,
      req: "Daga Lv.100",
      template: "Aumenta el daño infligido con el elemento oscuro+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Asalto sangriento",
      maxLvl: 10,
      req: "Daga Lv.105",
      template: "Increases player's Attack when attacking enemies afflicted with [[Bleed (skill inflicting status ailment)",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
  ],
  Axe: [
    {
      name: "Entrenamiento con hacha",
      maxLvl: 10,
      req: "Hacha 2H Lv.1",
      template: "Aumenta el ataque normal cuando se equipa un hacha+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Body's Enhancement",
      maxLvl: 10,
      req: "Hacha 2H Lv.1",
      template: "Aumenta el ataque cuando se equipa un hacha+{val}",
      calc: (lvl) => [6, 7, 8, 9, 10, 11, 12, 13, 14, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Axe's Blow",
      maxLvl: 10,
      req: "Hacha 2H Lv.1",
      template: "Después de golpear a un enemigo usando Switch, mejora al jugador, lo que le hace recibir menos daño durante +{val} segundos.",
      calc: (lvl) => lvl * 2.5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Postura básica",
      maxLvl: 10,
      req: "Hacha 2H Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Espíritu de lucha",
      maxLvl: 10,
      req: "Hacha 2H Lv.5",
      template: "Aumenta la tasa de llenado del indicador de cambio+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia con el hacha",
      maxLvl: 10,
      req: "Hacha 2H Lv.5",
      template: "Increases axe skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Marca de mercenario",
      maxLvl: 10,
      req: "Hacha 2H Lv.10",
      template: "Reduce el costo de SP de todos los registros de habilidades con hacha+{val}",
      calc: (lvl) => lvl * 15,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Mejora del control del hacha",
      maxLvl: 10,
      req: "Hacha 2H Lv.10",
      template: "Disminuye el costo de SP necesario para dar el paso+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinto de batalla",
      maxLvl: 10,
      req: "Hacha 2H Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinto de supervivencia",
      maxLvl: 10,
      req: "Competencia con hacha 2H - Nivel 15, Marca de mercenario - Nivel 1",
      template: "HP máx. +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "dividir",
      maxLvl: 10,
      req: "Hacha 2H Lv.20",
      template: "Aumenta el ataque contra un enemigo con más del +{val}% de su HP máximo.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Conocimiento de armas",
      maxLvl: 10,
      req: "Hacha 2H Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Kongou",
      maxLvl: 10,
      req: "Hacha 2H Lv.30",
      template: "Decreases damage taken if it's more than +{val}% of character's max HP.",
      calc: (lvl) => [30, 35, 40, 45, 50, 55, 60, 65, 70, 75][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Axe's Secret",
      maxLvl: 10,
      req: "Hacha 2H Lv.35",
      template: "Aumenta el ataque cuando se equipa un hacha+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con la espada",
      maxLvl: 10,
      req: "Hacha 2H Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sobrecarga I (Hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llamas (hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.50",
      template: "Aumenta el ataque al usar el elemento Fuego+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor acuático (hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.50",
      template: "Aumenta el ataque al usar el elemento Agua+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor del viento (hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Viento+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor de la Tierra (Hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.50",
      template: "Aumenta el ataque al usar el elemento Tierra+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Brillo Brillo (Hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor oscuro (Hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.50",
      template: "Aumenta el ataque al usar el elemento oscuro+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en supervivencia (hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia contundente (hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.60",
      template: "Aumenta el daño infligido a enemigos débiles a ataques contundentes+{val}",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Gran experiencia en defensa (hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Poder poderoso",
      maxLvl: 10,
      req: "Hacha 2H Lv.70",
      template: "Aumenta el ataque en proporción al HP restante+{val}",
      calc: (lvl) =>
        [210, 220, 230, 240, 250, 260, 270, 280, 290, 300][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces (hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Mejora de reversión",
      maxLvl: 10,
      req: "Hacha 2H Lv.80",
      template: "When receiving a hit, there's a chance to obtain a buff which increases Attack+{val}",
      calc: (lvl) =>
        [15.5, 16, 16.5, 17, 17.5, 18, 18.5, 19, 19.5, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Asalto dinámico",
      maxLvl: 10,
      req: "Hacha 2H Lv.85",
      template: "Aumenta el jugador\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) => lvl * 0.25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Elevación de la Tierra (Hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.90",
      template: "Aumenta el ataque al usar el elemento Tierra+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con una sola espada (Hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.95",
      template: "Aumenta el poder de las habilidades con espada única en +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga de tierra (hacha 2H)",
      maxLvl: 10,
      req: "Hacha 2H Lv.100",
      template: "Aumenta el daño causado por el elemento Tierra+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Ataque poderoso",
      maxLvl: 10,
      req: "Hacha 2H Lv.105",
      template: "Increases player's Attack proportionally to the percentage of remaining HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Sobrecargo yo",
      maxLvl: 1,
      req: "Competencia con hacha 2H - Nivel 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en supervivencia",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 55, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 65, Experiencia en supervivencia (Hacha 2H) - Nivel 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces",
      maxLvl: 10,
      req: "Competencia con el hacha 2H: nivel 75, gran experiencia en defensa (hacha 2H): nivel 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Ascenso de la Tierra",
      maxLvl: 10,
      req: "Competencia con hacha 2H: nivel 90, asalto dinámico: nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Tierra. +{valor}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga de tierra",
      maxLvl: 10,
      req: "Competencia con el hacha 2H: nivel 100, dominio de la habilidad con una sola espada (hacha 2H): nivel 5",
      template: "Aumenta el daño causado por el elemento Tierra. +{valor}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dominio de la habilidad con una sola espada",
      maxLvl: 10,
      req: "Competencia con hacha 2H: nivel 95, asalto dinámico: nivel 5",
      template: "Aumenta el poder de las habilidades con espada única en +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llama",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 50, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Fuego. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor acuático",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 50, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Agua. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor del viento",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 50, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Viento. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de la Tierra",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 50, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Tierra. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Brillo Brillo",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 50, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "resplandor oscuro",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 50, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento oscuro. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Técnica de espada avanzada",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 50, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Aumenta el poder de las habilidades con la espada en +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rompiendo los fundamentos",
      maxLvl: 10,
      req: "Competencia con el hacha 2H - Nivel 50, Dominio de la habilidad con la espada (Hacha 2H) - Nivel 5",
      template: "Aumenta el valor de ruptura de las habilidades con espada en +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Ataque en cadena vinculado",
      maxLvl: 10,
      req: "Competencia con hacha 2H: nivel 110, ataque poderoso: nivel 5",
      template: "Aumenta el poder de las habilidades con espada utilizadas en Switch en +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Spear: [
    {
      name: "Entrenamiento con lanza",
      maxLvl: 10,
      req: "Lanza 2H Lv.1",
      template: "Aumenta el ataque normal cuando se equipa una lanza+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Estampida",
      maxLvl: 10,
      req: "Lanza 2H Lv.1",
      template: "Aumenta el ataque durante +{val} segundos después de dar un paso, cuando se equipa una lanza.",
      calc: (lvl) => lvl * 2,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Spear's Blow",
      maxLvl: 10,
      req: "Lanza 2H Lv.1",
      template: "Después de golpear a un enemigo usando Switch, mejora al jugador, lo que aumenta su índice de críticos durante +{val} segundos.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Postura básica",
      maxLvl: 10,
      req: "Lanza 2H Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Vendaval",
      maxLvl: 10,
      req: "Lanza 2H Lv.5",
      template: "Acorta el tiempo de recuperación de los registros de habilidades de lanza+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia con la lanza",
      maxLvl: 10,
      req: "Lanza 2H Lv.5",
      template: "Increases spear skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "marca de caballero",
      maxLvl: 10,
      req: "Lanza 2H Lv.10",
      template: "Restaura SP por cada enemigo derrotado+{val}",
      calc: (lvl) => lvl * 3,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Mejora del control de lanza",
      maxLvl: 10,
      req: "Lanza 2H Lv.10",
      template: "Disminuye el costo de SP necesario para dar el paso+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinto de batalla",
      maxLvl: 10,
      req: "Lanza 2H Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinto de supervivencia",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 15, Marca de caballero - Nivel 1",
      template: "HP máx. +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "colmillo",
      maxLvl: 10,
      req: "Lanza 2H Lv.20",
      template: "Aumenta el ataque contra enemigos con un estado alterado cuando se equipa una lanza+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Conocimiento de armas",
      maxLvl: 10,
      req: "Lanza 2H Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Danza de la lanza",
      maxLvl: 10,
      req: "Lanza 2H Lv.30",
      template: "Descripción pendiente (código wiki)",
      calc: (lvl) => 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Spear's Secret",
      maxLvl: 10,
      req: "Lanza 2H Lv.35",
      template: "Aumenta el ataque cuando se equipa una lanza+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con la espada",
      maxLvl: 10,
      req: "Lanza 2H Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sobrecarga I (Lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llamas (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.50",
      template: "Aumenta el ataque al usar el elemento Fuego+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor acuático (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.50",
      template: "Aumenta el ataque al usar el elemento Agua+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor del viento (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Viento+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor de la Tierra (Lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.50",
      template: "Aumenta el ataque al usar el elemento Tierra+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Brillo Brillo (Lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor oscuro (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.50",
      template: "Aumenta el ataque al usar el elemento oscuro+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en supervivencia (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia de empuje (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.60",
      template: "Aumenta el daño infligido a los enemigos débiles a los ataques de empuje+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Interruptor de marcado",
      maxLvl: 10,
      req: "Lanza 2H Lv.70",
      template: "Al golpear a un enemigo usando Switch, tiene la posibilidad de infligir al enemigo una [[Desventaja de estigma]] durante +{val} segundos.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Persecución de los débiles",
      maxLvl: 10,
      req: "Lanza 2H Lv.80",
      template: "Aumenta el ataque contra enemigos debilitados+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio general de la habilidad con la espada (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.85",
      template: "Aumenta el poder de Sword Skills en espacios activos, así como aquellos que forman parte de Connect Chain en un +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Aumento del viento (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.90",
      template: "Aumenta el ataque cuando se usa el elemento Viento+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Arte de destrucción",
      maxLvl: 10,
      req: "Lanza 2H Lv.95",
      template: "Aumenta la eficiencia del descanso+{val}",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga de viento (lanza 2H)",
      maxLvl: 10,
      req: "Lanza 2H Lv.100",
      template: "Aumenta el daño infligido con el elemento Viento+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Interruptor de decadencia de armadura",
      maxLvl: 10,
      req: "Lanza 2H Lv.105",
      template: "Al golpear a un enemigo usando Switch, tiene la posibilidad de infligir al enemigo [[Armor Decay Debuff]] durante +{val} segundos.",
      calc: (lvl) => lvl * 30,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Sobrecargo yo",
      maxLvl: 1,
      req: "Competencia con lanza 2H - Nivel 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en supervivencia",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 55, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 65, Experiencia en supervivencia (Lanza 2H) - Nivel 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces",
      maxLvl: 10,
      req: "Competencia con lanza 2H: nivel 75, gran experiencia en defensa (lanza 2H): nivel 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "aumento del viento",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 90, Dominio general de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Viento. +{valor}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga de viento",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 100, Arte de destrucción - Nivel 5",
      template: "Aumenta el daño causado por el elemento Viento. +{valor}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dominio general de la habilidad con la espada",
      maxLvl: 10,
      req: "Competencia con lanza: nivel 85, experiencia en ataque feroz (lanza 2H): nivel 5",
      template: "Aumenta el poder de Sword Skills en espacios activos, así como aquellos que forman parte de Connect Chain en un +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llama",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 50, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Fuego. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor acuático",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 50, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Agua. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor del viento",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 50, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Viento. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de la Tierra",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 50, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Tierra. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Brillo Brillo",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 50, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "resplandor oscuro",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 50, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento oscuro. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Técnica de espada avanzada",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 50, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el poder de las habilidades con la espada en +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rompiendo los fundamentos",
      maxLvl: 10,
      req: "Competencia con lanza 2H - Nivel 50, Dominio de la habilidad con la espada (Lanza 2H) - Nivel 5",
      template: "Aumenta el valor de ruptura de las habilidades con espada en +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Ataque en cadena vinculado",
      maxLvl: 10,
      req: "Competencia con lanza 2H: nivel 110, interruptor de deterioro de armadura: nivel 1",
      template: "Aumenta el poder de las habilidades con espada utilizadas en Switch en +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Bow: [
    {
      name: "Entrenamiento con arco",
      maxLvl: 10,
      req: "Arco Lv.1",
      template: "Aumenta el ataque normal cuando se equipa un arco+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "perforar",
      maxLvl: 10,
      req: "Arco Lv.1",
      template: "Aumenta el ataque cuando HP está por encima de +{val}%",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "destello",
      maxLvl: 10,
      req: "Arco Lv.1",
      template: "Después de golpear a un enemigo usando Switch, mejora al jugador, lo que aumenta su índice de críticos durante +{val} segundos.",
      calc: (lvl) => lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Postura básica",
      maxLvl: 10,
      req: "Arco Lv.1",
      template: "Passively increases the player's damage dealt with every attack+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Disparo preciso",
      maxLvl: 10,
      req: "Arco Lv.5",
      template: "Aumenta el daño infligido a los enemigos débiles a los ataques de empuje+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Competencia con el arco",
      maxLvl: 10,
      req: "Arco Lv.5",
      template: "Increases bow skill records' damage by +{val}%",
      calc: (lvl) => [11, 12, 13, 14, 15, 16, 17, 18, 19, 20][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Prueba de arquero",
      maxLvl: 10,
      req: "Arco Lv.10",
      template: "Acorta el tiempo necesario para cargar algunos de los récords de habilidad con el arco+{val}",
      calc: (lvl) => lvl * 20,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Mejora del control del arco",
      maxLvl: 10,
      req: "Arco Lv.10",
      template: "Disminuye el costo de SP necesario para dar el paso+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "sp",
      active: true,
    },
    {
      name: "Instinto de batalla",
      maxLvl: 10,
      req: "Arco Lv.15",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Instinto de supervivencia",
      maxLvl: 10,
      req: "Competencia con arco - Nivel 15, Prueba de arquero - Nivel 1",
      template: "HP máx. +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Predator's Keen Eye",
      maxLvl: 10,
      req: "Arco Lv.20",
      template: "Aumenta el ataque contra un enemigo con menos del +{val}% de su HP máximo.",
      calc: (lvl) => [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Conocimiento de armas",
      maxLvl: 10,
      req: "Arco Lv.25",
      template: "Passively increases the player's Attack+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 1, 1, 1, 1, 2, 2][
          lvl - 1
        ] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Luna creciente",
      maxLvl: 10,
      req: "Arco Lv.30",
      template: "Después de golpear a un enemigo con una habilidad de arco en Switch, se activa una mejora que durante +{val} segundos (o hasta que el jugador reciba daño) aumenta el ataque en un +{val}%.",
      calc: (lvl) => lvl * 3,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Bow's Secret",
      maxLvl: 10,
      req: "Arco Lv.35",
      template: "Aumenta el ataque cuando se equipa un arco+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con la espada",
      maxLvl: 10,
      req: "Arco Lv.40",
      template: "Passively increases the power of all player's offensive skill records+{val}",
      calc: (lvl) =>
        [1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 1, 1, 1, 2, 2][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Sobrecarga I (arco)",
      maxLvl: 10,
      req: "Arco Lv.45",
      template: "Allows charging \"Switch\" meter to third level+{val}",
      calc: (lvl) => lvl * 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llama (arco)",
      maxLvl: 10,
      req: "Arco Lv.50",
      template: "Aumenta el ataque al usar el elemento Fuego+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor acuático (arco)",
      maxLvl: 10,
      req: "Arco Lv.50",
      template: "Aumenta el ataque al usar el elemento Agua+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor del viento (arco)",
      maxLvl: 10,
      req: "Arco Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Viento+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor de la Tierra (Arco)",
      maxLvl: 10,
      req: "Arco Lv.50",
      template: "Aumenta el ataque al usar el elemento Tierra+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Brillo Resplandor (Arco)",
      maxLvl: 10,
      req: "Arco Lv.50",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Resplandor oscuro (arco)",
      maxLvl: 10,
      req: "Arco Lv.50",
      template: "Aumenta el ataque al usar el elemento oscuro+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en supervivencia (arco)",
      maxLvl: 10,
      req: "Arco Lv.55",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Competencia en empuje (arco)",
      maxLvl: 10,
      req: "Arco Lv.60",
      template: "Aumenta el daño infligido a los enemigos débiles a los ataques de empuje+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa (arco)",
      maxLvl: 10,
      req: "Arco Lv.65",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Golpe sorpresa",
      maxLvl: 10,
      req: "Arco Lv.70",
      template: "Aumenta el ataque contra enemigos que no apuntan al jugador+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces (arco)",
      maxLvl: 10,
      req: "Arco Lv.75",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rotura dura (Arco)",
      maxLvl: 10,
      req: "Arco Lv.80",
      template: "Aumenta el jugador\"s Attack against enemies in "Break" state+{val}',
      calc: (lvl) =>
        [205, 210, 215, 220, 225, 230, 235, 240, 245, 250][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Golpe inverso",
      maxLvl: 10,
      req: "Arco Lv.85",
      template: "Aumenta el ataque según el porcentaje de HP restante.",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Subida de brillo (arco)",
      maxLvl: 10,
      req: "Arco Lv.90",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado+{val}",
      calc: (lvl) => [55, 60, 65, 70, 75, 80, 85, 90, 95, 100][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Dominio de la habilidad con una sola espada (arco)",
      maxLvl: 10,
      req: "Arco Lv.95",
      template: "Aumenta el poder de las habilidades con espada única en +{val}%",
      calc: (lvl) => [7, 9, 11, 13, 15, 17, 19, 21, 23, 25][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga de brillo (arco)",
      maxLvl: 10,
      req: "Arco Lv.100",
      template: "Aumenta el daño infligido con el elemento Sagrado+{val}",
      calc: (lvl) =>
        [10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Asalto inverso",
      maxLvl: 10,
      req: "Arco Lv.105",
      template: "Increases player's Attack proportionally to the percentage of lost HP+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    ,
    {
      name: "Sobrecargo yo",
      maxLvl: 1,
      req: "Competencia con arco - Nivel 45",
      template: "Allows charging 'Switch' meter to third level. +{val}",
      calc: (lvl) => 200,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en supervivencia",
      maxLvl: 10,
      req: "Dominio del arco: nivel 55, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Increases player's HP by +{val}",
      calc: (lvl) => lvl * 100,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Fuerte experiencia en defensa",
      maxLvl: 10,
      req: "Competencia con arco: nivel 65, experiencia en supervivencia (arco): nivel 5",
      template: "Increases player's Defense by +{val}",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en ataques feroces",
      maxLvl: 10,
      req: "Competencia con arco: nivel 75, gran experiencia en defensa (arco): nivel 5",
      template: "Increases player's Attack by +{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "ruptura dura",
      maxLvl: 10,
      req: "Competencia con arco: nivel 80, experiencia en ataque feroz (arco): nivel 5",
      template: "Increases player's Attack against enemies in 'Break' state. +{val}",
      calc: (lvl) => 200 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "aumento de brillo",
      maxLvl: 10,
      req: "Competencia con arco: nivel 90, golpe inverso: nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado. +{valor}",
      calc: (lvl) => 50 + lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Carga de brillo",
      maxLvl: 10,
      req: "Dominio del arco: nivel 100, dominio de la habilidad con una sola espada (arco): nivel 5",
      template: "Aumenta el daño infligido con el elemento Sagrado. +{valor}",
      calc: (lvl) => 10 + lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Dominio de la habilidad con una sola espada",
      maxLvl: 10,
      req: "Competencia con arco: nivel 95, golpe inverso: nivel 5",
      template: "Aumenta el poder de las habilidades con espada única en +{val}%",
      calc: (lvl) => 5 + lvl * 2,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de llama",
      maxLvl: 10,
      req: "Dominio del arco: nivel 50, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Fuego. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor acuático",
      maxLvl: 10,
      req: "Dominio del arco: nivel 50, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Agua. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor del viento",
      maxLvl: 10,
      req: "Dominio del arco: nivel 50, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Viento. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resplandor de la Tierra",
      maxLvl: 10,
      req: "Dominio del arco: nivel 50, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Tierra. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Brillo Brillo",
      maxLvl: 10,
      req: "Dominio del arco: nivel 50, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento Sagrado. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "resplandor oscuro",
      maxLvl: 10,
      req: "Dominio del arco: nivel 50, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Aumenta el ataque cuando se usa el elemento oscuro. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Técnica de espada avanzada",
      maxLvl: 10,
      req: "Dominio del arco: nivel 50, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Aumenta el poder de las habilidades con la espada en +{val}%",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Rompiendo los fundamentos",
      maxLvl: 10,
      req: "Dominio del arco: nivel 50, dominio de la habilidad con la espada (arco): nivel 5",
      template: "Aumenta el valor de ruptura de las habilidades con espada en +{val}%",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Ataque en cadena vinculado",
      maxLvl: 10,
      req: "Competencia con arco: nivel 110, asalto inverso: nivel 5",
      template: "Aumenta el poder de las habilidades con espada utilizadas en Switch en +{val}%",
      calc: (lvl) => lvl * 10,
      bonusType: "passive",
      active: true,
    },
  ],
  Shield: [
    {
      name: "Entrenamiento con escudo",
      maxLvl: 10,
      req: "Escudo Nv.1",
      template: "Aumenta la defensa cuando se equipa un escudo+{val}",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Resistir",
      maxLvl: 10,
      req: "Escudo Nv.1",
      template: "Aumenta la resistencia contra daños de estado cuando se equipa un escudo+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "proteger",
      maxLvl: 10,
      req: "Escudo Nv.1",
      template: "Después de golpear a un enemigo usando Switch, mejora al jugador, lo que aumenta su defensa durante +{val} segundos.",
      calc: (lvl) => lvl * 0.5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Guardia decisiva",
      maxLvl: 10,
      req: "Escudo Lv.5",
      template: "Reduce el daño recibido en un porcentaje que depende de la cantidad de registros de habilidades de escudo equipados+{val}",
      calc: (lvl) =>
        [2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Reflexión",
      maxLvl: 10,
      req: "Escudo Lv.10",
      template: "Refleja una parte del daño recibido hacia un enemigo+{val}",
      calc: (lvl) => lvl * 10,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Instinto de supervivencia",
      maxLvl: 10,
      req: "Competencia con escudo: nivel 15, reflexión: nivel 1",
      template: "HP máx. +{val}%",
      calc: (lvl) =>
        [
          1.4, 1.8, 2.2, 2.6, 3, 3.4000000000000004, 3.8000000000000003, 4.2,
          4.6, 5,
        ][lvl - 1] || 0,
      bonusType: "hp_percent",
      active: true,
    },
    {
      name: "Vitalidad",
      maxLvl: 10,
      req: "Escudo Lv.20",
      template: "Aumenta la resistencia al retroceso cuando se equipa un escudo+{val}",
      calc: (lvl) => [12, 14, 16, 18, 20, 22, 24, 26, 28, 30][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Escudo de conocimiento",
      maxLvl: 10,
      req: "Escudo Lv.25",
      template: "Passively increases the player's Defense+{val}",
      calc: (lvl) =>
        [1.4, 1.8, 2.2, 2.6, 3, 3.4, 3.8, 4.2, 4.6, 5][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "trascendente",
      maxLvl: 10,
      req: "Escudo Lv.30",
      template: "Aumenta el daño infligido con los registros de habilidad del escudo+{val}",
      calc: (lvl) => [30, 35, 40, 45, 50][lvl - 1] || 0,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Curación con escudo",
      maxLvl: 10,
      req: "Escudo Lv.55",
      template: "Recupera cierta cantidad de HP cada +{val} segundos.",
      calc: (lvl) => lvl * 5,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Experiencia en recuperación",
      maxLvl: 10,
      req: "Escudo Lv.60",
      template: "Aumenta pasivamente la efectividad de los elementos curativos+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Mejora del cuerpo (escudo)",
      maxLvl: 10,
      req: "Escudo Lv.65",
      template: "HP máx. +{val}",
      calc: (lvl) => lvl * 50,
      bonusType: "hp_flat",
      active: true,
    },
    {
      name: "Curación de campo",
      maxLvl: 10,
      req: "Escudo Lv.70",
      template: "Aumenta pasivamente la eficacia de las plantas curativas+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Golpe poderoso",
      maxLvl: 10,
      req: "Escudo Lv.75",
      template: "Aumenta el daño contra enemigos débiles a embotados+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    {
      name: "Estímulo físico (escudo)",
      maxLvl: 10,
      req: "Escudo Lv.80",
      template: "Passively increases player's HP+{val}",
      calc: (lvl) =>
        [525, 550, 575, 600, 625, 650, 675, 700, 725, 750][lvl - 1] || 0,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Barra poderosa",
      maxLvl: 10,
      req: "Escudo Lv.85",
      template: "Aumenta el daño contra enemigos débiles para cortar+{val}",
      calc: (lvl) => lvl * 1,
      bonusType: "atk_percent",
      active: true,
    },
    ,
    {
      name: "Estímulo físico",
      maxLvl: 10,
      req: "Competencia con escudo: nivel 80, golpe poderoso: nivel 5",
      template: "Passively increases player's HP. +{val}",
      calc: (lvl) => 500 + lvl * 25,
      bonusType: "passive",
      active: true,
    },
    {
      name: "Empuje poderoso",
      maxLvl: 10,
      req: "Competencia con escudo: nivel 90, corte poderoso: nivel 5",
      template: "Aumenta el daño contra enemigos débiles al empuje. +{valor}",
      calc: (lvl) => lvl * 1,
      bonusType: "passive",
      active: true,
    },
  ],
};
